/* Copyright (c) 2017-2026 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2017-2026 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#include "utils/test.h"

TPP_ASSERT_EXPANDS("10", __TPP_EVAL(10))
TPP_ASSERT_EXPANDS("10", __TPP_EVAL(0xa))
TPP_ASSERT_EXPANDS("10", __TPP_EVAL(+10))
TPP_ASSERT_EXPANDS("-10", __TPP_EVAL(-10))
TPP_ASSERT_EXPANDS("-1", __TPP_EVAL(-1))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(-0))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(!10))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(!0))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(!!10))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(!!0))
TPP_ASSERT_EXPANDS("-11", __TPP_EVAL(~10))
TPP_ASSERT_EXPANDS("-2", __TPP_EVAL(~1))
TPP_ASSERT_EXPANDS("-1", __TPP_EVAL(~0))
TPP_ASSERT_EXPANDS("-1", __TPP_EVAL(~-0))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(~-1))
TPP_ASSERT_EXPANDS("97", __TPP_EVAL('a'))
TPP_ASSERT_EXPANDS("98", __TPP_EVAL('b'))
TPP_ASSERT_EXPANDS("99", __TPP_EVAL('c'))

TPP_ASSERT_EXPANDS("1", __TPP_EVAL(!""))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(!"foo"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(!!""))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(!!"foo"))

TPP_ASSERT_EXPANDS("\"no\"", __TPP_EVAL("" ? "yes" : "no"))
TPP_ASSERT_EXPANDS("\"yes\"", __TPP_EVAL("foo" ? "yes" : "no"))

TPP_ASSERT_EXPANDS("0", __TPP_EVAL(#""))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(#"a"))
TPP_ASSERT_EXPANDS("2", __TPP_EVAL(#"ab"))
TPP_ASSERT_EXPANDS("3", __TPP_EVAL(#"abc"))

#assert foo(bar)
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(#foo(bar)))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(#foo(baz)))
#pragma TPP extension(push, "-ftrigraphs")
#pragma TPP warning(push, "-Wno-trigraphs")
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(??=""))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(??="a"))
TPP_ASSERT_EXPANDS("2", __TPP_EVAL(??="ab"))
TPP_ASSERT_EXPANDS("3", __TPP_EVAL(??="abc"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(??=foo(bar)))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(??=foo(baz)))
#unassert foo(bar)
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(??=foo(bar)))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(??=foo(baz)))
#pragma TPP warning(pop)
#pragma TPP extension(pop)
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(#foo(bar)))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(#foo(baz)))

TPP_ASSERT_EXPANDS("0", __TPP_EVAL(defined MY_MACRO))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(defined(MY_MACRO)))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL((defined MY_MACRO)))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL((defined(MY_MACRO))))
#define MY_MACRO
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(defined MY_MACRO))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(defined(MY_MACRO)))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL((defined MY_MACRO)))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL((defined(MY_MACRO))))
#undef MY_MACRO

TPP_ASSERT_EXPANDS("\"no\"",    __TPP_EVAL(if (0) "yes" elif (0) "maybe" else "no"))
TPP_ASSERT_EXPANDS("\"maybe\"", __TPP_EVAL(if (0) "yes" elif (1) "maybe" else "no"))
TPP_ASSERT_EXPANDS("\"yes\"",   __TPP_EVAL(if (1) "yes" elif (0) "maybe" else "no"))
TPP_ASSERT_EXPANDS("\"yes\"",   __TPP_EVAL(if (1) "yes" elif (1) "maybe" else "no"))

TPP_ASSERT_WARNING_BEGIN("-Wundef")
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(NO_SUCH_MACRO))
TPP_ASSERT_WARNING_END("-Wundef")
TPP_ASSERT_WARNING_BEGIN("-Wundef")
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(NO_SUCH_MACRO(10, (20), 30)))
TPP_ASSERT_WARNING_END("-Wundef")
TPP_ASSERT_WARNING_BEGIN("-Wundef")
TPP_ASSERT_EXPANDS("2", __TPP_EVAL(NO_SUCH_MACRO + 2))
TPP_ASSERT_WARNING_END("-Wundef")
TPP_ASSERT_WARNING_BEGIN("-Wundef")
TPP_ASSERT_EXPANDS("2", __TPP_EVAL(NO_SUCH_MACRO(10, (20), 30) + 2))
TPP_ASSERT_WARNING_END("-Wundef")

TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"))

TPP_ASSERT_EXPANDS("0", __TPP_EVAL("abc"[-1]))
TPP_ASSERT_EXPANDS("97", __TPP_EVAL("abc"[0]))
TPP_ASSERT_EXPANDS("98", __TPP_EVAL("abc"[1]))
TPP_ASSERT_EXPANDS("99", __TPP_EVAL("abc"[2]))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("abc"[3]))

TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[:]))

TPP_ASSERT_EXPANDS("\"bc\"", __TPP_EVAL("abc"[1:]))
TPP_ASSERT_EXPANDS("\"c\"", __TPP_EVAL("abc"[2:]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[3:]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[4:]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[5:]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[6:]))

TPP_ASSERT_EXPANDS("\"a\"", __TPP_EVAL("abc"[:1]))
TPP_ASSERT_EXPANDS("\"ab\"", __TPP_EVAL("abc"[:2]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[:3]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[:4]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[:5]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[:6]))

TPP_ASSERT_EXPANDS("\"c\"", __TPP_EVAL("abc"[-1:]))
TPP_ASSERT_EXPANDS("\"bc\"", __TPP_EVAL("abc"[-2:]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[-3:]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[-4:]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[-5:]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[-6:]))

TPP_ASSERT_EXPANDS("\"ab\"", __TPP_EVAL("abc"[:-1]))
TPP_ASSERT_EXPANDS("\"a\"", __TPP_EVAL("abc"[:-2]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[:-3]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[:-4]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[:-5]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[:-6]))

TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[-1:-1]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[-1:0]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[-1:1]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[-1:2]))
TPP_ASSERT_EXPANDS("\"c\"", __TPP_EVAL("abc"[-1:3]))
TPP_ASSERT_EXPANDS("\"c\"", __TPP_EVAL("abc"[-1:4]))

TPP_ASSERT_EXPANDS("\"ab\"", __TPP_EVAL("abc"[0:-1]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[0:0]))
TPP_ASSERT_EXPANDS("\"a\"", __TPP_EVAL("abc"[0:1]))
TPP_ASSERT_EXPANDS("\"ab\"", __TPP_EVAL("abc"[0:2]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[0:3]))
TPP_ASSERT_EXPANDS("\"abc\"", __TPP_EVAL("abc"[0:4]))

TPP_ASSERT_EXPANDS("\"b\"", __TPP_EVAL("abc"[1:-1]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[1:0]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[1:1]))
TPP_ASSERT_EXPANDS("\"b\"", __TPP_EVAL("abc"[1:2]))
TPP_ASSERT_EXPANDS("\"bc\"", __TPP_EVAL("abc"[1:3]))
TPP_ASSERT_EXPANDS("\"bc\"", __TPP_EVAL("abc"[1:4]))

TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[2:-1]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[2:0]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[2:1]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[2:2]))
TPP_ASSERT_EXPANDS("\"c\"", __TPP_EVAL("abc"[2:3]))
TPP_ASSERT_EXPANDS("\"c\"", __TPP_EVAL("abc"[2:4]))

TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[3:-1]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[3:0]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[3:1]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[3:2]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[3:3]))
TPP_ASSERT_EXPANDS("\"\"", __TPP_EVAL("abc"[3:4]))


TPP_ASSERT_EXPANDS("7", __TPP_EVAL(1 + 2 * 3))
TPP_ASSERT_EXPANDS("5", __TPP_EVAL(1 * 2 + 3))

TPP_ASSERT_EXPANDS("9",  __TPP_EVAL(-3 * -3))
TPP_ASSERT_EXPANDS("6",  __TPP_EVAL(-3 * -2))
TPP_ASSERT_EXPANDS("3",  __TPP_EVAL(-3 * -1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-3 * 0))
TPP_ASSERT_EXPANDS("-3", __TPP_EVAL(-3 * 1))
TPP_ASSERT_EXPANDS("-6", __TPP_EVAL(-3 * 2))
TPP_ASSERT_EXPANDS("-9", __TPP_EVAL(-3 * 3))
TPP_ASSERT_EXPANDS("6",  __TPP_EVAL(-2 * -3))
TPP_ASSERT_EXPANDS("4",  __TPP_EVAL(-2 * -2))
TPP_ASSERT_EXPANDS("2",  __TPP_EVAL(-2 * -1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-2 * 0))
TPP_ASSERT_EXPANDS("-2", __TPP_EVAL(-2 * 1))
TPP_ASSERT_EXPANDS("-4", __TPP_EVAL(-2 * 2))
TPP_ASSERT_EXPANDS("-6", __TPP_EVAL(-2 * 3))
TPP_ASSERT_EXPANDS("3",  __TPP_EVAL(-1 * -3))
TPP_ASSERT_EXPANDS("2",  __TPP_EVAL(-1 * -2))
TPP_ASSERT_EXPANDS("1",  __TPP_EVAL(-1 * -1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-1 * 0))
TPP_ASSERT_EXPANDS("-1", __TPP_EVAL(-1 * 1))
TPP_ASSERT_EXPANDS("-2", __TPP_EVAL(-1 * 2))
TPP_ASSERT_EXPANDS("-3", __TPP_EVAL(-1 * 3))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 * -3))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 * -2))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 * -1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 * 0))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 * 1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 * 2))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 * 3))
TPP_ASSERT_EXPANDS("-3", __TPP_EVAL(1 * -3))
TPP_ASSERT_EXPANDS("-2", __TPP_EVAL(1 * -2))
TPP_ASSERT_EXPANDS("-1", __TPP_EVAL(1 * -1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(1 * 0))
TPP_ASSERT_EXPANDS("1",  __TPP_EVAL(1 * 1))
TPP_ASSERT_EXPANDS("2",  __TPP_EVAL(1 * 2))
TPP_ASSERT_EXPANDS("3",  __TPP_EVAL(1 * 3))
TPP_ASSERT_EXPANDS("-6", __TPP_EVAL(2 * -3))
TPP_ASSERT_EXPANDS("-4", __TPP_EVAL(2 * -2))
TPP_ASSERT_EXPANDS("-2", __TPP_EVAL(2 * -1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(2 * 0))
TPP_ASSERT_EXPANDS("2",  __TPP_EVAL(2 * 1))
TPP_ASSERT_EXPANDS("4",  __TPP_EVAL(2 * 2))
TPP_ASSERT_EXPANDS("6",  __TPP_EVAL(2 * 3))
TPP_ASSERT_EXPANDS("-9", __TPP_EVAL(3 * -3))
TPP_ASSERT_EXPANDS("-6", __TPP_EVAL(3 * -2))
TPP_ASSERT_EXPANDS("-3", __TPP_EVAL(3 * -1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(3 * 0))
TPP_ASSERT_EXPANDS("3",  __TPP_EVAL(3 * 1))
TPP_ASSERT_EXPANDS("6",  __TPP_EVAL(3 * 2))
TPP_ASSERT_EXPANDS("9",  __TPP_EVAL(3 * 3))

#define TPP_ASSERT_DIVMOD(lhs, rhs, div, mod)       \
	TPP_ASSERT_EXPANDS(#div, __TPP_EVAL(lhs / rhs)) \
	TPP_ASSERT_EXPANDS(#mod, __TPP_EVAL(lhs % rhs))
TPP_ASSERT_DIVMOD(-3, -3,  1,  0)
TPP_ASSERT_DIVMOD(-3, -2,  1, -1)
TPP_ASSERT_DIVMOD(-3, -1,  3,  0)
TPP_ASSERT_DIVMOD(-3,  1, -3,  0)
TPP_ASSERT_DIVMOD(-3,  2, -1, -1)
TPP_ASSERT_DIVMOD(-3,  3, -1,  0)
TPP_ASSERT_DIVMOD(-2, -3,  0, -2)
TPP_ASSERT_DIVMOD(-2, -2,  1,  0)
TPP_ASSERT_DIVMOD(-2, -1,  2,  0)
TPP_ASSERT_DIVMOD(-2,  1, -2,  0)
TPP_ASSERT_DIVMOD(-2,  2, -1,  0)
TPP_ASSERT_DIVMOD(-2,  3,  0, -2)
TPP_ASSERT_DIVMOD(-1, -3,  0, -1)
TPP_ASSERT_DIVMOD(-1, -2,  0, -1)
TPP_ASSERT_DIVMOD(-1, -1,  1,  0)
TPP_ASSERT_DIVMOD(-1,  1, -1,  0)
TPP_ASSERT_DIVMOD(-1,  2,  0, -1)
TPP_ASSERT_DIVMOD(-1,  3,  0, -1)
TPP_ASSERT_DIVMOD( 0, -3,  0,  0)
TPP_ASSERT_DIVMOD( 0, -2,  0,  0)
TPP_ASSERT_DIVMOD( 0, -1,  0,  0)
TPP_ASSERT_DIVMOD( 0,  1,  0,  0)
TPP_ASSERT_DIVMOD( 0,  2,  0,  0)
TPP_ASSERT_DIVMOD( 0,  3,  0,  0)
TPP_ASSERT_DIVMOD( 1, -3,  0,  1)
TPP_ASSERT_DIVMOD( 1, -2,  0,  1)
TPP_ASSERT_DIVMOD( 1, -1, -1,  0)
TPP_ASSERT_DIVMOD( 1,  1,  1,  0)
TPP_ASSERT_DIVMOD( 1,  2,  0,  1)
TPP_ASSERT_DIVMOD( 1,  3,  0,  1)
TPP_ASSERT_DIVMOD( 2, -3,  0,  2)
TPP_ASSERT_DIVMOD( 2, -2, -1,  0)
TPP_ASSERT_DIVMOD( 2, -1, -2,  0)
TPP_ASSERT_DIVMOD( 2,  1,  2,  0)
TPP_ASSERT_DIVMOD( 2,  2,  1,  0)
TPP_ASSERT_DIVMOD( 2,  3,  0,  2)
TPP_ASSERT_DIVMOD( 3, -3, -1,  0)
TPP_ASSERT_DIVMOD( 3, -2, -1,  1)
TPP_ASSERT_DIVMOD( 3, -1, -3,  0)
TPP_ASSERT_DIVMOD( 3,  1,  3,  0)
TPP_ASSERT_DIVMOD( 3,  2,  1,  1)
TPP_ASSERT_DIVMOD( 3,  3,  1,  0)
#undef TPP_ASSERT_DIVMOD

TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-3 / 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-2 / 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-1 / 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 / 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(1 / 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(2 / 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(3 / 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")

TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-3 % 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-2 % 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(-1 % 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(0 % 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(1 % 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(2 % 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")
TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero")
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(3 % 0))
TPP_ASSERT_WARNING_END("-Wdivide-by-zero")


TPP_ASSERT_EXPANDS("444",  __TPP_EVAL(123 + 321))
TPP_ASSERT_EXPANDS("-198", __TPP_EVAL(123 - 321))
TPP_ASSERT_EXPANDS("-75",  __TPP_EVAL(123 - 321 + 123))
TPP_ASSERT_EXPANDS("321",  __TPP_EVAL(123 + 321 - 123))

TPP_ASSERT_EXPANDS("1",  __TPP_EVAL(1 << 0))
TPP_ASSERT_EXPANDS("2",  __TPP_EVAL(1 << 1))
TPP_ASSERT_EXPANDS("4",  __TPP_EVAL(1 << 2))
TPP_ASSERT_EXPANDS("8",  __TPP_EVAL(1 << 3))
TPP_ASSERT_EXPANDS("1",  __TPP_EVAL(1 >> 0))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(1 >> 1))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(1 >> 2))
TPP_ASSERT_EXPANDS("0",  __TPP_EVAL(1 >> 3))
TPP_ASSERT_EXPANDS("8",  __TPP_EVAL(8 >> 0))
TPP_ASSERT_EXPANDS("4",  __TPP_EVAL(8 >> 1))
TPP_ASSERT_EXPANDS("2",  __TPP_EVAL(8 >> 2))
TPP_ASSERT_EXPANDS("1",  __TPP_EVAL(8 >> 3))

TPP_ASSERT_EXPANDS("0", __TPP_EVAL(123 < 123))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(123 < 321))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(321 < 123))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(321 < 321))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(123 <= 123))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(123 <= 321))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(321 <= 123))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(321 <= 321))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(123 == 123))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(123 == 321))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(321 == 123))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(321 == 321))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(123 != 123))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(123 != 321))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(321 != 123))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(321 != 321))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(123 > 123))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(123 > 321))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(321 > 123))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(321 > 321))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(123 >= 123))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(123 >= 321))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(321 >= 123))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(321 >= 321))

TPP_ASSERT_EXPANDS("0", __TPP_EVAL("abc" < "abc"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("abc" < "def"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("def" < "abc"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("def" < "def"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("abc" <= "abc"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("abc" <= "def"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("def" <= "abc"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("def" <= "def"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("abc" == "abc"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("abc" == "def"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("def" == "abc"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("def" == "def"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("abc" != "abc"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("abc" != "def"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("def" != "abc"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("def" != "def"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("abc" > "abc"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("abc" > "def"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("def" > "abc"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("def" > "def"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("abc" >= "abc"))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL("abc" >= "def"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("def" >= "abc"))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL("def" >= "def"))

TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0x00 & 0x00))
TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0x00 & 0x12))
TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0x00 & 0xff))
TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0x12 & 0x00))
TPP_ASSERT_EXPANDS("18",  __TPP_EVAL(0x12 & 0x12))
TPP_ASSERT_EXPANDS("18",  __TPP_EVAL(0x12 & 0xff))
TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0xff & 0x00))
TPP_ASSERT_EXPANDS("18",  __TPP_EVAL(0xff & 0x12))
TPP_ASSERT_EXPANDS("255", __TPP_EVAL(0xff & 0xff))

TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0x00 ^ 0x00))
TPP_ASSERT_EXPANDS("18",  __TPP_EVAL(0x00 ^ 0x12))
TPP_ASSERT_EXPANDS("255", __TPP_EVAL(0x00 ^ 0xff))
TPP_ASSERT_EXPANDS("18",  __TPP_EVAL(0x12 ^ 0x00))
TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0x12 ^ 0x12))
TPP_ASSERT_EXPANDS("237", __TPP_EVAL(0x12 ^ 0xff))
TPP_ASSERT_EXPANDS("255", __TPP_EVAL(0xff ^ 0x00))
TPP_ASSERT_EXPANDS("237", __TPP_EVAL(0xff ^ 0x12))
TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0xff ^ 0xff))

TPP_ASSERT_EXPANDS("0",   __TPP_EVAL(0x00 | 0x00))
TPP_ASSERT_EXPANDS("18",  __TPP_EVAL(0x00 | 0x12))
TPP_ASSERT_EXPANDS("255", __TPP_EVAL(0x00 | 0xff))
TPP_ASSERT_EXPANDS("18",  __TPP_EVAL(0x12 | 0x00))
TPP_ASSERT_EXPANDS("18",  __TPP_EVAL(0x12 | 0x12))
TPP_ASSERT_EXPANDS("255", __TPP_EVAL(0x12 | 0xff))
TPP_ASSERT_EXPANDS("255", __TPP_EVAL(0xff | 0x00))
TPP_ASSERT_EXPANDS("255", __TPP_EVAL(0xff | 0x12))
TPP_ASSERT_EXPANDS("255", __TPP_EVAL(0xff | 0xff))

TPP_ASSERT_EXPANDS("0", __TPP_EVAL(0 && 0))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(0 && 1))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(1 && 0))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(1 && 1))

#pragma TPP extension(push, "-ftok-hat_hat")
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(0 ^^ 0))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(0 ^^ 1))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(1 ^^ 0))
TPP_ASSERT_EXPANDS("0", __TPP_EVAL(1 ^^ 1))
#pragma TPP extension(pop)

TPP_ASSERT_EXPANDS("0", __TPP_EVAL(0 || 0))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(0 || 1))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(1 || 0))
TPP_ASSERT_EXPANDS("1", __TPP_EVAL(1 || 1))

TPP_ASSERT_EXPANDS("\"no\"",    __TPP_EVAL(0 ? "yes" : 0 ? "maybe" : "no"))
TPP_ASSERT_EXPANDS("\"maybe\"", __TPP_EVAL(0 ? "yes" : 1 ? "maybe" : "no"))
TPP_ASSERT_EXPANDS("\"yes\"",   __TPP_EVAL(1 ? "yes" : 0 ? "maybe" : "no"))
TPP_ASSERT_EXPANDS("\"yes\"",   __TPP_EVAL(1 ? "yes" : 1 ? "maybe" : "no"))

TPP_ASSERT_EXPANDS("\"first\"",   __TPP_EVAL("first" ?: "second"))
TPP_ASSERT_EXPANDS("\"second\"",  __TPP_EVAL("" ?: "second"))

TPP_ASSERT_EXPANDS("10", __TPP_EVAL(10 ?: 20))
TPP_ASSERT_EXPANDS("20", __TPP_EVAL(0  ?: 20))



/* Also test all kinds of expressions when they appear in inactive branches */
#define TEST_INACTIVE(expr)                                             \
	TPP_ASSERT_EXPANDS("\"OK\"", __TPP_EVAL(if (1) "OK" else #!expr))   \
	TPP_ASSERT_EXPANDS("\"OK\"", __TPP_EVAL(if (0) #!expr else "OK"))   \
	TPP_ASSERT_EXPANDS("123999", __TPP_EVAL(123999 ?: #!expr))          \
	TPP_ASSERT_EXPANDS("\"OK\"", __TPP_EVAL(1 ? "OK" : #!expr))         \
	TPP_ASSERT_EXPANDS("\"OK\"", __TPP_EVAL(0 ? #!expr : "OK"))         \
	TPP_ASSERT_EXPANDS("1",      __TPP_EVAL(1 || (#!expr)))             \
	TPP_ASSERT_EXPANDS("0",      __TPP_EVAL(0 && (#!expr)))
TEST_INACTIVE(10)
TEST_INACTIVE(0xa)
TEST_INACTIVE(+10)
TEST_INACTIVE(-10)
TEST_INACTIVE(-1)
TEST_INACTIVE(-0)
TEST_INACTIVE(!10)
TEST_INACTIVE(!0)
TEST_INACTIVE(!!10)
TEST_INACTIVE(!!0)
TEST_INACTIVE(~10)
TEST_INACTIVE(~1)
TEST_INACTIVE(~0)
TEST_INACTIVE(~-0)
TEST_INACTIVE(~-1)
TEST_INACTIVE('a')
TEST_INACTIVE(!"")
TEST_INACTIVE(!"foo")
TEST_INACTIVE(!!"")
TEST_INACTIVE(!!"foo")

TEST_INACTIVE("" ? "yes" : "no")
TEST_INACTIVE("foo" ? "yes" : "no")

TEST_INACTIVE(#"")
TEST_INACTIVE(#"abc")

#assert foo(bar)
TEST_INACTIVE(#foo(bar))
TEST_INACTIVE(#foo(baz))
#pragma TPP extension(push, "-ftrigraphs")
#pragma TPP warning(push, "-Wno-trigraphs")
TEST_INACTIVE(??="")
TEST_INACTIVE(??="abc")
TEST_INACTIVE(??=foo(bar))
TEST_INACTIVE(??=foo(baz))
#unassert foo(bar)
TEST_INACTIVE(??=foo(bar))
TEST_INACTIVE(??=foo(baz))
#pragma TPP warning(pop)
#pragma TPP extension(pop)
TEST_INACTIVE(#foo(bar))
TEST_INACTIVE(#foo(baz))

TEST_INACTIVE(defined MY_MACRO)
TEST_INACTIVE(defined(MY_MACRO))
TEST_INACTIVE((defined MY_MACRO))
TEST_INACTIVE((defined(MY_MACRO)))
#define MY_MACRO
TEST_INACTIVE(defined MY_MACRO)
TEST_INACTIVE(defined(MY_MACRO))
TEST_INACTIVE((defined MY_MACRO))
TEST_INACTIVE((defined(MY_MACRO)))
#undef MY_MACRO

TEST_INACTIVE(if (0) "yes" elif (0) "maybe" else "no")
TEST_INACTIVE(if (0) "yes" elif (1) "maybe" else "no")
TEST_INACTIVE(if (1) "yes" elif (0) "maybe" else "no")
TEST_INACTIVE(if (1) "yes" elif (1) "maybe" else "no")

//TPP_ASSERT_WARNING_BEGIN("-Wundef") /* Not raised in inactive expressions! */
TEST_INACTIVE(NO_SUCH_MACRO)
TEST_INACTIVE(NO_SUCH_MACRO(10, (20), 30))
//TPP_ASSERT_WARNING_END("-Wundef")

TEST_INACTIVE("abc"[-1])
TEST_INACTIVE("abc"[0])
TEST_INACTIVE("abc"[3])
TEST_INACTIVE("abc"[:])
TEST_INACTIVE("abc"[1:])
TEST_INACTIVE("abc"[:1])
TEST_INACTIVE("abc"[-1:])
TEST_INACTIVE("abc"[:-1])
TEST_INACTIVE("abc"[1:2])

TEST_INACTIVE(1 + 2 * 3)
TEST_INACTIVE(1 * 2 + 3)

TEST_INACTIVE(-3 * -3)
TEST_INACTIVE(-3 / -3)
TEST_INACTIVE(-3 % -3)
//TPP_ASSERT_WARNING_BEGIN("-Wdivide-by-zero") /* Not raised in inactive expressions! */
TEST_INACTIVE(-3 / 0)
TEST_INACTIVE(-3 % 0)
//TPP_ASSERT_WARNING_END("-Wdivide-by-zero")

TEST_INACTIVE(123 + 321)
TEST_INACTIVE(123 - 321)
TEST_INACTIVE(123 - 321 + 123)
TEST_INACTIVE(123 + 321 - 123)

TEST_INACTIVE(1 << 0)
TEST_INACTIVE(1 >> 0)
TEST_INACTIVE(123 < 321)
TEST_INACTIVE(123 <= 321)
TEST_INACTIVE(123 == 321)
TEST_INACTIVE(123 != 321)
TEST_INACTIVE(123 > 321)
TEST_INACTIVE(123 >= 321)

TEST_INACTIVE("abc" < "def")
TEST_INACTIVE("abc" <= "def")
TEST_INACTIVE("abc" == "def")
TEST_INACTIVE("abc" != "def")
TEST_INACTIVE("abc" > "def")
TEST_INACTIVE("abc" >= "def")
TEST_INACTIVE(0x12 & 0xff)
TEST_INACTIVE(0x12 ^ 0xff)
TEST_INACTIVE(0x12 | 0xff)

TEST_INACTIVE(0 && 0)
TEST_INACTIVE(0 && 1)
TEST_INACTIVE(1 && 0)
TEST_INACTIVE(1 && 1)
#pragma TPP extension(push, "-ftok-hat_hat")
TEST_INACTIVE(0 ^^ 0)
TEST_INACTIVE(0 ^^ 1)
TEST_INACTIVE(1 ^^ 0)
TEST_INACTIVE(1 ^^ 1)
#pragma TPP extension(pop)
TEST_INACTIVE(0 || 0)
TEST_INACTIVE(0 || 1)
TEST_INACTIVE(1 || 0)
TEST_INACTIVE(1 || 1)
TEST_INACTIVE(0 ? "yes" : 0 ? "maybe" : "no")
TEST_INACTIVE(0 ? "yes" : 1 ? "maybe" : "no")
TEST_INACTIVE(1 ? "yes" : 0 ? "maybe" : "no")
TEST_INACTIVE(1 ? "yes" : 1 ? "maybe" : "no")
TEST_INACTIVE("first" ?: "second")
TEST_INACTIVE("" ?: "second")
TEST_INACTIVE(10 ?: 20)
TEST_INACTIVE(0  ?: 20)
#undef TEST_INACTIVE


