/* Copyright (c) 2017-2026 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2017-2026 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
/*!depends config.h, defs.h*/
#ifndef GUARD_TPP_TOKEN_ALIASES_H
#define GUARD_TPP_TOKEN_ALIASES_H 1

#include "api.h"

#include "config.h"

/*[[[tpp-begin]]]*/
TPP_DECL_BEGIN

/*[[[deemon
import * from deemon;

class TokenId {
	this = default;
	@@ID: "TPP_TOK_EQUAL_EQUAL_EQUAL"
	public member id: string;
	@@Condition: "TPP_HAVE_TOK_EQUAL_EQUAL_EQUAL"
	public member condition: string;
}

local tokens: {TokenId...} = [];
local conditionStack = [];
local inside = false;
local insideMultiChar = false;
for (local line: File.open("token.h").read().decode("utf-8").splitlines(false)) {
	if (!inside) {
		if ("TPP_TOK_EOF" in line &&
		    "\\0" in line) {
			inside = true;
		} else {
			continue;
		}
	}
	if (("TPP_TOK_MULTI" "CHAR_BEGIN") in line) {
		insideMultiChar = true;
		continue;
	}
	if ("TPP_TOK_MULTI" "CHAR_END" in line)
		break;
	if (line.startswith("#if")) {
		conditionStack.append(line[3:].strip());
	} else if (line.startswith("#elif")) {
		local last = conditionStack.popback();
		conditionStack.append(f"!{last} && {line[5:].strip()}");
	} else if (line.startswith("#else")) {
		local last = conditionStack.popback();
		conditionStack.append(f"!{last}");
	} else if (line.startswith("#endif")) {
		conditionStack.popback();
	} else {
		local tokenName;
		try {
			tokenName, none = line.rescanf(r"\s*(\w+)\s*=\s('[^']+'),")...;
		} catch (...) {
			if (!insideMultiChar)
				continue;
			try {
				tokenName = line.rescanf(r"\s*(\w+)\s*,\s*" r"/")...;
			} catch (...) {
				continue;
			}
		}
		if (tokenName.startswith("_"))
			continue;
		local tokenId = TokenId(
			id: tokenName,
			condition: " && ".join(conditionStack) ?: "1");
		tokens.append(tokenId);
	}
}

local tokensByCondition: {string: {TokenId...}} = Dict();
for (local token: tokens)
	tokensByCondition.setdefault(token.condition, []).append(token);
print("#if TPP_HAVE_API_TOKEN_NAMES_IN_GLOBAL_NAMESPACE");
for (local condition, conditionalTokens: tokensByCondition) {
	if (condition != "1")
		print("#if ", condition);
	for (local token: conditionalTokens)
		print("#define ", token.id.lsstrip("TPP_"), " ", token.id);
	if (condition != "1")
		print("#endif /" "* ", condition, " *" "/");
}

function getProperty(name: string) {
	static local DEFS_H = File.open("defs.h", "rb").read();
	local start = DEFS_H.reindex(name + r"\s*=\s*\{").last;
	return exec("{" + DEFS_H[start:DEFS_H.indexmatch("{", "}", start)] + "}");
}
local BUILTIN_KEYWORDS = getProperty("BUILTIN_KEYWORDS");
for (local kwd, cond: BUILTIN_KEYWORDS) {
	print("#if ", cond);
	print("#define KWD_", kwd, " TPP_KWD_", kwd);
	print("#endif /" "* ", cond, " *" "/");
}
print("#endif /" "* TPP_HAVE_API_TOKEN_NAMES_IN_GLOBAL_NAMESPACE *" "/");
]]]*/
#if TPP_HAVE_API_TOKEN_NAMES_IN_GLOBAL_NAMESPACE
#define TOK_EOF TPP_TOK_EOF
#define TOK_LF TPP_TOK_LF
#define TOK_SPACE TPP_TOK_SPACE
#define TOK_EXCLAIM TPP_TOK_EXCLAIM
#define TOK_POUND TPP_TOK_POUND
#define TOK_PERCENT TPP_TOK_PERCENT
#define TOK_AMP TPP_TOK_AMP
#define TOK_LPAREN TPP_TOK_LPAREN
#define TOK_RPAREN TPP_TOK_RPAREN
#define TOK_STAR TPP_TOK_STAR
#define TOK_PLUS TPP_TOK_PLUS
#define TOK_COMMA TPP_TOK_COMMA
#define TOK_MINUS TPP_TOK_MINUS
#define TOK_DOT TPP_TOK_DOT
#define TOK_SLASH TPP_TOK_SLASH
#define TOK_COLON TPP_TOK_COLON
#define TOK_SEMICOLON TPP_TOK_SEMICOLON
#define TOK_LANGLE TPP_TOK_LANGLE
#define TOK_EQUAL TPP_TOK_EQUAL
#define TOK_RANGLE TPP_TOK_RANGLE
#define TOK_QMARK TPP_TOK_QMARK
#define TOK_AT TPP_TOK_AT
#define TOK_LBRACKET TPP_TOK_LBRACKET
#define TOK_BACKSLASH TPP_TOK_BACKSLASH
#define TOK_RBRACKET TPP_TOK_RBRACKET
#define TOK_HAT TPP_TOK_HAT
#define TOK_BACKTICK TPP_TOK_BACKTICK
#define TOK_LBRACE TPP_TOK_LBRACE
#define TOK_PIPE TPP_TOK_PIPE
#define TOK_RBRACE TPP_TOK_RBRACE
#define TOK_TILDE TPP_TOK_TILDE
#if TPP_HAVE_TOK_DOLLAR
#define TOK_DOLLAR TPP_TOK_DOLLAR
#endif /* TPP_HAVE_TOK_DOLLAR */
#if !TPP_HAVE_TOK_C_INT && !TPP_HAVE_TOK_C_FLOAT
#define TOK_0 TPP_TOK_0
#define TOK_1 TPP_TOK_1
#define TOK_2 TPP_TOK_2
#define TOK_3 TPP_TOK_3
#define TOK_4 TPP_TOK_4
#define TOK_5 TPP_TOK_5
#define TOK_6 TPP_TOK_6
#define TOK_7 TPP_TOK_7
#define TOK_8 TPP_TOK_8
#define TOK_9 TPP_TOK_9
#endif /* !TPP_HAVE_TOK_C_INT && !TPP_HAVE_TOK_C_FLOAT */
#if TPP_HAVE_UNICODE
#define TOK_UNICHAR TPP_TOK_UNICHAR
#endif /* TPP_HAVE_UNICODE */
#if TPP_HAVE_TOK_INT && TPP_HAVE_TOK_C_INT
#define TOK_C_INT TPP_TOK_C_INT
#endif /* TPP_HAVE_TOK_INT && TPP_HAVE_TOK_C_INT */
#if TPP_HAVE_TOK_INT && TPP_HAVE_TOK_PASCAL_HEX
#define TOK_PASCAL_HEX TPP_TOK_PASCAL_HEX
#endif /* TPP_HAVE_TOK_INT && TPP_HAVE_TOK_PASCAL_HEX */
#if TPP_HAVE_TOK_FLOAT && TPP_HAVE_TOK_C_FLOAT
#define TOK_C_FLOAT TPP_TOK_C_FLOAT
#endif /* TPP_HAVE_TOK_FLOAT && TPP_HAVE_TOK_C_FLOAT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_C_COMMENT
#define TOK_C_COMMENT TPP_TOK_C_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_C_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_PASCAL_COMMENT
#define TOK_PASCAL_COMMENT TPP_TOK_PASCAL_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_PASCAL_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_PASCAL_BRACE_COMMENT
#define TOK_PASCAL_BRACE_COMMENT TPP_TOK_PASCAL_BRACE_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_PASCAL_BRACE_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_HTML_COMMENT
#define TOK_HTML_COMMENT TPP_TOK_HTML_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_HTML_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_CXX_COMMENT
#define TOK_CXX_COMMENT TPP_TOK_CXX_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_CXX_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SQL_COMMENT
#define TOK_SQL_COMMENT TPP_TOK_SQL_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SQL_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_AT_AT_COMMENT
#define TOK_AT_AT_COMMENT TPP_TOK_AT_AT_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_AT_AT_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SHELL_COMMENT
#define TOK_SHELL_COMMENT TPP_TOK_SHELL_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SHELL_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SLASH_COMMENT
#define TOK_SLASH_COMMENT TPP_TOK_SLASH_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SLASH_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_AT_COMMENT
#define TOK_AT_COMMENT TPP_TOK_AT_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_AT_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SOL_SHELL_COMMENT
#define TOK_SOL_SHELL_COMMENT TPP_TOK_SOL_SHELL_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SOL_SHELL_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SOL_SLASH_COMMENT
#define TOK_SOL_SLASH_COMMENT TPP_TOK_SOL_SLASH_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SOL_SLASH_COMMENT */
#if TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SOL_AT_COMMENT
#define TOK_SOL_AT_COMMENT TPP_TOK_SOL_AT_COMMENT
#endif /* TPP_HAVE_TOK_COMMENTLIKE && TPP_HAVE_TOK_SOL_AT_COMMENT */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_C_STRING
#define TOK_C_STRING TPP_TOK_C_STRING
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_C_STRING */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL
#define TOK_CXX_RAW_STRING_LITERAL TPP_TOK_CXX_RAW_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_WIDE_STRING_LITERAL
#define TOK_CXX_WIDE_STRING_LITERAL TPP_TOK_CXX_WIDE_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_WIDE_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_WIDE_STRING_LITERAL && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL
#define TOK_CXX_RAW_WIDE_STRING_LITERAL TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_WIDE_STRING_LITERAL && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF8_STRING_LITERAL
#define TOK_CXX_UTF8_STRING_LITERAL TPP_TOK_CXX_UTF8_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF8_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF8_STRING_LITERAL && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL
#define TOK_CXX_RAW_UTF8_STRING_LITERAL TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF8_STRING_LITERAL && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF16_STRING_LITERAL
#define TOK_CXX_UTF16_STRING_LITERAL TPP_TOK_CXX_UTF16_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF16_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF16_STRING_LITERAL && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL
#define TOK_CXX_RAW_UTF16_STRING_LITERAL TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF16_STRING_LITERAL && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF32_STRING_LITERAL
#define TOK_CXX_UTF32_STRING_LITERAL TPP_TOK_CXX_UTF32_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF32_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF32_STRING_LITERAL && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL
#define TOK_CXX_RAW_UTF32_STRING_LITERAL TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF32_STRING_LITERAL && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_RAW_STRING_LITERAL
#define TOK_RAW_STRING_LITERAL TPP_TOK_RAW_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_RAW_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_BLOCK_STRING_LITERAL
#define TOK_BLOCK_STRING_LITERAL TPP_TOK_BLOCK_STRING_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_BLOCK_STRING_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_C_CHAR
#define TOK_C_CHAR TPP_TOK_C_CHAR
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_C_CHAR */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL
#define TOK_CXX_RAW_CHAR_LITERAL TPP_TOK_CXX_RAW_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_WIDE_CHAR_LITERAL
#define TOK_CXX_WIDE_CHAR_LITERAL TPP_TOK_CXX_WIDE_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_WIDE_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_WIDE_CHAR_LITERAL && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL
#define TOK_CXX_RAW_WIDE_CHAR_LITERAL TPP_TOK_CXX_RAW_WIDE_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_WIDE_CHAR_LITERAL && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF8_CHAR_LITERAL
#define TOK_CXX_UTF8_CHAR_LITERAL TPP_TOK_CXX_UTF8_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF8_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF8_CHAR_LITERAL && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL
#define TOK_CXX_RAW_UTF8_CHAR_LITERAL TPP_TOK_CXX_RAW_UTF8_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF8_CHAR_LITERAL && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF16_CHAR_LITERAL
#define TOK_CXX_UTF16_CHAR_LITERAL TPP_TOK_CXX_UTF16_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF16_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF16_CHAR_LITERAL && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL
#define TOK_CXX_RAW_UTF16_CHAR_LITERAL TPP_TOK_CXX_RAW_UTF16_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF16_CHAR_LITERAL && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF32_CHAR_LITERAL
#define TOK_CXX_UTF32_CHAR_LITERAL TPP_TOK_CXX_UTF32_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF32_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF32_CHAR_LITERAL && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL
#define TOK_CXX_RAW_UTF32_CHAR_LITERAL TPP_TOK_CXX_RAW_UTF32_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_CXX_UTF32_CHAR_LITERAL && TPP_HAVE_TOK_CXX_RAW_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_RAW_CHAR_LITERAL
#define TOK_RAW_CHAR_LITERAL TPP_TOK_RAW_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_RAW_CHAR_LITERAL */
#if TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_BLOCK_CHAR_LITERAL
#define TOK_BLOCK_CHAR_LITERAL TPP_TOK_BLOCK_CHAR_LITERAL
#endif /* TPP_HAVE_TOK_STRINGLIKE && TPP_HAVE_TOK_BLOCK_CHAR_LITERAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_EXCLAIM && TPP_HAVE_TOK_EXCLAIM_EXCLAIM
#define TOK_EXCLAIM_EXCLAIM TPP_TOK_EXCLAIM_EXCLAIM
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EXCLAIM && TPP_HAVE_TOK_EXCLAIM_EXCLAIM */
#if TPP_HAVE_TOK_MC_STARTSWITH_EXCLAIM && TPP_HAVE_TOK_EXCLAIM_EQUAL
#define TOK_EXCLAIM_EQUAL TPP_TOK_EXCLAIM_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EXCLAIM && TPP_HAVE_TOK_EXCLAIM_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_EXCLAIM && TPP_HAVE_TOK_EXCLAIM_EQUAL_EQUAL
#define TOK_EXCLAIM_EQUAL_EQUAL TPP_TOK_EXCLAIM_EQUAL_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EXCLAIM && TPP_HAVE_TOK_EXCLAIM_EQUAL_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_POUND && TPP_HAVE_TOK_POUND_POUND
#define TOK_POUND_POUND TPP_TOK_POUND_POUND
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_POUND && TPP_HAVE_TOK_POUND_POUND */
#if TPP_HAVE_TOK_MC_STARTSWITH_PERCENT && TPP_HAVE_TOK_PERCENT_PERCENT
#define TOK_PERCENT_PERCENT TPP_TOK_PERCENT_PERCENT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_PERCENT && TPP_HAVE_TOK_PERCENT_PERCENT */
#if TPP_HAVE_TOK_MC_STARTSWITH_PERCENT && TPP_HAVE_TOK_PERCENT_PERCENT_EQUAL
#define TOK_PERCENT_PERCENT_EQUAL TPP_TOK_PERCENT_PERCENT_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_PERCENT && TPP_HAVE_TOK_PERCENT_PERCENT_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_PERCENT && TPP_HAVE_TOK_PERCENT_EQUAL
#define TOK_PERCENT_EQUAL TPP_TOK_PERCENT_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_PERCENT && TPP_HAVE_TOK_PERCENT_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_AMP && TPP_HAVE_TOK_AMP_AMP
#define TOK_AMP_AMP TPP_TOK_AMP_AMP
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_AMP && TPP_HAVE_TOK_AMP_AMP */
#if TPP_HAVE_TOK_MC_STARTSWITH_AMP && TPP_HAVE_TOK_AMP_EQUAL
#define TOK_AMP_EQUAL TPP_TOK_AMP_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_AMP && TPP_HAVE_TOK_AMP_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_STAR
#define TOK_STAR_STAR TPP_TOK_STAR_STAR
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_STAR */
#if TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_STAR_EQUAL
#define TOK_STAR_STAR_EQUAL TPP_TOK_STAR_STAR_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_STAR_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_DOT
#define TOK_STAR_DOT TPP_TOK_STAR_DOT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_DOT */
#if TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_LANGLE_MINUS
#define TOK_STAR_LANGLE_MINUS TPP_TOK_STAR_LANGLE_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_LANGLE_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_EQUAL
#define TOK_STAR_EQUAL TPP_TOK_STAR_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_STAR && TPP_HAVE_TOK_STAR_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_PLUS && TPP_HAVE_TOK_PLUS_PLUS
#define TOK_PLUS_PLUS TPP_TOK_PLUS_PLUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_PLUS && TPP_HAVE_TOK_PLUS_PLUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_PLUS && TPP_HAVE_TOK_PLUS_EQUAL
#define TOK_PLUS_EQUAL TPP_TOK_PLUS_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_PLUS && TPP_HAVE_TOK_PLUS_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_MINUS
#define TOK_MINUS_MINUS TPP_TOK_MINUS_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_LANGLE
#define TOK_MINUS_LANGLE TPP_TOK_MINUS_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_LANGLE_LANGLE
#define TOK_MINUS_LANGLE_LANGLE TPP_TOK_MINUS_LANGLE_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_LANGLE_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_LANGLE_LANGLE_LANGLE
#define TOK_MINUS_LANGLE_LANGLE_LANGLE TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_EQUAL
#define TOK_MINUS_EQUAL TPP_TOK_MINUS_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_RANGLE
#define TOK_MINUS_RANGLE TPP_TOK_MINUS_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_RANGLE_STAR
#define TOK_MINUS_RANGLE_STAR TPP_TOK_MINUS_RANGLE_STAR
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_RANGLE_STAR */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_RANGLE_RANGLE
#define TOK_MINUS_RANGLE_RANGLE TPP_TOK_MINUS_RANGLE_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_RANGLE_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_RANGLE_RANGLE_RANGLE
#define TOK_MINUS_RANGLE_RANGLE_RANGLE TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_MINUS && TPP_HAVE_TOK_MINUS_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_DOT && TPP_HAVE_TOK_DOT_STAR
#define TOK_DOT_STAR TPP_TOK_DOT_STAR
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_DOT && TPP_HAVE_TOK_DOT_STAR */
#if TPP_HAVE_TOK_MC_STARTSWITH_DOT && TPP_HAVE_TOK_DOT_DOT
#define TOK_DOT_DOT TPP_TOK_DOT_DOT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_DOT && TPP_HAVE_TOK_DOT_DOT */
#if TPP_HAVE_TOK_MC_STARTSWITH_DOT && TPP_HAVE_TOK_DOT_DOT_DOT
#define TOK_DOT_DOT_DOT TPP_TOK_DOT_DOT_DOT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_DOT && TPP_HAVE_TOK_DOT_DOT_DOT */
#if TPP_HAVE_TOK_MC_STARTSWITH_SLASH && TPP_HAVE_TOK_SLASH_SLASH
#define TOK_SLASH_SLASH TPP_TOK_SLASH_SLASH
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_SLASH && TPP_HAVE_TOK_SLASH_SLASH */
#if TPP_HAVE_TOK_MC_STARTSWITH_SLASH && TPP_HAVE_TOK_SLASH_SLASH_EQUAL
#define TOK_SLASH_SLASH_EQUAL TPP_TOK_SLASH_SLASH_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_SLASH && TPP_HAVE_TOK_SLASH_SLASH_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_SLASH && TPP_HAVE_TOK_SLASH_EQUAL
#define TOK_SLASH_EQUAL TPP_TOK_SLASH_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_SLASH && TPP_HAVE_TOK_SLASH_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_COLON && TPP_HAVE_TOK_COLON_COLON
#define TOK_COLON_COLON TPP_TOK_COLON_COLON
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_COLON && TPP_HAVE_TOK_COLON_COLON */
#if TPP_HAVE_TOK_MC_STARTSWITH_COLON && TPP_HAVE_TOK_COLON_EQUAL
#define TOK_COLON_EQUAL TPP_TOK_COLON_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_COLON && TPP_HAVE_TOK_COLON_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_MINUS
#define TOK_LANGLE_MINUS TPP_TOK_LANGLE_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_MINUS_LANGLE
#define TOK_LANGLE_MINUS_LANGLE TPP_TOK_LANGLE_MINUS_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_MINUS_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_MINUS_RANGLE
#define TOK_LANGLE_MINUS_RANGLE TPP_TOK_LANGLE_MINUS_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_MINUS_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE
#define TOK_LANGLE_LANGLE TPP_TOK_LANGLE_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_MINUS
#define TOK_LANGLE_LANGLE_MINUS TPP_TOK_LANGLE_LANGLE_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_LANGLE
#define TOK_LANGLE_LANGLE_LANGLE TPP_TOK_LANGLE_LANGLE_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_LANGLE_MINUS
#define TOK_LANGLE_LANGLE_LANGLE_MINUS TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_LANGLE_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_LANGLE_EQUAL
#define TOK_LANGLE_LANGLE_LANGLE_EQUAL TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_EQUAL
#define TOK_LANGLE_LANGLE_EQUAL TPP_TOK_LANGLE_LANGLE_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_EQUAL
#define TOK_LANGLE_EQUAL TPP_TOK_LANGLE_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_EQUAL_LANGLE
#define TOK_LANGLE_EQUAL_LANGLE TPP_TOK_LANGLE_EQUAL_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_EQUAL_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_EQUAL_RANGLE
#define TOK_LANGLE_EQUAL_RANGLE TPP_TOK_LANGLE_EQUAL_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_EQUAL_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_RANGLE
#define TOK_LANGLE_RANGLE TPP_TOK_LANGLE_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_LANGLE && TPP_HAVE_TOK_LANGLE_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_EXCLAIM
#define TOK_EQUAL_EXCLAIM TPP_TOK_EQUAL_EXCLAIM
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_EXCLAIM */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_PERCENT
#define TOK_EQUAL_PERCENT TPP_TOK_EQUAL_PERCENT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_PERCENT */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_PERCENT_PERCENT
#define TOK_EQUAL_PERCENT_PERCENT TPP_TOK_EQUAL_PERCENT_PERCENT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_PERCENT_PERCENT */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_AMP
#define TOK_EQUAL_AMP TPP_TOK_EQUAL_AMP
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_AMP */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_STAR
#define TOK_EQUAL_STAR TPP_TOK_EQUAL_STAR
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_STAR */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_STAR_STAR
#define TOK_EQUAL_STAR_STAR TPP_TOK_EQUAL_STAR_STAR
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_STAR_STAR */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_PLUS
#define TOK_EQUAL_PLUS TPP_TOK_EQUAL_PLUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_PLUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_MINUS
#define TOK_EQUAL_MINUS TPP_TOK_EQUAL_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_SLASH
#define TOK_EQUAL_SLASH TPP_TOK_EQUAL_SLASH
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_SLASH */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_SLASH_SLASH
#define TOK_EQUAL_SLASH_SLASH TPP_TOK_EQUAL_SLASH_SLASH
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_SLASH_SLASH */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_COLON
#define TOK_EQUAL_COLON TPP_TOK_EQUAL_COLON
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_COLON */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_LANGLE
#define TOK_EQUAL_LANGLE TPP_TOK_EQUAL_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_LANGLE_LANGLE
#define TOK_EQUAL_LANGLE_LANGLE TPP_TOK_EQUAL_LANGLE_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_LANGLE_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_LANGLE_LANGLE_LANGLE
#define TOK_EQUAL_LANGLE_LANGLE_LANGLE TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_EQUAL
#define TOK_EQUAL_EQUAL TPP_TOK_EQUAL_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_EQUAL_EXCLAIM
#define TOK_EQUAL_EQUAL_EXCLAIM TPP_TOK_EQUAL_EQUAL_EXCLAIM
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_EQUAL_EXCLAIM */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_EQUAL_EQUAL
#define TOK_EQUAL_EQUAL_EQUAL TPP_TOK_EQUAL_EQUAL_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_EQUAL_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_RANGLE
#define TOK_EQUAL_RANGLE TPP_TOK_EQUAL_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_RANGLE_RANGLE
#define TOK_EQUAL_RANGLE_RANGLE TPP_TOK_EQUAL_RANGLE_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_RANGLE_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_RANGLE_RANGLE_RANGLE
#define TOK_EQUAL_RANGLE_RANGLE_RANGLE TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_QMARK
#define TOK_EQUAL_QMARK TPP_TOK_EQUAL_QMARK
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_QMARK */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_AT
#define TOK_EQUAL_AT TPP_TOK_EQUAL_AT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_AT */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_AT_AT
#define TOK_EQUAL_AT_AT TPP_TOK_EQUAL_AT_AT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_AT_AT */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_HAT
#define TOK_EQUAL_HAT TPP_TOK_EQUAL_HAT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_HAT */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_PIPE
#define TOK_EQUAL_PIPE TPP_TOK_EQUAL_PIPE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_PIPE */
#if TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_TILDE
#define TOK_EQUAL_TILDE TPP_TOK_EQUAL_TILDE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_EQUAL && TPP_HAVE_TOK_EQUAL_TILDE */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_MINUS
#define TOK_RANGLE_MINUS TPP_TOK_RANGLE_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_MINUS_LANGLE
#define TOK_RANGLE_MINUS_LANGLE TPP_TOK_RANGLE_MINUS_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_MINUS_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_MINUS_RANGLE
#define TOK_RANGLE_MINUS_RANGLE TPP_TOK_RANGLE_MINUS_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_MINUS_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_LANGLE
#define TOK_RANGLE_LANGLE TPP_TOK_RANGLE_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_EQUAL
#define TOK_RANGLE_EQUAL TPP_TOK_RANGLE_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_EQUAL_LANGLE
#define TOK_RANGLE_EQUAL_LANGLE TPP_TOK_RANGLE_EQUAL_LANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_EQUAL_LANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_EQUAL_RANGLE
#define TOK_RANGLE_EQUAL_RANGLE TPP_TOK_RANGLE_EQUAL_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_EQUAL_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE
#define TOK_RANGLE_RANGLE TPP_TOK_RANGLE_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_MINUS
#define TOK_RANGLE_RANGLE_MINUS TPP_TOK_RANGLE_RANGLE_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_EQUAL
#define TOK_RANGLE_RANGLE_EQUAL TPP_TOK_RANGLE_RANGLE_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_RANGLE
#define TOK_RANGLE_RANGLE_RANGLE TPP_TOK_RANGLE_RANGLE_RANGLE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_RANGLE_MINUS
#define TOK_RANGLE_RANGLE_RANGLE_MINUS TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_RANGLE_MINUS */
#if TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_RANGLE_EQUAL
#define TOK_RANGLE_RANGLE_RANGLE_EQUAL TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_RANGLE && TPP_HAVE_TOK_RANGLE_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_QMARK && TPP_HAVE_TOK_QMARK_EQUAL
#define TOK_QMARK_EQUAL TPP_TOK_QMARK_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_QMARK && TPP_HAVE_TOK_QMARK_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_QMARK && TPP_HAVE_TOK_QMARK_QMARK
#define TOK_QMARK_QMARK TPP_TOK_QMARK_QMARK
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_QMARK && TPP_HAVE_TOK_QMARK_QMARK */
#if TPP_HAVE_TOK_MC_STARTSWITH_AT && TPP_HAVE_TOK_AT_EQUAL
#define TOK_AT_EQUAL TPP_TOK_AT_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_AT && TPP_HAVE_TOK_AT_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_AT && TPP_HAVE_TOK_AT_AT
#define TOK_AT_AT TPP_TOK_AT_AT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_AT && TPP_HAVE_TOK_AT_AT */
#if TPP_HAVE_TOK_MC_STARTSWITH_AT && TPP_HAVE_TOK_AT_AT_EQUAL
#define TOK_AT_AT_EQUAL TPP_TOK_AT_AT_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_AT && TPP_HAVE_TOK_AT_AT_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_HAT && TPP_HAVE_TOK_HAT_EQUAL
#define TOK_HAT_EQUAL TPP_TOK_HAT_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_HAT && TPP_HAVE_TOK_HAT_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_HAT && TPP_HAVE_TOK_HAT_HAT
#define TOK_HAT_HAT TPP_TOK_HAT_HAT
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_HAT && TPP_HAVE_TOK_HAT_HAT */
#if TPP_HAVE_TOK_MC_STARTSWITH_PIPE && TPP_HAVE_TOK_PIPE_EQUAL
#define TOK_PIPE_EQUAL TPP_TOK_PIPE_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_PIPE && TPP_HAVE_TOK_PIPE_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_PIPE && TPP_HAVE_TOK_PIPE_PIPE
#define TOK_PIPE_PIPE TPP_TOK_PIPE_PIPE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_PIPE && TPP_HAVE_TOK_PIPE_PIPE */
#if TPP_HAVE_TOK_MC_STARTSWITH_TILDE && TPP_HAVE_TOK_TILDE_EQUAL
#define TOK_TILDE_EQUAL TPP_TOK_TILDE_EQUAL
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_TILDE && TPP_HAVE_TOK_TILDE_EQUAL */
#if TPP_HAVE_TOK_MC_STARTSWITH_TILDE && TPP_HAVE_TOK_TILDE_TILDE
#define TOK_TILDE_TILDE TPP_TOK_TILDE_TILDE
#endif /* TPP_HAVE_TOK_MC_STARTSWITH_TILDE && TPP_HAVE_TOK_TILDE_TILDE */
#if TPP_HAVE_CPP_LINE
#define KWD_line TPP_KWD_line
#endif /* TPP_HAVE_CPP_LINE */
#if TPP_HAVE_CPP_INCLUDE
#define KWD_include TPP_KWD_include
#endif /* TPP_HAVE_CPP_INCLUDE */
#if TPP_HAVE_CPP_INCLUDE_NEXT
#define KWD_include_next TPP_KWD_include_next
#endif /* TPP_HAVE_CPP_INCLUDE_NEXT */
#if TPP_HAVE_CPP_IMPORT
#define KWD_import TPP_KWD_import
#endif /* TPP_HAVE_CPP_IMPORT */
#if TPP_HAVE_CPP_IF_ELSE_ENDIF || TPP_HAVE_BUILTIN_EXPR_IF_ELSE_IN_EXPRESSIONS
#define KWD_if TPP_KWD_if
#endif /* TPP_HAVE_CPP_IF_ELSE_ENDIF || TPP_HAVE_BUILTIN_EXPR_IF_ELSE_IN_EXPRESSIONS */
#if TPP_HAVE_CPP_IF_ELSE_ENDIF
#define KWD_ifdef TPP_KWD_ifdef
#endif /* TPP_HAVE_CPP_IF_ELSE_ENDIF */
#if TPP_HAVE_CPP_IF_ELSE_ENDIF
#define KWD_ifndef TPP_KWD_ifndef
#endif /* TPP_HAVE_CPP_IF_ELSE_ENDIF */
#if TPP_HAVE_CPP_IF_ELSE_ENDIF || TPP_HAVE_BUILTIN_EXPR_IF_ELSE_IN_EXPRESSIONS
#define KWD_elif TPP_KWD_elif
#endif /* TPP_HAVE_CPP_IF_ELSE_ENDIF || TPP_HAVE_BUILTIN_EXPR_IF_ELSE_IN_EXPRESSIONS */
#if TPP_HAVE_CPP_IF_ELSE_ENDIF
#define KWD_elifdef TPP_KWD_elifdef
#endif /* TPP_HAVE_CPP_IF_ELSE_ENDIF */
#if TPP_HAVE_CPP_IF_ELSE_ENDIF
#define KWD_elifndef TPP_KWD_elifndef
#endif /* TPP_HAVE_CPP_IF_ELSE_ENDIF */
#if TPP_HAVE_CPP_IF_ELSE_ENDIF || TPP_HAVE_BUILTIN_EXPR_IF_ELSE_IN_EXPRESSIONS
#define KWD_else TPP_KWD_else
#endif /* TPP_HAVE_CPP_IF_ELSE_ENDIF || TPP_HAVE_BUILTIN_EXPR_IF_ELSE_IN_EXPRESSIONS */
#if TPP_HAVE_CPP_IF_ELSE_ENDIF
#define KWD_endif TPP_KWD_endif
#endif /* TPP_HAVE_CPP_IF_ELSE_ENDIF */
#if TPP_HAVE_CPP_DEFINE
#define KWD_define TPP_KWD_define
#endif /* TPP_HAVE_CPP_DEFINE */
#if TPP_HAVE_CPP_DEFINE || TPP_HAVE_PRAGMA_PUSH_MACRO
#define KWD_undef TPP_KWD_undef
#endif /* TPP_HAVE_CPP_DEFINE || TPP_HAVE_PRAGMA_PUSH_MACRO */
#if TPP_HAVE_CPP_EMBED
#define KWD_embed TPP_KWD_embed
#endif /* TPP_HAVE_CPP_EMBED */
#if TPP_HAVE_CPP_ASSERT
#define KWD_assert TPP_KWD_assert
#endif /* TPP_HAVE_CPP_ASSERT */
#if TPP_HAVE_CPP_ASSERT
#define KWD_unassert TPP_KWD_unassert
#endif /* TPP_HAVE_CPP_ASSERT */
#if TPP_HAVE_CPP_ERROR || TPP_HAVE_PRAGMA_ERROR || TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC || TPP_HAVE_PRAGMA_GCC_ERROR || TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING
#define KWD_error TPP_KWD_error
#endif /* TPP_HAVE_CPP_ERROR || TPP_HAVE_PRAGMA_ERROR || TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC || TPP_HAVE_PRAGMA_GCC_ERROR || TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING */
#if TPP_HAVE_CPP_WARNING || TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING || TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC || TPP_HAVE_PRAGMA_GCC_WARNING
#define KWD_warning TPP_KWD_warning
#endif /* TPP_HAVE_CPP_WARNING || TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING || TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC || TPP_HAVE_PRAGMA_GCC_WARNING */
#if TPP_HAVE_CPP_IDENT_SCCS
#define KWD_ident TPP_KWD_ident
#endif /* TPP_HAVE_CPP_IDENT_SCCS */
#if TPP_HAVE_CPP_IDENT_SCCS
#define KWD_sccs TPP_KWD_sccs
#endif /* TPP_HAVE_CPP_IDENT_SCCS */
#if TPP_HAVE_CPP_PRAGMA
#define KWD_pragma TPP_KWD_pragma
#endif /* TPP_HAVE_CPP_PRAGMA */
#if TPP_HAVE_MACRO__Pragma
#define KWD__Pragma TPP_KWD__Pragma
#endif /* TPP_HAVE_MACRO__Pragma */
#if TPP_HAVE_MACRO___pragma
#define KWD___pragma TPP_KWD___pragma
#endif /* TPP_HAVE_MACRO___pragma */
#if TPP_HAVE_CLANG_MACRO___has_attribute
#define KWD___has_attribute TPP_KWD___has_attribute
#endif /* TPP_HAVE_CLANG_MACRO___has_attribute */
#if TPP_HAVE_CLANG_MACRO___has_builtin
#define KWD___has_builtin TPP_KWD___has_builtin
#endif /* TPP_HAVE_CLANG_MACRO___has_builtin */
#if TPP_HAVE_CLANG_MACRO___has_cpp_attribute
#define KWD___has_cpp_attribute TPP_KWD___has_cpp_attribute
#endif /* TPP_HAVE_CLANG_MACRO___has_cpp_attribute */
#if TPP_HAVE_CLANG_MACRO___has_declspec_attribute
#define KWD___has_declspec_attribute TPP_KWD___has_declspec_attribute
#endif /* TPP_HAVE_CLANG_MACRO___has_declspec_attribute */
#if TPP_HAVE_CLANG_MACRO___has_extension || TPP_HAVE_MACRO___has_extension
#define KWD___has_extension TPP_KWD___has_extension
#endif /* TPP_HAVE_CLANG_MACRO___has_extension || TPP_HAVE_MACRO___has_extension */
#if TPP_HAVE_CLANG_MACRO___has_feature
#define KWD___has_feature TPP_KWD___has_feature
#endif /* TPP_HAVE_CLANG_MACRO___has_feature */
#if TPP_HAVE_CLANG_MACRO___has_c_attribute
#define KWD___has_c_attribute TPP_KWD___has_c_attribute
#endif /* TPP_HAVE_CLANG_MACRO___has_c_attribute */
#if TPP_HAVE_MACRO___is_identifier
#define KWD___is_identifier TPP_KWD___is_identifier
#endif /* TPP_HAVE_MACRO___is_identifier */
#if TPP_HAVE_MACRO___is_deprecated
#define KWD___is_deprecated TPP_KWD___is_deprecated
#endif /* TPP_HAVE_MACRO___is_deprecated */
#if TPP_HAVE_MACRO___is_poisoned
#define KWD___is_poisoned TPP_KWD___is_poisoned
#endif /* TPP_HAVE_MACRO___is_poisoned */
#if TPP_HAVE_MACRO___has_known_extension
#define KWD___has_known_extension TPP_KWD___has_known_extension
#endif /* TPP_HAVE_MACRO___has_known_extension */
#if TPP_HAVE_MACRO___has_warning
#define KWD___has_warning TPP_KWD___has_warning
#endif /* TPP_HAVE_MACRO___has_warning */
#if TPP_HAVE_MACRO___has_known_warning
#define KWD___has_known_warning TPP_KWD___has_known_warning
#endif /* TPP_HAVE_MACRO___has_known_warning */
#if TPP_HAVE_MACRO___has_include
#define KWD___has_include TPP_KWD___has_include
#endif /* TPP_HAVE_MACRO___has_include */
#if TPP_HAVE_MACRO___has_include_next
#define KWD___has_include_next TPP_KWD___has_include_next
#endif /* TPP_HAVE_MACRO___has_include_next */
#if TPP_HAVE_MACRO___has_embed
#define KWD___has_embed TPP_KWD___has_embed
#endif /* TPP_HAVE_MACRO___has_embed */
#if TPP_HAVE_MACRO___FILE__
#define KWD___FILE__ TPP_KWD___FILE__
#endif /* TPP_HAVE_MACRO___FILE__ */
#if TPP_HAVE_MACRO___LINE__
#define KWD___LINE__ TPP_KWD___LINE__
#endif /* TPP_HAVE_MACRO___LINE__ */
#if TPP_HAVE_MACRO___TIME__
#define KWD___TIME__ TPP_KWD___TIME__
#endif /* TPP_HAVE_MACRO___TIME__ */
#if TPP_HAVE_MACRO___DATE__
#define KWD___DATE__ TPP_KWD___DATE__
#endif /* TPP_HAVE_MACRO___DATE__ */
#if TPP_HAVE_MACRO___COLUMN__
#define KWD___COLUMN__ TPP_KWD___COLUMN__
#endif /* TPP_HAVE_MACRO___COLUMN__ */
#if TPP_HAVE_MACRO___BASE_FILE__
#define KWD___BASE_FILE__ TPP_KWD___BASE_FILE__
#endif /* TPP_HAVE_MACRO___BASE_FILE__ */
#if TPP_HAVE_MACRO___FILE_NAME__
#define KWD___FILE_NAME__ TPP_KWD___FILE_NAME__
#endif /* TPP_HAVE_MACRO___FILE_NAME__ */
#if TPP_HAVE_MACRO___INCLUDE_LEVEL__
#define KWD___INCLUDE_LEVEL__ TPP_KWD___INCLUDE_LEVEL__
#endif /* TPP_HAVE_MACRO___INCLUDE_LEVEL__ */
#if TPP_HAVE_MACRO___INCLUDE_DEPTH__
#define KWD___INCLUDE_DEPTH__ TPP_KWD___INCLUDE_DEPTH__
#endif /* TPP_HAVE_MACRO___INCLUDE_DEPTH__ */
#if TPP_HAVE_MACRO___COUNTER__
#define KWD___COUNTER__ TPP_KWD___COUNTER__
#endif /* TPP_HAVE_MACRO___COUNTER__ */
#if TPP_HAVE_MACRO___TIMESTAMP__
#define KWD___TIMESTAMP__ TPP_KWD___TIMESTAMP__
#endif /* TPP_HAVE_MACRO___TIMESTAMP__ */
#if TPP_HAVE_NUMERIC_DATE_MACROS
#define KWD___DATE_DAY__ TPP_KWD___DATE_DAY__
#endif /* TPP_HAVE_NUMERIC_DATE_MACROS */
#if TPP_HAVE_NUMERIC_DATE_MACROS
#define KWD___DATE_WDAY__ TPP_KWD___DATE_WDAY__
#endif /* TPP_HAVE_NUMERIC_DATE_MACROS */
#if TPP_HAVE_NUMERIC_DATE_MACROS
#define KWD___DATE_YDAY__ TPP_KWD___DATE_YDAY__
#endif /* TPP_HAVE_NUMERIC_DATE_MACROS */
#if TPP_HAVE_NUMERIC_DATE_MACROS
#define KWD___DATE_MONTH__ TPP_KWD___DATE_MONTH__
#endif /* TPP_HAVE_NUMERIC_DATE_MACROS */
#if TPP_HAVE_NUMERIC_DATE_MACROS
#define KWD___DATE_YEAR__ TPP_KWD___DATE_YEAR__
#endif /* TPP_HAVE_NUMERIC_DATE_MACROS */
#if TPP_HAVE_NUMERIC_TIME_MACROS
#define KWD___TIME_SEC__ TPP_KWD___TIME_SEC__
#endif /* TPP_HAVE_NUMERIC_TIME_MACROS */
#if TPP_HAVE_NUMERIC_TIME_MACROS
#define KWD___TIME_MIN__ TPP_KWD___TIME_MIN__
#endif /* TPP_HAVE_NUMERIC_TIME_MACROS */
#if TPP_HAVE_NUMERIC_TIME_MACROS
#define KWD___TIME_HOUR__ TPP_KWD___TIME_HOUR__
#endif /* TPP_HAVE_NUMERIC_TIME_MACROS */
#if TPP_HAVE_MACRO___TPP_EVAL
#define KWD___TPP_EVAL TPP_KWD___TPP_EVAL
#endif /* TPP_HAVE_MACRO___TPP_EVAL */
#if TPP_HAVE_MACRO___TPP_EXEC
#define KWD___TPP_EXEC TPP_KWD___TPP_EXEC
#endif /* TPP_HAVE_MACRO___TPP_EXEC */
#if TPP_HAVE_MACRO___TPP_UNIQUE
#define KWD___TPP_UNIQUE TPP_KWD___TPP_UNIQUE
#endif /* TPP_HAVE_MACRO___TPP_UNIQUE */
#if TPP_HAVE_MACRO___TPP_LOAD_FILE
#define KWD___TPP_LOAD_FILE TPP_KWD___TPP_LOAD_FILE
#endif /* TPP_HAVE_MACRO___TPP_LOAD_FILE */
#if TPP_HAVE_MACRO___TPP_COUNTER
#define KWD___TPP_COUNTER TPP_KWD___TPP_COUNTER
#endif /* TPP_HAVE_MACRO___TPP_COUNTER */
#if TPP_HAVE_MACRO___TPP_RANDOM
#define KWD___TPP_RANDOM TPP_KWD___TPP_RANDOM
#endif /* TPP_HAVE_MACRO___TPP_RANDOM */
#if TPP_HAVE_MACRO___TPP_STR_DECOMPILE
#define KWD___TPP_STR_DECOMPILE TPP_KWD___TPP_STR_DECOMPILE
#endif /* TPP_HAVE_MACRO___TPP_STR_DECOMPILE */
#if TPP_HAVE_MACRO___TPP_STR_SUBSTR
#define KWD___TPP_STR_SUBSTR TPP_KWD___TPP_STR_SUBSTR
#endif /* TPP_HAVE_MACRO___TPP_STR_SUBSTR */
#if TPP_HAVE_MACRO___TPP_STR_SUBSTR
#define KWD___TPP_STR_AT TPP_KWD___TPP_STR_AT
#endif /* TPP_HAVE_MACRO___TPP_STR_SUBSTR */
#if TPP_HAVE_MACRO___TPP_STR_PACK
#define KWD___TPP_STR_PACK TPP_KWD___TPP_STR_PACK
#endif /* TPP_HAVE_MACRO___TPP_STR_PACK */
#if TPP_HAVE_MACRO___TPP_STR_SIZE
#define KWD___TPP_STR_SIZE TPP_KWD___TPP_STR_SIZE
#endif /* TPP_HAVE_MACRO___TPP_STR_SIZE */
#if TPP_HAVE_MACRO___TPP_COUNT_TOKENS
#define KWD___TPP_COUNT_TOKENS TPP_KWD___TPP_COUNT_TOKENS
#endif /* TPP_HAVE_MACRO___TPP_COUNT_TOKENS */
#if TPP_HAVE_MACRO___TPP_IDENTIFIER
#define KWD___TPP_IDENTIFIER TPP_KWD___TPP_IDENTIFIER
#endif /* TPP_HAVE_MACRO___TPP_IDENTIFIER */
#if TPP_HAVE_VA_ARGS_IN_MACROS
#define KWD___VA_ARGS__ TPP_KWD___VA_ARGS__
#endif /* TPP_HAVE_VA_ARGS_IN_MACROS */
#if TPP_HAVE_VA_COMMA_IN_MACROS
#define KWD___VA_COMMA__ TPP_KWD___VA_COMMA__
#endif /* TPP_HAVE_VA_COMMA_IN_MACROS */
#if TPP_HAVE_VA_NARGS_IN_MACROS
#define KWD___VA_NARGS__ TPP_KWD___VA_NARGS__
#endif /* TPP_HAVE_VA_NARGS_IN_MACROS */
#if TPP_HAVE_VA_OPT_IN_MACROS
#define KWD___VA_OPT__ TPP_KWD___VA_OPT__
#endif /* TPP_HAVE_VA_OPT_IN_MACROS */
#if TPP_HAVE_BUILTIN_EXPR_DEFINED
#define KWD_defined TPP_KWD_defined
#endif /* TPP_HAVE_BUILTIN_EXPR_DEFINED */
#if TPP_HAVE_CPP_PREDEFINED_MACROS
#define KWD___TPP_VERSION__ TPP_KWD___TPP_VERSION__
#endif /* TPP_HAVE_CPP_PREDEFINED_MACROS */
#if TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed
#define KWD_limit TPP_KWD_limit
#endif /* TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed */
#if TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed
#define KWD_prefix TPP_KWD_prefix
#endif /* TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed */
#if TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed
#define KWD_suffix TPP_KWD_suffix
#endif /* TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed */
#if TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed
#define KWD_if_empty TPP_KWD_if_empty
#endif /* TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed */
#if (TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed) && TPP_HAVE_CPP_EMBED_OFFSET
#define KWD_offset TPP_KWD_offset
#endif /* (TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed) && TPP_HAVE_CPP_EMBED_OFFSET */
#if (TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed) && TPP_HAVE_CPP_EMBED_OFFSET
#define KWD_gnu TPP_KWD_gnu
#endif /* (TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed) && TPP_HAVE_CPP_EMBED_OFFSET */
#if (TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed) && TPP_HAVE_CPP_EMBED_OFFSET
#define KWD_clang TPP_KWD_clang
#endif /* (TPP_HAVE_CPP_EMBED || TPP_HAVE_MACRO___has_embed) && TPP_HAVE_CPP_EMBED_OFFSET */
#if TPP_HAVE_CPP_PREDEFINED_MACROS && TPP_HAVE_MACRO___has_embed
#define KWD___STDC_EMBED_NOT_FOUND__ TPP_KWD___STDC_EMBED_NOT_FOUND__
#endif /* TPP_HAVE_CPP_PREDEFINED_MACROS && TPP_HAVE_MACRO___has_embed */
#if TPP_HAVE_CPP_PREDEFINED_MACROS && TPP_HAVE_MACRO___has_embed
#define KWD___STDC_EMBED_FOUND__ TPP_KWD___STDC_EMBED_FOUND__
#endif /* TPP_HAVE_CPP_PREDEFINED_MACROS && TPP_HAVE_MACRO___has_embed */
#if TPP_HAVE_CPP_PREDEFINED_MACROS && TPP_HAVE_MACRO___has_embed
#define KWD___STDC_EMBED_EMPTY__ TPP_KWD___STDC_EMBED_EMPTY__
#endif /* TPP_HAVE_CPP_PREDEFINED_MACROS && TPP_HAVE_MACRO___has_embed */
#if TPP_HAVE_CPP_FEATURE_MACROS && TPP_HAVE_LEXER_DECODEINT_BINARY_LITERALS
#define KWD___cpp_binary_literals TPP_KWD___cpp_binary_literals
#endif /* TPP_HAVE_CPP_FEATURE_MACROS && TPP_HAVE_LEXER_DECODEINT_BINARY_LITERALS */
#if TPP_HAVE_CPP_FEATURE_MACROS && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL
#define KWD___cpp_raw_strings TPP_KWD___cpp_raw_strings
#endif /* TPP_HAVE_CPP_FEATURE_MACROS && TPP_HAVE_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_CPP_FEATURE_MACROS && TPP_HAVE_STRING_ESCAPE_NAMED
#define KWD___cpp_named_character_escapes TPP_KWD___cpp_named_character_escapes
#endif /* TPP_HAVE_CPP_FEATURE_MACROS && TPP_HAVE_STRING_ESCAPE_NAMED */
#if TPP_HAVE_CPP_FEATURE_MACROS && TPP_HAVE_CPP_EMBED
#define KWD___cpp_pp_embed TPP_KWD___cpp_pp_embed
#endif /* TPP_HAVE_CPP_FEATURE_MACROS && TPP_HAVE_CPP_EMBED */
#if TPP_HAVE_PRAGMA_PUSH_MACRO
#define KWD_push_macro TPP_KWD_push_macro
#endif /* TPP_HAVE_PRAGMA_PUSH_MACRO */
#if TPP_HAVE_PRAGMA_PUSH_MACRO
#define KWD_pop_macro TPP_KWD_pop_macro
#endif /* TPP_HAVE_PRAGMA_PUSH_MACRO */
#if TPP_HAVE_PRAGMA_ONCE
#define KWD_once TPP_KWD_once
#endif /* TPP_HAVE_PRAGMA_ONCE */
#if TPP_HAVE_PRAGMA_TPP
#define KWD_TPP TPP_KWD_TPP
#endif /* TPP_HAVE_PRAGMA_TPP */
#if TPP_HAVE_PRAGMA_REGION
#define KWD_region TPP_KWD_region
#endif /* TPP_HAVE_PRAGMA_REGION */
#if TPP_HAVE_PRAGMA_REGION
#define KWD_endregion TPP_KWD_endregion
#endif /* TPP_HAVE_PRAGMA_REGION */
#if TPP_HAVE_PRAGMA_DEPRECATED
#define KWD_deprecated TPP_KWD_deprecated
#endif /* TPP_HAVE_PRAGMA_DEPRECATED */
#if TPP_HAVE_PRAGMA_TPP_EXEC || TPP_HAVE_PRAGMA_TPP_TPP_EXEC
#define KWD_tpp_exec TPP_KWD_tpp_exec
#endif /* TPP_HAVE_PRAGMA_TPP_EXEC || TPP_HAVE_PRAGMA_TPP_TPP_EXEC */
#if TPP_HAVE_PRAGMA_TPP_SET_KEYWORD_FLAGS || TPP_HAVE_PRAGMA_TPP_TPP_SET_KEYWORD_FLAGS
#define KWD_tpp_set_keyword_flags TPP_KWD_tpp_set_keyword_flags
#endif /* TPP_HAVE_PRAGMA_TPP_SET_KEYWORD_FLAGS || TPP_HAVE_PRAGMA_TPP_TPP_SET_KEYWORD_FLAGS */
#if TPP_HAVE_PRAGMA_EXTENSION
#define KWD_extension TPP_KWD_extension
#endif /* TPP_HAVE_PRAGMA_EXTENSION */
#if ((TPP_HAVE_PRAGMA_EXTENSION || TPP_HAVE_PRAGMA_TPP_EXTENSION) && TPP_HAVE_EXTENSIONS_PUSH_POP) || ((TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC || TPP_HAVE_PRAGMA_TPP_WARNING) && TPP_HAVE_WARNINGS_PUSH_POP) || (TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_WARNINGS_PUSH_POP)
#define KWD_push TPP_KWD_push
#endif /* ((TPP_HAVE_PRAGMA_EXTENSION || TPP_HAVE_PRAGMA_TPP_EXTENSION) && TPP_HAVE_EXTENSIONS_PUSH_POP) || ((TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC || TPP_HAVE_PRAGMA_TPP_WARNING) && TPP_HAVE_WARNINGS_PUSH_POP) || (TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_WARNINGS_PUSH_POP) */
#if ((TPP_HAVE_PRAGMA_EXTENSION || TPP_HAVE_PRAGMA_TPP_EXTENSION) && TPP_HAVE_EXTENSIONS_PUSH_POP) || ((TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC || TPP_HAVE_PRAGMA_TPP_WARNING) && TPP_HAVE_WARNINGS_PUSH_POP) || (TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_WARNINGS_PUSH_POP)
#define KWD_pop TPP_KWD_pop
#endif /* ((TPP_HAVE_PRAGMA_EXTENSION || TPP_HAVE_PRAGMA_TPP_EXTENSION) && TPP_HAVE_EXTENSIONS_PUSH_POP) || ((TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC || TPP_HAVE_PRAGMA_TPP_WARNING) && TPP_HAVE_WARNINGS_PUSH_POP) || (TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_WARNINGS_PUSH_POP) */
#if TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING
#define KWD_disable TPP_KWD_disable
#endif /* TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING */
#if TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING
#define KWD_enable TPP_KWD_enable
#endif /* TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING */
#if (TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING) && TPP_HAVE_WARNING_SUPPRESS
#define KWD_suppress TPP_KWD_suppress
#endif /* (TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING) && TPP_HAVE_WARNING_SUPPRESS */
#if ((TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING) && TPP_HAVE_WARNING_DEFAULT) || (TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_INCLUDE_PATH_AFTER) || TPP_HAVE_PRAGMA_TPP_KEYWORD_FEATURES
#define KWD_default TPP_KWD_default
#endif /* ((TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING) && TPP_HAVE_WARNING_DEFAULT) || (TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_INCLUDE_PATH_AFTER) || TPP_HAVE_PRAGMA_TPP_KEYWORD_FEATURES */
#if TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING
#define KWD_fatal TPP_KWD_fatal
#endif /* TPP_HAVE_PRAGMA_WARNING || TPP_HAVE_PRAGMA_TPP_WARNING */
#if TPP_HAVE_PRAGMA_MESSAGE
#define KWD_message TPP_KWD_message
#endif /* TPP_HAVE_PRAGMA_MESSAGE */
#if TPP_HAVE_PRAGMA_GCC
#define KWD_GCC TPP_KWD_GCC
#endif /* TPP_HAVE_PRAGMA_GCC */
#if TPP_HAVE_PRAGMA_GCC_POISON
#define KWD_poison TPP_KWD_poison
#endif /* TPP_HAVE_PRAGMA_GCC_POISON */
#if TPP_HAVE_PRAGMA_GCC_SYSTEM_HEADER
#define KWD_system_header TPP_KWD_system_header
#endif /* TPP_HAVE_PRAGMA_GCC_SYSTEM_HEADER */
#if TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC
#define KWD_diagnostic TPP_KWD_diagnostic
#endif /* TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC */
#if TPP_HAVE_PRAGMA_GCC_DEPENDENCY
#define KWD_dependency TPP_KWD_dependency
#endif /* TPP_HAVE_PRAGMA_GCC_DEPENDENCY */
#if TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC
#define KWD_ignored TPP_KWD_ignored
#endif /* TPP_HAVE_PRAGMA_GCC_DIAGNOSTIC */
#if TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH
#define KWD_include_path TPP_KWD_include_path
#endif /* TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH */
#if TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH
#define KWD_clear TPP_KWD_clear
#endif /* TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH */
#if TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_INCLUDE_PATH_QUOTE
#define KWD_quote TPP_KWD_quote
#endif /* TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_INCLUDE_PATH_QUOTE */
#if TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_INCLUDE_PATH_SYSHDR
#define KWD_system TPP_KWD_system
#endif /* TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_INCLUDE_PATH_SYSHDR */
#if TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_INCLUDE_PATH_AFTER
#define KWD_dirafter TPP_KWD_dirafter
#endif /* TPP_HAVE_PRAGMA_TPP_INCLUDE_PATH && TPP_HAVE_INCLUDE_PATH_AFTER */
#endif /* TPP_HAVE_API_TOKEN_NAMES_IN_GLOBAL_NAMESPACE */
/*[[[end]]]*/

TPP_DECL_END
/*[[[tpp-end]]]*/

#endif /* !GUARD_TPP_TOKEN_ALIASES_H */
