/* Copyright (c) 2017-2026 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2017-2026 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef GUARD_TPP_TOKEN_H
#define GUARD_TPP_TOKEN_H 1

#include "api.h"

#include "config.h"
#include "ctype.h"
#include "error.h"
#include "string.h"

/*[[[tpp-begin]]]*/
TPP_DECL_BEGIN


typedef enum tpp_token_id {
	/* Token IDs can also represent (certain) error */



	/* --------------------------------------------------------------------
	 * HARD_ERROR: TPP_ENOMEM
	 * --------------------------------------------------------------------
	 *
	 * Out of memory
	 *
	 * A call to `tpp_malloc()' or `tpp_realloc()' returned NULL, indicating
	 * that the system is out of heap memory. */
	TPP_TOK_ENOMEM = (int)TPP_ENOMEM,



	/* --------------------------------------------------------------------
	 * HARD_ERROR: TPP_EIO
	 * --------------------------------------------------------------------
	 *
	 * Filesystem I/O operation failed */
	TPP_TOK_EIO = (int)TPP_EIO,



#if TPP_HAVE_FILE_NONBLOCK
	/* --------------------------------------------------------------------
	 * SOFT_ERROR: TPP_EWOULDBLOCK
	 * --------------------------------------------------------------------
	 *
	 * Operation would block, but non-blocking was requested
	 *
	 * You will only see this error if you made use of "TPP_HAVE_FILE_NONBLOCK"
	 * This is a temporary error that means that the next token cannot be read
	 * *right now* because reading from the underlying I/O file would block.
	 *
	 * -> You will not see this error when building with "-DTPP_HAVE_FILE_NONBLOCK=0"
	 * -> You will not see this error when not using the "TPP_FILE_IOFLAGS_NONBLOCK" flag */
	TPP_TOK_EWOULDBLOCK = (int)TPP_EWOULDBLOCK, /* [SOFT_ERROR] */
#define _TPP_CASE_TPP_TOK_EWOULDBLOCK case TPP_TOK_EWOULDBLOCK:
#else /* TPP_HAVE_FILE_NONBLOCK */
#define _TPP_CASE_TPP_TOK_EWOULDBLOCK /* nothing */
#endif /* !TPP_HAVE_FILE_NONBLOCK */



#if TPP_HAVE_WARNINGS
	/* --------------------------------------------------------------------
	 * SOFT_ERROR / HARD_ERROR: TPP_ELEXERROR
	 * --------------------------------------------------------------------
	 *
	 * Hard lexer error (usually when too many -Werror were emitted)
	 *
	 * This error should be treated as a HARD_ERROR in most cases, in that
	 * it should be propagated. However, since it is always generated by
	 * TPP itself, you *could* in theory also change lexer configuration
	 * and re-try the failing operation (though if you do that, you will
	 * probably run into the same error again) */
	TPP_TOK_ELEXERROR   = (int)TPP_ELEXERROR,

	/* --------------------------------------------------------------------
	 * HARD_ERROR: TPP_EIO
	 * --------------------------------------------------------------------
	 *
	 * Printer registered for "tpp_lexer_warnf" returned an error.
	 * Since this error is not related to TPP itself, this error should
	 * be propagated. */
	TPP_TOK_EWARNPRINT  = (int)TPP_EWARNPRINT,
#define _TPP_CASE_TPP_TOK_ELEXERROR  case TPP_TOK_ELEXERROR:
#define _TPP_CASE_TPP_TOK_EWARNPRINT case TPP_TOK_EWARNPRINT:
#else /* TPP_HAVE_WARNINGS */
#define _TPP_CASE_TPP_TOK_ELEXERROR  /* nothing */
#define _TPP_CASE_TPP_TOK_EWARNPRINT /* nothing */
#endif /* !TPP_HAVE_WARNINGS */

/* Check if a given "tpp_token_id id" describes an error (rather than a token) */
#define TPP_TOK_ISERR(id)  ((int)(id) < 0)

/* Return the "tpp_token_id" representation of "err".
 * The caller must ensure that "err" has an associated "TPP_TOK_E*" entry. */
#define TPP_TOK_OFERR(err) ((tpp_token_id)(int)(err))

/* Same as "TPP_TOK_OFERR()", but returns "TPP_TOK_EOF" for "TPP_EOK" */
#if 1
#define TPP_TOK_OFERR_OR_EOF(err) ((tpp_token_id)(int)(err))
#else
#define TPP_TOK_OFERR_OR_EOF(err) ((err) == TPP_EOK ? TPP_TOK_EOF : TPP_TOK_OFERR(err))
#endif

/* Convert a given "tpp_token_id id" into the associated error code "TPP_E*"
 * The caller must ensure that "TPP_TOK_ISERR(id) == true" */
#define TPP_TOK_ASERR(id)  ((tpp_errno)(int)(id))

/* Convenience macro to list the case-labels for all "TPP_TOK_E*" errors. */
#define TPP_CASE_TPP_TOK_ERR      \
	case TPP_TOK_ENOMEM:          \
	case TPP_TOK_EIO:             \
	_TPP_CASE_TPP_TOK_EWOULDBLOCK \
	_TPP_CASE_TPP_TOK_ELEXERROR   \
	_TPP_CASE_TPP_TOK_EWARNPRINT

/* Return the token ID used to describe a given byte-code "ch" */
#define TPP_TOK_OFCHAR(ch) ((tpp_token_id)(unsigned int)(tpp_char)(ch))



	TPP_TOK_EOF   = '\0', /* "<eof>" END-OF-FILE (will always be ZERO) */
	TPP_TOK_LF    = '\n', /* "<linefeed>" Line-feed (always generated by `tpp_lexer_yieldraw()', filtered later if disabled) */
	TPP_TOK_SPACE = ' ',  /* "<space>" Whitespace (always generated by `tpp_lexer_yieldraw()', filtered later if disabled) */

	/* Single-character tokens (always equal to that character's ordinal). */
	TPP_TOK_EQUAL     = '=',
	TPP_TOK_AT        = '@',
	TPP_TOK_BACKSLASH = '\\',
	TPP_TOK_DOT       = '.',
	TPP_TOK_COMMA     = ',',
	TPP_TOK_COLON     = ':',
	TPP_TOK_POUND     = '#',
	TPP_TOK_LANGLE    = '<',
	TPP_TOK_RANGLE    = '>',
	TPP_TOK_LPAREN    = '(',
	TPP_TOK_RPAREN    = ')',
	TPP_TOK_LBRACKET  = '[',
	TPP_TOK_RBRACKET  = ']',
	TPP_TOK_LBRACE    = '{',
	TPP_TOK_RBRACE    = '}',
	TPP_TOK_PERCENT   = '%',
	TPP_TOK_EXCLAIM   = '!',
	TPP_TOK_AMP       = '&',
	TPP_TOK_PIPE      = '|',
	TPP_TOK_PLUS      = '+',
	TPP_TOK_MINUS     = '-',
	TPP_TOK_STAR      = '*',
	TPP_TOK_SLASH     = '/',
	TPP_TOK_QMARK     = '?',
	TPP_TOK_SEMICOLON = ';',
	TPP_TOK_TILDE     = '~',
	TPP_TOK_HAT       = '^',
#if TPP_HAVE_TPP_TOK_DOLLAR
	TPP_TOK_DOLLAR    = '$',
#endif /* TPP_HAVE_TPP_TOK_DOLLAR */

	/* Double(or more)-character tokens. */
	TPP_INTERNAL(TPP_TOK_MULTICHAR_BEGIN) = 255, /* KEEP THIS THE FIRST MULTICHAR TOKEN! */
#if TPP_HAVE_UNICODE
	TPP_TOK_UNICHAR, /* "<unicode character>" Misc unicode character that could not be classified */
#endif /* TPP_HAVE_UNICODE */
#if TPP_HAVE_TPP_TOK_INT
	TPP_TOK_INT, /* "<integer>" 42 */
#endif /* TPP_HAVE_TPP_TOK_INT */
#if TPP_HAVE_TPP_TOK_FLOAT
	TPP_TOK_FLOAT, /* "<float>" 42.0 */
#endif /* TPP_HAVE_TPP_TOK_FLOAT */

#if TPP_HAVE_TPP_TOK_COMMENTLIKE
	TPP_TOK_COMMENTLIKE_MIN,
	TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_MIN) = TPP_TOK_COMMENTLIKE_MIN - 1,
#if TPP_HAVE_TPP_TOK_C_COMMENT
	TPP_TOK_C_COMMENT, /* "<comment>" like this one! */
#define _TPP_CASE_TPP_TOK_C_COMMENT case TPP_TOK_C_COMMENT:
#else /* TPP_HAVE_TPP_TOK_C_COMMENT */
#define _TPP_CASE_TPP_TOK_C_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_C_COMMENT */
#if TPP_HAVE_TPP_TOK_PASCAL_COMMENT
	TPP_TOK_PASCAL_COMMENT, // "<comment>" "(*like this one!*)"
#define _TPP_CASE_TPP_TOK_PASCAL_COMMENT case TPP_TOK_PASCAL_COMMENT:
#else /* TPP_HAVE_TPP_TOK_PASCAL_COMMENT */
#define _TPP_CASE_TPP_TOK_PASCAL_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PASCAL_COMMENT */
	TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_NOLINE_MAX),
	TPP_TOK_COMMENTLIKE_NOLINE_MAX = TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_NOLINE_MAX) - 1,
#if TPP_HAVE_TPP_TOK_CXX_COMMENT
	TPP_TOK_CXX_COMMENT, // "<comment>" like this one!
#define _TPP_CASE_TPP_TOK_CXX_COMMENT case TPP_TOK_CXX_COMMENT:
#else /* TPP_HAVE_TPP_TOK_CXX_COMMENT */
#define _TPP_CASE_TPP_TOK_CXX_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_COMMENT */
#if TPP_HAVE_TPP_TOK_SHELL_COMMENT
	TPP_TOK_SHELL_COMMENT, // "<comment>" "# like this one!"
#define _TPP_CASE_TPP_TOK_SHELL_COMMENT case TPP_TOK_SHELL_COMMENT:
#else /* TPP_HAVE_TPP_TOK_SHELL_COMMENT */
#define _TPP_CASE_TPP_TOK_SHELL_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SHELL_COMMENT */
#if TPP_HAVE_TPP_TOK_ASM_COMMENT
	TPP_TOK_ASM_COMMENT, // "<comment>" "/ like this one!"
#define _TPP_CASE_TPP_TOK_ASM_COMMENT case TPP_TOK_ASM_COMMENT:
#else /* TPP_HAVE_TPP_TOK_ASM_COMMENT */
#define _TPP_CASE_TPP_TOK_ASM_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_ASM_COMMENT */
#if TPP_HAVE_TPP_TOK_SQL_COMMENT
	TPP_TOK_SQL_COMMENT, // "<comment>" "-- like this one!"
#define _TPP_CASE_TPP_TOK_SQL_COMMENT case TPP_TOK_SQL_COMMENT:
#else /* TPP_HAVE_TPP_TOK_SQL_COMMENT */
#define _TPP_CASE_TPP_TOK_SQL_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SQL_COMMENT */
	TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_MAX),
	TPP_TOK_COMMENTLIKE_MAX = TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_MAX) - 1,
#define TPP_CASE_TPP_TOK_COMMENT_NOLINE \
	_TPP_CASE_TPP_TOK_C_COMMENT         \
	_TPP_CASE_TPP_TOK_PASCAL_COMMENT
#define TPP_CASE_TPP_TOK_COMMENT_LINE \
	_TPP_CASE_TPP_TOK_CXX_COMMENT     \
	_TPP_CASE_TPP_TOK_SHELL_COMMENT   \
	_TPP_CASE_TPP_TOK_ASM_COMMENT     \
	_TPP_CASE_TPP_TOK_SQL_COMMENT
#define TPP_TOK_ISCOMMENT(id)                     \
	((int)(id) >= (int)TPP_TOK_COMMENTLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_MAX)
#define TPP_CASE_TPP_TOK_COMMENT    \
	TPP_CASE_TPP_TOK_COMMENT_NOLINE \
	TPP_CASE_TPP_TOK_COMMENT_LINE
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE */
#define TPP_TOK_ISCOMMENT(id)           0
#define TPP_CASE_TPP_TOK_COMMENT_NOLINE /* nothing */
#define TPP_CASE_TPP_TOK_COMMENT_LINE   /* nothing */
#define TPP_CASE_TPP_TOK_COMMENT        /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE */
#if TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE
#define TPP_TOK_ISCOMMENT_NOLINE(id)              \
	((int)(id) >= (int)TPP_TOK_COMMENTLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_NOLINE_MAX)
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE */
#define TPP_TOK_ISCOMMENT_NOLINE(id) 0
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE */
#if TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE
#define TPP_TOK_ISCOMMENT_LINE(id)                      \
	((int)(id) > (int)TPP_TOK_COMMENTLIKE_NOLINE_MAX && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_MAX)
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE */
#define TPP_TOK_ISCOMMENT_LINE(id) 0
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE */


#if TPP_HAVE_TPP_TOK_STRINGLIKE
	TPP_TOK_STRINGLIKE_MIN,
	TPP_INTERNAL(_TPP_TOK_STRINGLIKE_MIN) = TPP_TOK_STRINGLIKE_MIN - 1,
#if TPP_HAVE_TPP_TOK_CHAR
	TPP_TOK_CHAR, /* "<char>" 'foo' */
#define _TPP_CASE_TPP_TOK_CHAR case TPP_TOK_CHAR:
#else /* TPP_HAVE_TPP_TOK_CHAR */
#define _TPP_CASE_TPP_TOK_CHAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CHAR */
#if TPP_HAVE_TPP_TOK_STRING
	TPP_TOK_STRING, /* "<string>" "foo" */
#define _TPP_CASE_TPP_TOK_STRING case TPP_TOK_STRING:
#else /* TPP_HAVE_TPP_TOK_STRING */
#define _TPP_CASE_TPP_TOK_STRING /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STRING */
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_STRING_LITERAL, /* "<string>" R"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL case TPP_TOK_CXX_RAW_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL
	TPP_TOK_CXX_WIDE_STRING_LITERAL, /* "<string>" L"foo" */
#define _TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL case TPP_TOK_CXX_WIDE_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL, /* "<string>" LR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL case TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL
	TPP_TOK_CXX_UTF8_STRING_LITERAL, /* "<string>" u8"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL case TPP_TOK_CXX_UTF8_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL, /* "<string>" u8R"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL
	TPP_TOK_CXX_UTF16_STRING_LITERAL, /* "<string>" u"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL case TPP_TOK_CXX_UTF16_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL, /* "<string>" uR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL
	TPP_TOK_CXX_UTF32_STRING_LITERAL, /* "<string>" U"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL case TPP_TOK_CXX_UTF32_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL, /* "<string>" UR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL
	TPP_TOK_RAW_STRING_LITERAL, /* "<string>" R"foo"  r"foo"  */
#define _TPP_CASE_TPP_TOK_RAW_STRING_LITERAL case TPP_TOK_RAW_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_RAW_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL
	TPP_TOK_RAW_CHAR_LITERAL, /* "<string>" R'bar'  r'bar' */
#define _TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL case TPP_TOK_RAW_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL
	TPP_TOK_BLOCK_STRING_LITERAL, /* "<string>" """foo""" */
#define _TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL case TPP_TOK_BLOCK_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL
	TPP_TOK_BLOCK_CHAR_LITERAL, /* "<string>" '''foo''' */
#define _TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL case TPP_TOK_BLOCK_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL */
	TPP_INTERNAL(_TPP_TOK_STRINGLIKE_MAX),
	TPP_TOK_STRINGLIKE_MAX = TPP_INTERNAL(_TPP_TOK_STRINGLIKE_MAX) - 1,
#define TPP_TOK_ISSTRING(id)                     \
	((int)(id) >= (int)TPP_TOK_STRINGLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_STRINGLIKE_MAX)
#define TPP_CASE_TPP_TOK_STRING                    \
	_TPP_CASE_TPP_TOK_CHAR                         \
	_TPP_CASE_TPP_TOK_STRING                       \
	_TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL       \
	_TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL      \
	_TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL  \
	_TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL      \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL  \
	_TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL     \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL \
	_TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL     \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL \
	_TPP_CASE_TPP_TOK_RAW_STRING_LITERAL           \
	_TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL             \
	_TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL         \
	_TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL
#else /* TPP_HAVE_TPP_TOK_STRINGLIKE */
#define TPP_TOK_ISSTRING(id)    0
#define TPP_CASE_TPP_TOK_STRING /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STRINGLIKE */

#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE
	TPP_TOK_LANGLE_LANGLE, /* "<<" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE
	TPP_TOK_RANGLE_RANGLE, /* ">>" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL
	TPP_TOK_EQUAL_EQUAL, /* "==" */
#endif /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL
	TPP_TOK_EXCLAIM_EQUAL, /* "!=" */
#endif /* TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_EQUAL
	TPP_TOK_RANGLE_EQUAL, /* ">=" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_EQUAL
	TPP_TOK_LANGLE_EQUAL, /* "<=" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_DOT_DOT_DOT
	TPP_TOK_DOT_DOT_DOT, /* "..." */
#endif /* TPP_HAVE_TPP_TOK_DOT_DOT_DOT */
#if TPP_HAVE_TPP_TOK_PLUS_EQUAL
	TPP_TOK_PLUS_EQUAL, /* "+=" */
#endif /* TPP_HAVE_TPP_TOK_PLUS_EQUAL */
#if TPP_HAVE_TPP_TOK_MINUS_EQUAL
	TPP_TOK_MINUS_EQUAL, /* "-=" */
#endif /* TPP_HAVE_TPP_TOK_MINUS_EQUAL */
#if TPP_HAVE_TPP_TOK_STAR_EQUAL
	TPP_TOK_STAR_EQUAL, /* "*=" */
#endif /* TPP_HAVE_TPP_TOK_STAR_EQUAL */
#if TPP_HAVE_TPP_TOK_SLASH_EQUAL
	TPP_TOK_SLASH_EQUAL, /* "/=" */
#endif /* TPP_HAVE_TPP_TOK_SLASH_EQUAL */
#if TPP_HAVE_TPP_TOK_PERCENT_EQUAL
	TPP_TOK_PERCENT_EQUAL, /* "%=" */
#endif /* TPP_HAVE_TPP_TOK_PERCENT_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL
	TPP_TOK_LANGLE_LANGLE_EQUAL, /* "<<=" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL
	TPP_TOK_RANGLE_RANGLE_EQUAL, /* ">>=" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_AMP_EQUAL
	TPP_TOK_AMP_EQUAL, /* "&=" */
#endif /* TPP_HAVE_TPP_TOK_AMP_EQUAL */
#if TPP_HAVE_TPP_TOK_PIPE_EQUAL
	TPP_TOK_PIPE_EQUAL, /* "|=" */
#endif /* TPP_HAVE_TPP_TOK_PIPE_EQUAL */
#if TPP_HAVE_TPP_TOK_HAT_EQUAL
	TPP_TOK_HAT_EQUAL, /* "^=" */
#endif /* TPP_HAVE_TPP_TOK_HAT_EQUAL */
#if TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL
	TPP_TOK_STAR_STAR_EQUAL, /* "**=" */
#endif /* TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL */
#if TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL
	TPP_TOK_SLASH_SLASH_EQUAL, /* "//=" */
#endif /* TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL */
#if TPP_HAVE_TPP_TOK_AT_EQUAL
	TPP_TOK_AT_EQUAL, /* "@=" */
#endif /* TPP_HAVE_TPP_TOK_AT_EQUAL */
#if TPP_HAVE_TPP_TOK_POUND_POUND
	TPP_TOK_POUND_POUND, /* "##" */
#endif /* TPP_HAVE_TPP_TOK_POUND_POUND */
#if TPP_HAVE_TPP_TOK_AMP_AMP
	TPP_TOK_AMP_AMP, /* "&&" */
#endif /* TPP_HAVE_TPP_TOK_AMP_AMP */
#if TPP_HAVE_TPP_TOK_PIPE_PIPE
	TPP_TOK_PIPE_PIPE, /* "||" */
#endif /* TPP_HAVE_TPP_TOK_PIPE_PIPE */
#if TPP_HAVE_TPP_TOK_HAT_HAT
	TPP_TOK_HAT_HAT, /* "^^" */
#endif /* TPP_HAVE_TPP_TOK_HAT_HAT */
#if TPP_HAVE_TPP_TOK_PLUS_PLUS
	TPP_TOK_PLUS_PLUS, /* "++" */
#endif /* TPP_HAVE_TPP_TOK_PLUS_PLUS */
#if TPP_HAVE_TPP_TOK_MINUS_MINUS
	TPP_TOK_MINUS_MINUS, /* "--" */
#endif /* TPP_HAVE_TPP_TOK_MINUS_MINUS */
#if TPP_HAVE_TPP_TOK_STAR_STAR
	TPP_TOK_STAR_STAR, /* "**" */
#endif /* TPP_HAVE_TPP_TOK_STAR_STAR */
#if TPP_HAVE_TPP_TOK_SLASH_SLASH
	TPP_TOK_SLASH_SLASH, /* "//" */
#endif /* TPP_HAVE_TPP_TOK_SLASH_SLASH */
#if TPP_HAVE_TPP_TOK_TILDE_TILDE
	TPP_TOK_TILDE_TILDE, /* "~~" */
#endif /* TPP_HAVE_TPP_TOK_TILDE_TILDE */
#if TPP_HAVE_TPP_TOK_TILDE_EQUAL
	TPP_TOK_TILDE_EQUAL, /* "~=" */
#endif /* TPP_HAVE_TPP_TOK_TILDE_EQUAL */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE
	TPP_TOK_MINUS_RANGLE, /* "->" */
#endif /* TPP_HAVE_TPP_TOK_MINUS_RANGLE */
#if TPP_HAVE_TPP_TOK_COLON_EQUAL
	TPP_TOK_COLON_EQUAL, /* ":=" */
#endif /* TPP_HAVE_TPP_TOK_COLON_EQUAL */
#if TPP_HAVE_TPP_TOK_COLON_COLON
	TPP_TOK_COLON_COLON, /* "::" */
#endif /* TPP_HAVE_TPP_TOK_COLON_COLON */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR
	TPP_TOK_MINUS_RANGLE_STAR, /* "->*" */
#endif /* TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR */
#if TPP_HAVE_TPP_TOK_DOT_STAR
	TPP_TOK_DOT_STAR, /* ".*" */
#endif /* TPP_HAVE_TPP_TOK_DOT_STAR */
#if TPP_HAVE_TPP_TOK_DOT_DOT
	TPP_TOK_DOT_DOT, /* ".." */
#endif /* TPP_HAVE_TPP_TOK_DOT_DOT */
#if TPP_HAVE_TPP_TOK_LANGLE_RANGLE
	TPP_TOK_LANGLE_RANGLE, /* "<>" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE
	TPP_TOK_LANGLE_LANGLE_LANGLE, /* "<<<" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE
	TPP_TOK_RANGLE_RANGLE_RANGLE, /* ">>>" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL
	TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL, /* "<<<=" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL
	TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL, /* ">>>=" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL
	TPP_TOK_EQUAL_EQUAL_EQUAL, /* "===" */
#endif /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL
	TPP_TOK_EXCLAIM_EQUAL_EQUAL, /* "!==" */
#endif /* TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_QMARK_QMARK
	TPP_TOK_QMARK_QMARK, /* "??" */
#endif /* TPP_HAVE_TPP_TOK_QMARK_QMARK */
#if TPP_HAVE_TPP_TOK_QMARK_EQUAL
	TPP_TOK_QMARK_EQUAL, /* "?=" */
#endif /* TPP_HAVE_TPP_TOK_QMARK_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_LANGLE
	TPP_TOK_RANGLE_LANGLE, /* "><" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_PLUS
	TPP_TOK_EQUAL_PLUS, /* "=+" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_PLUS */
#if TPP_HAVE_TPP_TOK_EQUAL_MINUS
	TPP_TOK_EQUAL_MINUS, /* "=-" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_MINUS */
#if TPP_HAVE_TPP_TOK_EQUAL_STAR
	TPP_TOK_EQUAL_STAR, /* "=*" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_STAR */
#if TPP_HAVE_TPP_TOK_EQUAL_STAR_STAR
	TPP_TOK_EQUAL_STAR_STAR, /* "=**" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_STAR_STAR */
#if TPP_HAVE_TPP_TOK_EQUAL_SLASH
	TPP_TOK_EQUAL_SLASH, /* "=/" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_SLASH */
#if TPP_HAVE_TPP_TOK_EQUAL_SLASH_SLASH
	TPP_TOK_EQUAL_SLASH_SLASH, /* "=//" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_SLASH_SLASH */
#if TPP_HAVE_TPP_TOK_EQUAL_PERCENT
	TPP_TOK_EQUAL_PERCENT, /* "=%" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_PERCENT */
#if TPP_HAVE_TPP_TOK_EQUAL_AMP
	TPP_TOK_EQUAL_AMP, /* "=&" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_AMP */
#if TPP_HAVE_TPP_TOK_EQUAL_PIPE
	TPP_TOK_EQUAL_PIPE, /* "=|" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_PIPE */
#if TPP_HAVE_TPP_TOK_EQUAL_HAT
	TPP_TOK_EQUAL_HAT, /* "=^" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_HAT */
#if TPP_HAVE_TPP_TOK_EQUAL_LANGLE
	TPP_TOK_EQUAL_LANGLE, /* "=<" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_LANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE
	TPP_TOK_EQUAL_LANGLE_LANGLE, /* "=<<" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE
	TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE, /* "=<<<" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_RANGLE
	TPP_TOK_EQUAL_RANGLE, /* "=>" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE
	TPP_TOK_EQUAL_RANGLE_RANGLE, /* "=>>" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE
	TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE, /* "=>>>" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_AT
	TPP_TOK_EQUAL_AT, /* "=@" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_AT */
#if TPP_HAVE_TPP_TOK_EQUAL_TILDE
	TPP_TOK_EQUAL_TILDE, /* "=~" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_TILDE */
#if TPP_HAVE_TPP_TOK_EQUAL_COLON
	TPP_TOK_EQUAL_COLON, /* "=:" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_COLON */
#if TPP_HAVE_TPP_TOK_EQUAL_EXCLAIM
	TPP_TOK_EQUAL_EXCLAIM, /* "=!" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_EXCLAIM */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EXCLAIM
	TPP_TOK_EQUAL_EQUAL_EXCLAIM, /* "==!" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EXCLAIM */
#if TPP_HAVE_TPP_TOK_EQUAL_QMARK
	TPP_TOK_EQUAL_QMARK, /* "=?" */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_QMARK */
#if TPP_HAVE_TPP_TOK_LANGLE_MINUS
	TPP_TOK_LANGLE_MINUS, /* "<-" */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_STAR_LANGLE_MINUS
	TPP_TOK_STAR_LANGLE_MINUS, /* "*<-" */
#endif /* !TPP_HAVE_TPP_TOK_STAR_LANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_STAR_DOT
	TPP_TOK_STAR_DOT, /* "*." */
#endif /* !TPP_HAVE_TPP_TOK_STAR_DOT */
	TPP_TOK_MULTICHAR_END, /* KEEP THIS THE LAST MULTICHAR TOKEN! */
	TPP_TOK_KEYWORD_BEGIN = TPP_TOK_MULTICHAR_END, /* First builtin keyword */
	TPP_INTERNAL(_TPP_TOK_KEYWORD_BEGIN) = TPP_TOK_KEYWORD_BEGIN - 1,
#define TPP_DEFS
#define TPP_KWD(id, string) id,
#include TPP_CONFIG_DEFS_FILENAME
#undef TPP_DEFS
	TPP_TOK_USERKEYWORD_BEGIN, /* First user-defined (non-builtin) keyword */
} tpp_token_id;

/* Helper macros to easily detect certain types of whitespace. */
#define TPP_TOK_ISSPACE_OR_COMMENT(id)       ((id) == TPP_TOK_SPACE || TPP_TOK_ISCOMMENT_NOLINE(id))
#define TPP_TOK_ISLF_OR_COMMENT(id)          ((id) == TPP_TOK_LF || TPP_TOK_ISCOMMENT_LINE(id))
#define TPP_TOK_ISSPACE_OR_LF_OR_COMMENT(id) ((id) == TPP_TOK_SPACE || (id) == TPP_TOK_LF || TPP_TOK_ISCOMMENT(id))


/* Helper macros to determine which (and what kind of) keyword is described by a given `id' */
#define TPP_TOK_ISKEYWORD(id)        ((int)(id) >= (int)TPP_TOK_KEYWORD_BEGIN)
#define TPP_TOK_ISUSERKEYWORD(id)    ((int)(id) >= (int)TPP_TOK_USERKEYWORD_BEGIN)
#define TPP_TOK_ISBUILTINKEYWORD(id) (TPP_TOK_ISKEYWORD(id) && !TPP_TOK_ISUSERKEYWORD(id))

#if TPP_HAVE_STRTOKENID
/* Returns the "*" in "TPP_TOK_*" of "id", which must be a (non-keyword and non-error) token ID */
TPP_DECL TPP_WUNUSED char const *TPPCALL tpp_strtokenid(tpp_token_id id);
#endif /* TPP_HAVE_STRTOKENID */

#if TPP_HAVE_REPRTOKENID
/* Similar to `tpp_strtokenid()', but returns a (canonical) representation of "id" */
TPP_DECL TPP_WUNUSED char const *TPPCALL tpp_reprtokenid(tpp_token_id id);
#endif /* TPP_HAVE_REPRTOKENID */

struct tpp_keyword;
typedef struct tpp_token {
	tpp_token_id              TPP_INTERNAL(tt_id);    /* Token ID (never set to one of `TPP_TOK_E*'; iow: always positive or TPP_TOK_EOF) */
	struct tpp_keyword const *TPP_INTERNAL(tt_kwd);   /* [1..1][valid_if(TPP_TOK_ISKEYWORD(tt_id))] Keyword identified by `tt_id' */
	tpp_char const           *TPP_INTERNAL(tt_start); /* [1..1][>= tt_chunk->ts_str && <= tt_end] Token start pointer */
	tpp_char const           *TPP_INTERNAL(tt_end);   /* [1..1][>= tt_start && <= tt_chunk->ts_str+tt_chunk->ts_len] Token end pointer */
	TPP_REF tpp_string       *TPP_INTERNAL(tt_chunk); /* [0..1] Text chunk containing "tt_start" and "tt_end" (or "NULL" if not needed) */
} tpp_token;

/* Public API */
#define tpp_token_copy(self, other)             \
	(void)(*(self) = *(other),                  \
	       !((self)->TPP_INTERNAL(tt_chunk)) || \
	       (tpp_string_incref((self)->TPP_INTERNAL(tt_chunk)), 1))
#define tpp_token_fini(self)                    \
	(void)(!((self)->TPP_INTERNAL(tt_chunk)) || \
	       (tpp_string_decref((self)->TPP_INTERNAL(tt_chunk)), 1))
#define tpp_token_getid(self)    ((self)->TPP_INTERNAL(tt_id))
#define tpp_token_getkwd(self)   ((self)->TPP_INTERNAL(tt_kwd)) /* Only valid when "TPP_TOK_ISKEYWORD(tpp_token_getid(self))" */
#define tpp_token_getstart(self) ((self)->TPP_INTERNAL(tt_start))
#define tpp_token_getend(self)   ((self)->TPP_INTERNAL(tt_end))
#define tpp_token_getlen(self)   ((tpp_size)(tpp_token_getend(self) - tpp_token_getstart(self)))

/* Convenience aliases */
#define tpp_token_iseof(self)                    (tpp_token_getid(self) == TPP_TOK_EOF)
#define tpp_token_isspace_or_comment(self)       TPP_TOK_ISSPACE_OR_COMMENT(tpp_token_getid(self))
#define tpp_token_islf_or_comment(self)          TPP_TOK_ISLF_OR_COMMENT(tpp_token_getid(self))
#define tpp_token_isspace_or_lf_or_comment(self) TPP_TOK_ISSPACE_OR_LF_OR_COMMENT(tpp_token_getid(self))
#define tpp_token_iskeyword(self)                TPP_TOK_ISKEYWORD(tpp_token_getid(self))
#define tpp_token_isuserkeyword(self)            TPP_TOK_ISUSERKEYWORD(tpp_token_getid(self))
#define tpp_token_isbuiltinkeyword(self)         TPP_TOK_ISBUILTINKEYWORD(tpp_token_getid(self))
#define tpp_token_iscomment(self)                TPP_TOK_ISCOMMENT(tpp_token_getid(self))
#define tpp_token_iscomment_line(self)           TPP_TOK_ISCOMMENT_LINE(tpp_token_getid(self))
#define tpp_token_iscomment_noline(self)         TPP_TOK_ISCOMMENT_NOLINE(tpp_token_getid(self))
#define tpp_token_isstring(self)                 TPP_TOK_ISSTRING(tpp_token_getid(self))


#if TPP_HAVE_TOKEN_ENCODESTRING
/* \-encode "data...+=num_bytes" by passing it to "printer"
 * NOTE: Leading/trailing " (or ')-characters are *NOT* printed!
 *
 * @return: >= 0: Sum of positive return values of "printer"
 * @return: < 0:  First negative return value of "printer".
 *                Note that this function never causes errors
 *                on its own, meaning that the meaning of
 *                *all* negative values is entirely up to the
 *                given "printer"! */
TPP_DECL TPP_WUNUSED TPP_NONNULL((2)) tpp_ssize TPPCALL
tpp_token_encodestring(tpp_formatprinter printer, void *arg,
                       void const *data, tpp_size num_bytes);
#endif /* TPP_HAVE_TOKEN_ENCODESTRING */

TPP_DECL_END
/*[[[tpp-end]]]*/

#endif /* !GUARD_TPP_TOKEN_H */
