/* Copyright (c) 2017-2026 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2017-2026 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef GUARD_TPP_TOKEN_STRTOKENID_C
#define GUARD_TPP_TOKEN_STRTOKENID_C 1
#define TPP_BUILDING 1

#include "api.h"

#include "config.h"
#include "ctype.h"
#include "error.h"
#include "string.h"
#include "token.h"

/*[[[tpp-begin]]]*/
TPP_DECL_BEGIN

#if TPP_HAVE_STRTOKENID
/* Returns the "*" in "TPP_TOK_*" of "id", which must be a (non-keyword and non-error) token ID */
TPP_IMPL TPP_WUNUSED char const *TPPCALL
tpp_strtokenid(tpp_token_id id) {
	switch (id) {
#define TPP_STRTOKENID_CASE(x) case TPP_TOK_##x: return #x;
	TPP_STRTOKENID_CASE(EOF)
	TPP_STRTOKENID_CASE(LF)
	TPP_STRTOKENID_CASE(SPACE)
	TPP_STRTOKENID_CASE(PLUS)
	TPP_STRTOKENID_CASE(AMP)
	TPP_STRTOKENID_CASE(EQUAL)
	TPP_STRTOKENID_CASE(AT)
	TPP_STRTOKENID_CASE(BACKSLASH)
	TPP_STRTOKENID_CASE(COLON)
	TPP_STRTOKENID_CASE(COMMA)
	TPP_STRTOKENID_CASE(SLASH)
	TPP_STRTOKENID_CASE(DOT)
	TPP_STRTOKENID_CASE(POUND)
	TPP_STRTOKENID_CASE(LANGLE)
	TPP_STRTOKENID_CASE(LBRACE)
	TPP_STRTOKENID_CASE(LBRACKET)
	TPP_STRTOKENID_CASE(LPAREN)
	TPP_STRTOKENID_CASE(PERCENT)
	TPP_STRTOKENID_CASE(STAR)
	TPP_STRTOKENID_CASE(EXCLAIM)
	TPP_STRTOKENID_CASE(PIPE)
	TPP_STRTOKENID_CASE(QMARK)
	TPP_STRTOKENID_CASE(RANGLE)
	TPP_STRTOKENID_CASE(RBRACE)
	TPP_STRTOKENID_CASE(RBRACKET)
	TPP_STRTOKENID_CASE(RPAREN)
	TPP_STRTOKENID_CASE(SEMICOLON)
	TPP_STRTOKENID_CASE(MINUS)
	TPP_STRTOKENID_CASE(TILDE)
	TPP_STRTOKENID_CASE(HAT)
#if TPP_HAVE_UNICODE
	TPP_STRTOKENID_CASE(UNICHAR)
#endif /* TPP_HAVE_UNICODE */
#if TPP_HAVE_TPP_TOK_INT
	TPP_STRTOKENID_CASE(INT)
#endif /* TPP_HAVE_TPP_TOK_INT */
#if TPP_HAVE_TPP_TOK_FLOAT
	TPP_STRTOKENID_CASE(FLOAT)
#endif /* TPP_HAVE_TPP_TOK_FLOAT */

#if TPP_HAVE_TPP_TOK_COMMENTLIKE
#if TPP_HAVE_TPP_TOK_CXX_COMMENT
	TPP_STRTOKENID_CASE(CXX_COMMENT)
#endif /* TPP_HAVE_TPP_TOK_CXX_COMMENT */
#if TPP_HAVE_TPP_TOK_C_COMMENT
	TPP_STRTOKENID_CASE(C_COMMENT)
#endif /* TPP_HAVE_TPP_TOK_C_COMMENT */
#if TPP_HAVE_TPP_TOK_PASCAL_COMMENT
	TPP_STRTOKENID_CASE(PASCAL_COMMENT)
#endif /* TPP_HAVE_TPP_TOK_PASCAL_COMMENT */
#if TPP_HAVE_TPP_TOK_SHELL_COMMENT
	TPP_STRTOKENID_CASE(SHELL_COMMENT)
#endif /* TPP_HAVE_TPP_TOK_SHELL_COMMENT */
#if TPP_HAVE_TPP_TOK_ASM_COMMENT
	TPP_STRTOKENID_CASE(ASM_COMMENT)
#endif /* TPP_HAVE_TPP_TOK_ASM_COMMENT */
#if TPP_HAVE_TPP_TOK_SQL_COMMENT
	TPP_STRTOKENID_CASE(SQL_COMMENT)
#endif /* TPP_HAVE_TPP_TOK_SQL_COMMENT */
#endif /* TPP_HAVE_TPP_TOK_COMMENTLIKE */

#if TPP_HAVE_TPP_TOK_STRINGLIKE
#if TPP_HAVE_TPP_TOK_CHAR
	TPP_STRTOKENID_CASE(CHAR)
#endif /* !TPP_HAVE_TPP_TOK_CHAR */
#if TPP_HAVE_TPP_TOK_STRING
	TPP_STRTOKENID_CASE(STRING)
#endif /* TPP_HAVE_TPP_TOK_STRING */
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_RAW_STRING_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_WIDE_STRING_LITERAL)
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_RAW_WIDE_STRING_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#endif /* TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_UTF8_STRING_LITERAL)
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_RAW_UTF8_STRING_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#endif /* TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_UTF16_STRING_LITERAL)
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_RAW_UTF16_STRING_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#endif /* TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_UTF32_STRING_LITERAL)
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_STRTOKENID_CASE(CXX_RAW_UTF32_STRING_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#endif /* TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL
	TPP_STRTOKENID_CASE(RAW_STRING_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL
	TPP_STRTOKENID_CASE(RAW_CHAR_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL
	TPP_STRTOKENID_CASE(BLOCK_STRING_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL
	TPP_STRTOKENID_CASE(BLOCK_CHAR_LITERAL)
#endif /* TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL */
#endif /* TPP_HAVE_TPP_TOK_STRINGLIKE */

#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE
	TPP_STRTOKENID_CASE(LANGLE_LANGLE)
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE
	TPP_STRTOKENID_CASE(RANGLE_RANGLE)
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL
	TPP_STRTOKENID_CASE(EQUAL_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL
	TPP_STRTOKENID_CASE(EXCLAIM_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_EQUAL
	TPP_STRTOKENID_CASE(RANGLE_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_EQUAL
	TPP_STRTOKENID_CASE(LANGLE_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_DOT_DOT_DOT
	TPP_STRTOKENID_CASE(DOT_DOT_DOT)
#endif /* TPP_HAVE_TPP_TOK_DOT_DOT_DOT */
#if TPP_HAVE_TPP_TOK_PLUS_EQUAL
	TPP_STRTOKENID_CASE(PLUS_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_PLUS_EQUAL */
#if TPP_HAVE_TPP_TOK_MINUS_EQUAL
	TPP_STRTOKENID_CASE(MINUS_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_MINUS_EQUAL */
#if TPP_HAVE_TPP_TOK_STAR_EQUAL
	TPP_STRTOKENID_CASE(STAR_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_STAR_EQUAL */
#if TPP_HAVE_TPP_TOK_SLASH_EQUAL
	TPP_STRTOKENID_CASE(SLASH_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_SLASH_EQUAL */
#if TPP_HAVE_TPP_TOK_PERCENT_EQUAL
	TPP_STRTOKENID_CASE(PERCENT_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_PERCENT_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL
	TPP_STRTOKENID_CASE(LANGLE_LANGLE_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL
	TPP_STRTOKENID_CASE(RANGLE_RANGLE_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_AMP_EQUAL
	TPP_STRTOKENID_CASE(AMP_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_AMP_EQUAL */
#if TPP_HAVE_TPP_TOK_PIPE_EQUAL
	TPP_STRTOKENID_CASE(PIPE_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_PIPE_EQUAL */
#if TPP_HAVE_TPP_TOK_HAT_EQUAL
	TPP_STRTOKENID_CASE(HAT_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_HAT_EQUAL */
#if TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL
	TPP_STRTOKENID_CASE(STAR_STAR_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL */
#if TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL
	TPP_STRTOKENID_CASE(SLASH_SLASH_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL */
#if TPP_HAVE_TPP_TOK_AT_EQUAL
	TPP_STRTOKENID_CASE(AT_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_AT_EQUAL */
#if TPP_HAVE_TPP_TOK_POUND_POUND
	TPP_STRTOKENID_CASE(POUND_POUND)
#endif /* TPP_HAVE_TPP_TOK_POUND_POUND */
#if TPP_HAVE_TPP_TOK_AMP_AMP
	TPP_STRTOKENID_CASE(AMP_AMP)
#endif /* TPP_HAVE_TPP_TOK_AMP_AMP */
#if TPP_HAVE_TPP_TOK_PIPE_PIPE
	TPP_STRTOKENID_CASE(PIPE_PIPE)
#endif /* TPP_HAVE_TPP_TOK_PIPE_PIPE */
#if TPP_HAVE_TPP_TOK_HAT_HAT
	TPP_STRTOKENID_CASE(HAT_HAT)
#endif /* TPP_HAVE_TPP_TOK_HAT_HAT */
#if TPP_HAVE_TPP_TOK_PLUS_PLUS
	TPP_STRTOKENID_CASE(PLUS_PLUS)
#endif /* TPP_HAVE_TPP_TOK_PLUS_PLUS */
#if TPP_HAVE_TPP_TOK_MINUS_MINUS
	TPP_STRTOKENID_CASE(MINUS_MINUS)
#endif /* TPP_HAVE_TPP_TOK_MINUS_MINUS */
#if TPP_HAVE_TPP_TOK_STAR_STAR
	TPP_STRTOKENID_CASE(STAR_STAR)
#endif /* TPP_HAVE_TPP_TOK_STAR_STAR */
#if TPP_HAVE_TPP_TOK_SLASH_SLASH
	TPP_STRTOKENID_CASE(SLASH_SLASH)
#endif /* TPP_HAVE_TPP_TOK_SLASH_SLASH */
#if TPP_HAVE_TPP_TOK_TILDE_TILDE
	TPP_STRTOKENID_CASE(TILDE_TILDE)
#endif /* TPP_HAVE_TPP_TOK_TILDE_TILDE */
#if TPP_HAVE_TPP_TOK_TILDE_EQUAL
	TPP_STRTOKENID_CASE(TILDE_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_TILDE_EQUAL */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE
	TPP_STRTOKENID_CASE(MINUS_RANGLE)
#endif /* TPP_HAVE_TPP_TOK_MINUS_RANGLE */
#if TPP_HAVE_TPP_TOK_COLON_EQUAL
	TPP_STRTOKENID_CASE(COLON_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_COLON_EQUAL */
#if TPP_HAVE_TPP_TOK_COLON_COLON
	TPP_STRTOKENID_CASE(COLON_COLON)
#endif /* TPP_HAVE_TPP_TOK_COLON_COLON */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR
	TPP_STRTOKENID_CASE(MINUS_RANGLE_STAR)
#endif /* TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR */
#if TPP_HAVE_TPP_TOK_DOT_STAR
	TPP_STRTOKENID_CASE(DOT_STAR)
#endif /* TPP_HAVE_TPP_TOK_DOT_STAR */
#if TPP_HAVE_TPP_TOK_DOT_DOT
	TPP_STRTOKENID_CASE(DOT_DOT)
#endif /* TPP_HAVE_TPP_TOK_DOT_DOT */
#if TPP_HAVE_TPP_TOK_LANGLE_RANGLE
	TPP_STRTOKENID_CASE(LANGLE_RANGLE)
#endif /* TPP_HAVE_TPP_TOK_LANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE
	TPP_STRTOKENID_CASE(LANGLE_LANGLE_LANGLE)
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE
	TPP_STRTOKENID_CASE(RANGLE_RANGLE_RANGLE)
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL
	TPP_STRTOKENID_CASE(LANGLE_LANGLE_LANGLE_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL
	TPP_STRTOKENID_CASE(RANGLE_RANGLE_RANGLE_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL
	TPP_STRTOKENID_CASE(EQUAL_EQUAL_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL
	TPP_STRTOKENID_CASE(EXCLAIM_EQUAL_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_QMARK_QMARK
	TPP_STRTOKENID_CASE(QMARK_QMARK)
#endif /* TPP_HAVE_TPP_TOK_QMARK_QMARK */
#if TPP_HAVE_TPP_TOK_QMARK_EQUAL
	TPP_STRTOKENID_CASE(QMARK_EQUAL)
#endif /* TPP_HAVE_TPP_TOK_QMARK_EQUAL */

#undef TPP_STRTOKENID_CASE
	default: break;
	}
	return NULL;
}
#endif /* TPP_HAVE_STRTOKENID */

TPP_DECL_END
/*[[[tpp-end]]]*/

#endif /* !GUARD_TPP_TOKEN_STRTOKENID_C */
