/* Copyright (c) 2017-2026 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2017-2026 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef GUARD_TPP_TOKEN_H
#define GUARD_TPP_TOKEN_H 1

#include "api.h"

#include "config.h"
#include "ctype.h"
#include "error.h"
#include "string.h"

/*[[[tpp-begin]]]*/
TPP_DECL_BEGIN


typedef enum tpp_token_id {
	/* Token IDs can also represent error */
	TPP_TOK_ENOMEM      = (int)TPP_ENOMEM,
	TPP_TOK_EIO         = (int)TPP_EIO,
	TPP_TOK_ENOENT      = (int)TPP_ENOENT,
#if TPP_HAVE_FILE_NONBLOCK
	TPP_TOK_EWOULDBLOCK = (int)TPP_EWOULDBLOCK,
#endif /* TPP_HAVE_FILE_NONBLOCK */
#if TPP_HAVE_WARNINGS
	TPP_TOK_ELEXERROR   = (int)TPP_ELEXERROR,
	TPP_TOK_EWARNPRINT  = (int)TPP_EWARNPRINT,
#endif /* TPP_HAVE_WARNINGS */
#define TPP_TOK_ISERR(id)  ((int)(id) < 0)
#define TPP_TOK_ASERR(id)  ((enum tpp_errno)(int)(id))
#define TPP_TOK_OFERR(err) ((enum tpp_token_id)(int)(err))

	TPP_TOK_EOF   = '\0', /* END-OF-FILE (will always be ZERO) */
	TPP_TOK_LF    = '\n', /* Line-feed (always generated by `tpp_lexer_yieldraw()', filtered later if disabled) */
	TPP_TOK_SPACE = ' ',  /* Whitespace (always generated by `tpp_lexer_yieldraw()', filtered later if disabled) */

	/* Single-character tokens (always equal to that character's ordinal). */
	TPP_TOK_PLUS      = '+',
	TPP_TOK_AMP       = '&',
	TPP_TOK_EQUAL     = '=',
	TPP_TOK_AT        = '@',
	TPP_TOK_BACKSLASH = '\\',
	TPP_TOK_COLON     = ':',
	TPP_TOK_COMMA     = ',',
	TPP_TOK_SLASH     = '/',
	TPP_TOK_DOT       = '.',
	TPP_TOK_POUND     = '#',
	TPP_TOK_LANGLE    = '<',
	TPP_TOK_LBRACE    = '{',
	TPP_TOK_LBRACKET  = '[',
	TPP_TOK_LPAREN    = '(',
	TPP_TOK_PERCENT   = '%',
	TPP_TOK_STAR      = '*',
	TPP_TOK_EXCLAIM   = '!',
	TPP_TOK_PIPE      = '|',
	TPP_TOK_QMARK     = '?',
	TPP_TOK_RANGLE    = '>',
	TPP_TOK_RBRACE    = '}',
	TPP_TOK_RBRACKET  = ']',
	TPP_TOK_RPAREN    = ')',
	TPP_TOK_SEMICOLON = ';',
	TPP_TOK_MINUS     = '-',
	TPP_TOK_TILDE     = '~',
	TPP_TOK_HAT       = '^',

	/* Double(or more)-character tokens. */
	_TPP_TOK_STARTICHAR_BEGIN = 255,
#if TPP_HAVE_UNICODE
	TPP_TOK_UNICHAR, /* Misc unicode character that could not be classified */
#endif /* TPP_HAVE_UNICODE */
#if TPP_HAVE_TPP_TOK_INT
	TPP_TOK_INT, /* 42 */
#endif /* TPP_HAVE_TPP_TOK_INT */
#if TPP_HAVE_TPP_TOK_FLOAT
	TPP_TOK_FLOAT, /* 42.0 */
#endif /* TPP_HAVE_TPP_TOK_FLOAT */

#if TPP_HAVE_TPP_TOK_COMMENTLIKE
	TPP_TOK_COMMENTLIKE_MIN,
	_TPP_TOK_COMMENTLIKE_MIN = TPP_TOK_COMMENTLIKE_MIN - 1,
#if TPP_HAVE_TPP_TOK_C_COMMENT
	TPP_TOK_C_COMMENT, /* like this one! */
#define _TPP_CASE_TPP_TOK_C_COMMENT case TPP_TOK_C_COMMENT:
#else /* TPP_HAVE_TPP_TOK_C_COMMENT */
#define _TPP_CASE_TPP_TOK_C_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_C_COMMENT */
#if TPP_HAVE_TPP_TOK_PASCAL_COMMENT
	TPP_TOK_PASCAL_COMMENT, // "(*like this one!*)"
#define _TPP_CASE_TPP_TOK_PASCAL_COMMENT case TPP_TOK_PASCAL_COMMENT:
#else /* TPP_HAVE_TPP_TOK_PASCAL_COMMENT */
#define _TPP_CASE_TPP_TOK_PASCAL_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PASCAL_COMMENT */
	_TPP_TOK_COMMENTLIKE_NOLINE_MAX,
	TPP_TOK_COMMENTLIKE_NOLINE_MAX = _TPP_TOK_COMMENTLIKE_NOLINE_MAX - 1,
#if TPP_HAVE_TPP_TOK_CXX_COMMENT
	TPP_TOK_CXX_COMMENT, // like this one!
#define _TPP_CASE_TPP_TOK_CXX_COMMENT case TPP_TOK_CXX_COMMENT:
#else /* TPP_HAVE_TPP_TOK_CXX_COMMENT */
#define _TPP_CASE_TPP_TOK_CXX_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_COMMENT */
#if TPP_HAVE_TPP_TOK_SHELL_COMMENT
	TPP_TOK_SHELL_COMMENT, // "# like this one!"
#define _TPP_CASE_TPP_TOK_SHELL_COMMENT case TPP_TOK_SHELL_COMMENT:
#else /* TPP_HAVE_TPP_TOK_SHELL_COMMENT */
#define _TPP_CASE_TPP_TOK_SHELL_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SHELL_COMMENT */
#if TPP_HAVE_TPP_TOK_ASM_COMMENT
	TPP_TOK_ASM_COMMENT, // "/ like this one!"
#define _TPP_CASE_TPP_TOK_ASM_COMMENT case TPP_TOK_ASM_COMMENT:
#else /* TPP_HAVE_TPP_TOK_ASM_COMMENT */
#define _TPP_CASE_TPP_TOK_ASM_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_ASM_COMMENT */
#if TPP_HAVE_TPP_TOK_SQL_COMMENT
	TPP_TOK_SQL_COMMENT, // "-- like this one!"
#define _TPP_CASE_TPP_TOK_SQL_COMMENT case TPP_TOK_SQL_COMMENT:
#else /* TPP_HAVE_TPP_TOK_SQL_COMMENT */
#define _TPP_CASE_TPP_TOK_SQL_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SQL_COMMENT */
	_TPP_TOK_COMMENTLIKE_MAX,
	TPP_TOK_COMMENTLIKE_MAX = _TPP_TOK_COMMENTLIKE_MAX - 1,
#define TPP_TOK_ISCOMMENT(id)                     \
	((int)(id) >= (int)TPP_TOK_COMMENTLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_MAX)
#define TPP_CASE_TPP_TOK_COMMENT_NOLINE \
	_TPP_CASE_TPP_TOK_C_COMMENT         \
	_TPP_CASE_TPP_TOK_PASCAL_COMMENT
#define TPP_CASE_TPP_TOK_COMMENT_LINE \
	_TPP_CASE_TPP_TOK_CXX_COMMENT     \
	_TPP_CASE_TPP_TOK_SHELL_COMMENT   \
	_TPP_CASE_TPP_TOK_ASM_COMMENT     \
	_TPP_CASE_TPP_TOK_SQL_COMMENT
#define TPP_CASE_TPP_TOK_COMMENT    \
	TPP_CASE_TPP_TOK_COMMENT_NOLINE \
	TPP_CASE_TPP_TOK_COMMENT_LINE
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE */
#define TPP_TOK_ISCOMMENT(id)           0
#define TPP_CASE_TPP_TOK_COMMENT_NOLINE /* nothing */
#define TPP_CASE_TPP_TOK_COMMENT_LINE   /* nothing */
#define TPP_CASE_TPP_TOK_COMMENT        /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE */
#if TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE
#define TPP_TOK_ISCOMMENT_NOLINE(id)              \
	((int)(id) >= (int)TPP_TOK_COMMENTLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_NOLINE_MAX)
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE */
#define TPP_TOK_ISCOMMENT_NOLINE(id) 0
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE */
#if TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE
#define TPP_TOK_ISCOMMENT_LINE(id)                      \
	((int)(id) > (int)TPP_TOK_COMMENTLIKE_NOLINE_MAX && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_MAX)
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE */
#define TPP_TOK_ISCOMMENT_LINE(id) 0
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE */


#if TPP_HAVE_TPP_TOK_STRINGLIKE
	TPP_TOK_STRINGLIKE_MIN,
	_TPP_TOK_STRINGLIKE_MIN = TPP_TOK_STRINGLIKE_MIN - 1,
#if TPP_HAVE_TPP_TOK_CHAR
	TPP_TOK_CHAR, /* 'foo' */
#define _TPP_CASE_TPP_TOK_CHAR case TPP_TOK_CHAR:
#else /* TPP_HAVE_TPP_TOK_CHAR */
#define _TPP_CASE_TPP_TOK_CHAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CHAR */
#if TPP_HAVE_TPP_TOK_STRING
	TPP_TOK_STRING, /* "foo" */
#define _TPP_CASE_TPP_TOK_STRING case TPP_TOK_STRING:
#else /* TPP_HAVE_TPP_TOK_STRING */
#define _TPP_CASE_TPP_TOK_STRING /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STRING */
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_STRING_LITERAL, /* R"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL case TPP_TOK_CXX_RAW_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL
	TPP_TOK_CXX_WIDE_STRING_LITERAL, /* L"foo" */
#define _TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL case TPP_TOK_CXX_WIDE_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL, /* LR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL case TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL
	TPP_TOK_CXX_UTF8_STRING_LITERAL, /* u8"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL case TPP_TOK_CXX_UTF8_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL, /* u8R"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL
	TPP_TOK_CXX_UTF16_STRING_LITERAL, /* u"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL case TPP_TOK_CXX_UTF16_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL, /* uR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL
	TPP_TOK_CXX_UTF32_STRING_LITERAL, /* U"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL case TPP_TOK_CXX_UTF32_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL, /* UR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL
	TPP_TOK_RAW_STRING_LITERAL, /* R"foo"  r"foo"  */
#define _TPP_CASE_TPP_TOK_RAW_STRING_LITERAL case TPP_TOK_RAW_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_RAW_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL
	TPP_TOK_RAW_CHAR_LITERAL, /* R'bar'  r'bar' */
#define _TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL case TPP_TOK_RAW_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL
	TPP_TOK_BLOCK_STRING_LITERAL, /* """foo""" */
#define _TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL case TPP_TOK_BLOCK_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL
	TPP_TOK_BLOCK_CHAR_LITERAL, /* '''foo''' */
#define _TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL case TPP_TOK_BLOCK_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL */
	_TPP_TOK_STRINGLIKE_MAX,
	TPP_TOK_STRINGLIKE_MAX = _TPP_TOK_STRINGLIKE_MAX - 1,
#define TPP_TOK_ISSTRING(id)                     \
	((int)(id) >= (int)TPP_TOK_STRINGLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_STRINGLIKE_MAX)
#define TPP_CASE_TPP_TOK_STRING                    \
	_TPP_CASE_TPP_TOK_CHAR                         \
	_TPP_CASE_TPP_TOK_STRING                       \
	_TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL       \
	_TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL      \
	_TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL  \
	_TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL      \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL  \
	_TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL     \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL \
	_TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL     \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL \
	_TPP_CASE_TPP_TOK_RAW_STRING_LITERAL           \
	_TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL             \
	_TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL         \
	_TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL
#else /* TPP_HAVE_TPP_TOK_STRINGLIKE */
#define TPP_TOK_ISSTRING(id)    0
#define TPP_CASE_TPP_TOK_STRING /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STRINGLIKE */

#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE
	TPP_TOK_LANGLE_LANGLE, /* "<<" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE
	TPP_TOK_RANGLE_RANGLE, /* ">>" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL
	TPP_TOK_EQUAL_EQUAL, /* "==" */
#endif /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL
	TPP_TOK_EXCLAIM_EQUAL, /* "!=" */
#endif /* TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_EQUAL
	TPP_TOK_RANGLE_EQUAL, /* ">=" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_EQUAL
	TPP_TOK_LANGLE_EQUAL, /* "<=" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_DOT_DOT_DOT
	TPP_TOK_DOT_DOT_DOT, /* "..." */
#endif /* TPP_HAVE_TPP_TOK_DOT_DOT_DOT */
#if TPP_HAVE_TPP_TOK_PLUS_EQUAL
	TPP_TOK_PLUS_EQUAL, /* "+=" */
#endif /* TPP_HAVE_TPP_TOK_PLUS_EQUAL */
#if TPP_HAVE_TPP_TOK_MINUS_EQUAL
	TPP_TOK_MINUS_EQUAL, /* "-=" */
#endif /* TPP_HAVE_TPP_TOK_MINUS_EQUAL */
#if TPP_HAVE_TPP_TOK_STAR_EQUAL
	TPP_TOK_STAR_EQUAL, /* "*=" */
#endif /* TPP_HAVE_TPP_TOK_STAR_EQUAL */
#if TPP_HAVE_TPP_TOK_SLASH_EQUAL
	TPP_TOK_SLASH_EQUAL, /* "/=" */
#endif /* TPP_HAVE_TPP_TOK_SLASH_EQUAL */
#if TPP_HAVE_TPP_TOK_PERCENT_EQUAL
	TPP_TOK_PERCENT_EQUAL, /* "%=" */
#endif /* TPP_HAVE_TPP_TOK_PERCENT_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL
	TPP_TOK_LANGLE_LANGLE_EQUAL, /* "<<=" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL
	TPP_TOK_RANGLE_RANGLE_EQUAL, /* ">>=" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_AMP_EQUAL
	TPP_TOK_AMP_EQUAL, /* "&=" */
#endif /* TPP_HAVE_TPP_TOK_AMP_EQUAL */
#if TPP_HAVE_TPP_TOK_PIPE_EQUAL
	TPP_TOK_PIPE_EQUAL, /* "|=" */
#endif /* TPP_HAVE_TPP_TOK_PIPE_EQUAL */
#if TPP_HAVE_TPP_TOK_HAT_EQUAL
	TPP_TOK_HAT_EQUAL, /* "^=" */
#endif /* TPP_HAVE_TPP_TOK_HAT_EQUAL */
#if TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL
	TPP_TOK_STAR_STAR_EQUAL, /* "**=" */
#endif /* TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL */
#if TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL
	TPP_TOK_SLASH_SLASH_EQUAL, /* "//=" */
#endif /* TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL */
#if TPP_HAVE_TPP_TOK_AT_EQUAL
	TPP_TOK_AT_EQUAL, /* "@=" */
#endif /* TPP_HAVE_TPP_TOK_AT_EQUAL */
#if TPP_HAVE_TPP_TOK_POUND_POUND
	TPP_TOK_POUND_POUND, /* "##" */
#endif /* TPP_HAVE_TPP_TOK_POUND_POUND */
#if TPP_HAVE_TPP_TOK_AMP_AMP
	TPP_TOK_AMP_AMP, /* "&&" */
#endif /* TPP_HAVE_TPP_TOK_AMP_AMP */
#if TPP_HAVE_TPP_TOK_PIPE_PIPE
	TPP_TOK_PIPE_PIPE, /* "||" */
#endif /* TPP_HAVE_TPP_TOK_PIPE_PIPE */
#if TPP_HAVE_TPP_TOK_HAT_HAT
	TPP_TOK_HAT_HAT, /* "^^" */
#endif /* TPP_HAVE_TPP_TOK_HAT_HAT */
#if TPP_HAVE_TPP_TOK_PLUS_PLUS
	TPP_TOK_PLUS_PLUS, /* "++" */
#endif /* TPP_HAVE_TPP_TOK_PLUS_PLUS */
#if TPP_HAVE_TPP_TOK_MINUS_MINUS
	TPP_TOK_MINUS_MINUS, /* "--" */
#endif /* TPP_HAVE_TPP_TOK_MINUS_MINUS */
#if TPP_HAVE_TPP_TOK_STAR_STAR
	TPP_TOK_STAR_STAR, /* "**" */
#endif /* TPP_HAVE_TPP_TOK_STAR_STAR */
#if TPP_HAVE_TPP_TOK_SLASH_SLASH
	TPP_TOK_SLASH_SLASH, /* "//" */
#endif /* TPP_HAVE_TPP_TOK_SLASH_SLASH */
#if TPP_HAVE_TPP_TOK_TILDE_TILDE
	TPP_TOK_TILDE_TILDE, /* "~~" */
#endif /* TPP_HAVE_TPP_TOK_TILDE_TILDE */
#if TPP_HAVE_TPP_TOK_TILDE_EQUAL
	TPP_TOK_TILDE_EQUAL, /* "~=" */
#endif /* TPP_HAVE_TPP_TOK_TILDE_EQUAL */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE
	TPP_TOK_MINUS_RANGLE, /* "->" */
#endif /* TPP_HAVE_TPP_TOK_MINUS_RANGLE */
#if TPP_HAVE_TPP_TOK_COLON_EQUAL
	TPP_TOK_COLON_EQUAL, /* ":=" */
#endif /* TPP_HAVE_TPP_TOK_COLON_EQUAL */
#if TPP_HAVE_TPP_TOK_COLON_COLON
	TPP_TOK_COLON_COLON, /* "::" */
#endif /* TPP_HAVE_TPP_TOK_COLON_COLON */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR
	TPP_TOK_MINUS_RANGLE_STAR, /* "->*" */
#endif /* TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR */
#if TPP_HAVE_TPP_TOK_DOT_STAR
	TPP_TOK_DOT_STAR, /* ".*" */
#endif /* TPP_HAVE_TPP_TOK_DOT_STAR */
#if TPP_HAVE_TPP_TOK_DOT_DOT
	TPP_TOK_DOT_DOT, /* ".." */
#endif /* TPP_HAVE_TPP_TOK_DOT_DOT */
#if TPP_HAVE_TPP_TOK_LANGLE_RANGLE
	TPP_TOK_LANGLE_RANGLE, /* "<>" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE
	TPP_TOK_LANGLE_LANGLE_LANGLE, /* "<<<" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE
	TPP_TOK_RANGLE_RANGLE_RANGLE, /* ">>>" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL
	TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL, /* "<<<=" */
#endif /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL
	TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL, /* ">>>=" */
#endif /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL
	TPP_TOK_EQUAL_EQUAL_EQUAL, /* "===" */
#endif /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL
	TPP_TOK_EXCLAIM_EQUAL_EQUAL, /* "!==" */
#endif /* TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_QMARK_QMARK
	TPP_TOK_QMARK_QMARK, /* "??" */
#endif /* TPP_HAVE_TPP_TOK_QMARK_QMARK */
#if TPP_HAVE_TPP_TOK_QMARK_EQUAL
	TPP_TOK_QMARK_EQUAL, /* "?=" */
#endif /* TPP_HAVE_TPP_TOK_QMARK_EQUAL */

	TPP_TOK_STARTICHAR_END, /* KEEP THIS THE LAST TOKEN! */
	TPP_TOK_KEYWORD_BEGIN = TPP_TOK_STARTICHAR_END, /* First builtin keyword */
	_TPP_TOK_KEYWORD_BEGIN = TPP_TOK_KEYWORD_BEGIN - 1,
#define TPP_DEFS
#define TPP_KWD(id, string) id,
#include TPP_CONFIG_DEFS_FILENAME
#undef TPP_DEFS
	TPP_TOK_USERKEYWORD_BEGIN, /* First user-defined (non-builtin) keyword */
} tpp_token_id;

/* Helper macros to easily detect certain types of whitespace. */
#define TPP_TOK_ISSPACE_OR_COMMENT(id)       ((id) == TPP_TOK_SPACE || TPP_TOK_ISCOMMENT_NOLINE(id))
#define TPP_TOK_ISLF_OR_COMMENT(id)          ((id) == TPP_TOK_LF || TPP_TOK_ISCOMMENT_LINE(id))
#define TPP_TOK_ISSPACE_OR_LF_OR_COMMENT(id) ((id) == TPP_TOK_SPACE || (id) == TPP_TOK_LF || TPP_TOK_ISCOMMENT(id))


/* Helper macros to determine which (and what kind of) keyword is described by a given `id' */
#define TPP_TOK_ISKEYWORD(id)        ((int)(id) >= (int)TPP_TOK_KEYWORD_BEGIN)
#define TPP_TOK_ISUSERKEYWORD(id)    ((int)(id) >= (int)TPP_TOK_USERKEYWORD_BEGIN)
#define TPP_TOK_ISBUILTINKEYWORD(id) (TPP_TOK_ISKEYWORD(id) && !TPP_TOK_ISUSERKEYWORD(id))

#if TPP_HAVE_STRTOKENID
/* Returns the "*" in "TPP_TOK_*" of "id", which must be a (non-keyword and non-error) token ID */
TPP_DECL TPP_WUNUSED char const *TPPCALL tpp_strtokenid(tpp_token_id id);
#endif /* TPP_HAVE_STRTOKENID */

struct tpp_keyword;
typedef struct tpp_token {
	tpp_token_id              tt_id;    /* Token ID (never set to one of `TPP_TOK_E*'; iow: always positive or TPP_TOK_EOF) */
	struct tpp_keyword const *tt_kwd;   /* [1..1][valid_if(TPP_TOK_ISKEYWORD(tt_id))] Keyword identified by `tt_id' */
	tpp_char const           *tt_start; /* [1..1][>= tt_chunk->ts_str && <= tt_end] Token start pointer */
	tpp_char const           *tt_end;   /* [1..1][>= tt_start && <= tt_chunk->ts_str+tt_chunk->ts_len] Token end pointer */
	TPP_REF tpp_string       *tt_chunk; /* [0..1] Text chunk containing "tt_start" and "tt_end" (or "NULL" if not needed) */
} tpp_token;

#define tpp_token_initcopy(self, other) \
	(void)(*(self) = *(other), tpp_string_incref((self)->tt_chunk))
#define tpp_token_fini(self) tpp_string_decref((self)->tt_chunk)


#if 0
TPP_DECL TPP_WUNUSED TPP_NONNULL((1)) tpp_ssize TPPCALL
tpp_token_encodestring(tpp_formatprinter printer, void *arg,
                       void const *data, tpp_size num_bytes);
#endif


TPP_DECL_END
/*[[[tpp-end]]]*/

#endif /* !GUARD_TPP_TOKEN_H */
