/* Copyright (c) 2017-2026 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2017-2026 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef GUARD_TPP_TOKEN_H
#define GUARD_TPP_TOKEN_H 1

#include "api.h"

#include "config.h"
#include "ctype.h"
#include "error.h"
#include "string.h"

/*[[[tpp-begin]]]*/
TPP_DECL_BEGIN


typedef enum tpp_token_id {
	/* Token IDs can also represent (certain) error */



	/* --------------------------------------------------------------------
	 * HARD_ERROR: TPP_ENOMEM
	 * --------------------------------------------------------------------
	 *
	 * Out of memory
	 *
	 * A call to `tpp_malloc()' or `tpp_realloc()' returned NULL, indicating
	 * that the system is out of heap memory. */
	TPP_TOK_ENOMEM = (int)TPP_ENOMEM,



	/* --------------------------------------------------------------------
	 * HARD_ERROR: TPP_EIO
	 * --------------------------------------------------------------------
	 *
	 * Filesystem I/O operation failed */
	TPP_TOK_EIO = (int)TPP_EIO,



#if TPP_HAVE_FILE_NONBLOCK
	/* --------------------------------------------------------------------
	 * SOFT_ERROR: TPP_EWOULDBLOCK
	 * --------------------------------------------------------------------
	 *
	 * Operation would block, but non-blocking was requested
	 *
	 * You will only see this error if you made use of "TPP_HAVE_FILE_NONBLOCK"
	 * This is a temporary error that means that the next token cannot be read
	 * *right now* because reading from the underlying I/O file would block.
	 *
	 * -> You will not see this error when building with "-DTPP_HAVE_FILE_NONBLOCK=0"
	 * -> You will not see this error when not using the "TPP_FILE_FLAGS_NONBLOCK" flag */
	TPP_TOK_EWOULDBLOCK = (int)TPP_EWOULDBLOCK, /* [SOFT_ERROR] */
#define _TPP_CASE_TPP_TOK_EWOULDBLOCK case TPP_TOK_EWOULDBLOCK:
#else /* TPP_HAVE_FILE_NONBLOCK */
#define _TPP_CASE_TPP_TOK_EWOULDBLOCK /* nothing */
#endif /* !TPP_HAVE_FILE_NONBLOCK */



#if TPP_HAVE_WARNINGS
	/* --------------------------------------------------------------------
	 * SOFT_ERROR / HARD_ERROR: TPP_ELEXERROR
	 * --------------------------------------------------------------------
	 *
	 * Hard lexer error (usually when too many -Werror were emitted)
	 *
	 * This error should be treated as a HARD_ERROR in most cases, in that
	 * it should be propagated. However, since it is always generated by
	 * TPP itself, you *could* in theory also change lexer configuration
	 * and re-try the failing operation (though if you do that, you will
	 * probably run into the same error again) */
	TPP_TOK_ELEXERROR = (int)TPP_ELEXERROR,

	/* --------------------------------------------------------------------
	 * HARD_ERROR: TPP_EWARNPRINT
	 * --------------------------------------------------------------------
	 *
	 * Printer registered for "tpp_lexer_warnf" returned an error.
	 * Since this error is not related to TPP itself, this error should
	 * be propagated. */
	TPP_TOK_EWARNPRINT = (int)TPP_EWARNPRINT,
#define _TPP_CASE_TPP_TOK_ELEXERROR  case TPP_TOK_ELEXERROR:
#define _TPP_CASE_TPP_TOK_EWARNPRINT case TPP_TOK_EWARNPRINT:
#else /* TPP_HAVE_WARNINGS */
#define _TPP_CASE_TPP_TOK_ELEXERROR  /* nothing */
#define _TPP_CASE_TPP_TOK_EWARNPRINT /* nothing */
#endif /* !TPP_HAVE_WARNINGS */

/* Check if a given "tpp_token_id id" describes an error (rather than a token) */
#define TPP_TOK_ISERR(id) tpp_unlikely((int)(id) < 0)

/* Check if a given "tpp_token_id id" describes an error, or TPP_TOK_EOF */
#if 1
#define TPP_TOK_ISERR_OR_EOF(id) ((int)(id) <= 0)
#else
#define TPP_TOK_ISERR_OR_EOF(id) (TPP_TOK_ISERR(id) || (id) == TPP_TOK_EOF)
#endif

/* Return the "tpp_token_id" representation of "err".
 * The caller must ensure that "err" has an associated "TPP_TOK_E*" entry. */
#define TPP_TOK_OFERR(err) ((tpp_token_id)(int)(err))

/* Same as "TPP_TOK_OFERR()", but returns "TPP_TOK_EOF" for "TPP_EOK" */
#if 1
#define TPP_TOK_OFERR_OR_EOF(err) ((tpp_token_id)(int)(err))
#else
#define TPP_TOK_OFERR_OR_EOF(err) ((err) == TPP_EOK ? TPP_TOK_EOF : TPP_TOK_OFERR(err))
#endif

/* Convert a given "tpp_token_id id" into the associated error code "TPP_E*"
 * The caller must ensure that "TPP_TOK_ISERR(id) == true" */
#define TPP_TOK_ASERR(id)        ((tpp_errno)(int)(id))
#define TPP_TOK_ASERR_OR_EOK(id) (TPP_TOK_ISERR(id) ? TPP_TOK_ASERR(id) : TPP_EOK)

/* Convenience macro to list the case-labels for all "TPP_TOK_E*" errors. */
#define TPP_CASE_TPP_TOK_ERR      \
	case TPP_TOK_ENOMEM:          \
	case TPP_TOK_EIO:             \
	_TPP_CASE_TPP_TOK_EWOULDBLOCK \
	_TPP_CASE_TPP_TOK_ELEXERROR   \
	_TPP_CASE_TPP_TOK_EWARNPRINT

/* Return the token ID used to describe the single-character token of "ch" */
#define TPP_TOK_OFCHAR(ch) ((tpp_token_id)(unsigned int)(tpp_char)(ch))
#define TPP_TOK_ISCHAR(id) ((unsigned int)(id) <= 0xff)



	TPP_TOK_EOF   = '\0', /* "<eof>" END-OF-FILE (will always be ZERO; an actual \0-byte in input is treated as `TPP_TOK_SPACE') */
	TPP_TOK_LF    = '\n', /* "<linefeed>" Line-feed (always generated by `tpp_lexer_yieldraw()', filtered later if disabled) */
	TPP_TOK_SPACE = ' ',  /* "<space>" Whitespace (always generated by `tpp_lexer_yieldraw()', filtered later if disabled) */

	/* Single-character tokens (always equal to that character's ordinal). */
	TPP_TOK_EXCLAIM   = '!',
	TPP_TOK_POUND     = '#',
#if TPP_HAVE_TPP_TOK_DOLLAR
	TPP_TOK_DOLLAR    = '$',
#endif /* TPP_HAVE_TPP_TOK_DOLLAR */
	TPP_TOK_PERCENT   = '%',
	TPP_TOK_AMP       = '&',
	TPP_TOK_LPAREN    = '(',
	TPP_TOK_RPAREN    = ')',
	TPP_TOK_STAR      = '*',
	TPP_TOK_PLUS      = '+',
	TPP_TOK_COMMA     = ',',
	TPP_TOK_MINUS     = '-',
	TPP_TOK_DOT       = '.',
	TPP_TOK_SLASH     = '/',
	TPP_TOK_COLON     = ':',
	TPP_TOK_SEMICOLON = ';',
	TPP_TOK_LANGLE    = '<',
	TPP_TOK_EQUAL     = '=',
	TPP_TOK_RANGLE    = '>',
	TPP_TOK_QMARK     = '?',
	TPP_TOK_AT        = '@',
	TPP_TOK_LBRACKET  = '[',
	TPP_TOK_BACKSLASH = '\\',
	TPP_TOK_RBRACKET  = ']',
	TPP_TOK_HAT       = '^',
	TPP_TOK_BACKTICK  = '`',
	TPP_TOK_LBRACE    = '{',
	TPP_TOK_PIPE      = '|',
	TPP_TOK_RBRACE    = '}',
	TPP_TOK_TILDE     = '~',

	/* Double(or more)-character tokens. */
	TPP_INTERNAL(TPP_TOK_MULTICHAR_BEGIN) = 255, /* KEEP THIS THE FIRST MULTICHAR TOKEN! */
#if TPP_HAVE_UNICODE
	TPP_TOK_UNICHAR, /* "<unicode character>" Misc unicode character that could not be classified */
#endif /* TPP_HAVE_UNICODE */
#if TPP_HAVE_TPP_TOK_INT
	TPP_TOK_INT, /* "<integer>" 42 */
#endif /* TPP_HAVE_TPP_TOK_INT */
#if TPP_HAVE_TPP_TOK_FLOAT
	TPP_TOK_FLOAT, /* "<float>" 42.0 */
#endif /* TPP_HAVE_TPP_TOK_FLOAT */

#if TPP_HAVE_TPP_TOK_COMMENTLIKE
	TPP_TOK_COMMENTLIKE_MIN,
	TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_MIN) = TPP_TOK_COMMENTLIKE_MIN - 1,
#if TPP_HAVE_TPP_TOK_SLASH_STAR_COMMENT_STAR_SLASH
	TPP_TOK_SLASH_STAR_COMMENT_STAR_SLASH, /* "<comment>" like this one! */
#define _TPP_CASE_TPP_TOK_SLASH_STAR_COMMENT_STAR_SLASH case TPP_TOK_SLASH_STAR_COMMENT_STAR_SLASH:
#else /* TPP_HAVE_TPP_TOK_SLASH_STAR_COMMENT_STAR_SLASH */
#define _TPP_CASE_TPP_TOK_SLASH_STAR_COMMENT_STAR_SLASH /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SLASH_STAR_COMMENT_STAR_SLASH */
#if TPP_HAVE_TPP_TOK_LPAREN_STAR_COMMENT_STAR_RPAREN
	TPP_TOK_LPAREN_STAR_COMMENT_STAR_RPAREN, // "<comment>" "(*like this one!*)"
#define _TPP_CASE_TPP_TOK_LPAREN_STAR_COMMENT_STAR_RPAREN case TPP_TOK_LPAREN_STAR_COMMENT_STAR_RPAREN:
#else /* TPP_HAVE_TPP_TOK_LPAREN_STAR_COMMENT_STAR_RPAREN */
#define _TPP_CASE_TPP_TOK_LPAREN_STAR_COMMENT_STAR_RPAREN /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LPAREN_STAR_COMMENT_STAR_RPAREN */
#if TPP_HAVE_TPP_TOK_LANGLE_EXCLAIM_MINUS_MINUS_COMMENT_MINUS_MINUS_RANGLE
	TPP_TOK_LANGLE_EXCLAIM_MINUS_MINUS_COMMENT_MINUS_MINUS_RANGLE, // "<comment>" "<!-- like this one! -->"
#define _TPP_CASE_TPP_TOK_LANGLE_EXCLAIM_MINUS_MINUS_COMMENT_MINUS_MINUS_RANGLE case TPP_TOK_LANGLE_EXCLAIM_MINUS_MINUS_COMMENT_MINUS_MINUS_RANGLE:
#else /* TPP_HAVE_TPP_TOK_LANGLE_EXCLAIM_MINUS_MINUS_COMMENT_MINUS_MINUS_RANGLE */
#define _TPP_CASE_TPP_TOK_LANGLE_EXCLAIM_MINUS_MINUS_COMMENT_MINUS_MINUS_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_EXCLAIM_MINUS_MINUS_COMMENT_MINUS_MINUS_RANGLE */
	TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_NOLINE_MAX),
	TPP_TOK_COMMENTLIKE_NOLINE_MAX = TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_NOLINE_MAX) - 1,
#if TPP_HAVE_TPP_TOK_SLASH_SLASH_COMMENT
	TPP_TOK_SLASH_SLASH_COMMENT, // "<comment>" like this one!
#define _TPP_CASE_TPP_TOK_SLASH_SLASH_COMMENT case TPP_TOK_SLASH_SLASH_COMMENT:
#else /* TPP_HAVE_TPP_TOK_SLASH_SLASH_COMMENT */
#define _TPP_CASE_TPP_TOK_SLASH_SLASH_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SLASH_SLASH_COMMENT */
#if TPP_HAVE_TPP_TOK_POUND_COMMENT
	TPP_TOK_POUND_COMMENT, // "<comment>" "# like this one!"
#define _TPP_CASE_TPP_TOK_POUND_COMMENT case TPP_TOK_POUND_COMMENT:
#else /* TPP_HAVE_TPP_TOK_POUND_COMMENT */
#define _TPP_CASE_TPP_TOK_POUND_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_POUND_COMMENT */
#if TPP_HAVE_TPP_TOK_SLASH_COMMENT
	TPP_TOK_SLASH_COMMENT, // "<comment>" "/ like this one!"
#define _TPP_CASE_TPP_TOK_SLASH_COMMENT case TPP_TOK_SLASH_COMMENT:
#else /* TPP_HAVE_TPP_TOK_SLASH_COMMENT */
#define _TPP_CASE_TPP_TOK_SLASH_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SLASH_COMMENT */
#if TPP_HAVE_TPP_TOK_MINUS_MINUS_COMMENT
	TPP_TOK_MINUS_MINUS_COMMENT, // "<comment>" "-- like this one!"
#define _TPP_CASE_TPP_TOK_MINUS_MINUS_COMMENT case TPP_TOK_MINUS_MINUS_COMMENT:
#else /* TPP_HAVE_TPP_TOK_MINUS_MINUS_COMMENT */
#define _TPP_CASE_TPP_TOK_MINUS_MINUS_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_MINUS_COMMENT */
#if TPP_HAVE_TPP_TOK_AT_AT_COMMENT
	TPP_TOK_AT_AT_COMMENT, // "<comment>" "@@ like this one!"
#define _TPP_CASE_TPP_TOK_AT_AT_COMMENT case TPP_TOK_AT_AT_COMMENT:
#else /* TPP_HAVE_TPP_TOK_AT_AT_COMMENT */
#define _TPP_CASE_TPP_TOK_AT_AT_COMMENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_AT_AT_COMMENT */
	TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_MAX),
	TPP_TOK_COMMENTLIKE_MAX = TPP_INTERNAL(_TPP_TOK_COMMENTLIKE_MAX) - 1,
#define TPP_CASE_TPP_TOK_COMMENT_NOLINE               \
	_TPP_CASE_TPP_TOK_SLASH_STAR_COMMENT_STAR_SLASH   \
	_TPP_CASE_TPP_TOK_LPAREN_STAR_COMMENT_STAR_RPAREN \
	_TPP_CASE_TPP_TOK_LANGLE_EXCLAIM_MINUS_MINUS_COMMENT_MINUS_MINUS_RANGLE
#define TPP_CASE_TPP_TOK_COMMENT_LINE     \
	_TPP_CASE_TPP_TOK_SLASH_SLASH_COMMENT \
	_TPP_CASE_TPP_TOK_POUND_COMMENT       \
	_TPP_CASE_TPP_TOK_SLASH_COMMENT       \
	_TPP_CASE_TPP_TOK_MINUS_MINUS_COMMENT \
	_TPP_CASE_TPP_TOK_AT_AT_COMMENT
#define TPP_TOK_ISCOMMENT(id)                     \
	((int)(id) >= (int)TPP_TOK_COMMENTLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_MAX)
#define TPP_CASE_TPP_TOK_COMMENT    \
	TPP_CASE_TPP_TOK_COMMENT_NOLINE \
	TPP_CASE_TPP_TOK_COMMENT_LINE
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE */
#define TPP_TOK_ISCOMMENT(id)           0
#define TPP_CASE_TPP_TOK_COMMENT_NOLINE /* nothing */
#define TPP_CASE_TPP_TOK_COMMENT_LINE   /* nothing */
#define TPP_CASE_TPP_TOK_COMMENT        /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE */
#if TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE
#define TPP_TOK_ISCOMMENT_NOLINE(id)              \
	((int)(id) >= (int)TPP_TOK_COMMENTLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_NOLINE_MAX)
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE */
#define TPP_TOK_ISCOMMENT_NOLINE(id) 0
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE_NOLINE */
#if TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE
#define TPP_TOK_ISCOMMENT_LINE(id)                      \
	((int)(id) > (int)TPP_TOK_COMMENTLIKE_NOLINE_MAX && \
	 (int)(id) <= (int)TPP_TOK_COMMENTLIKE_MAX)
#else /* TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE */
#define TPP_TOK_ISCOMMENT_LINE(id) 0
#endif /* !TPP_HAVE_TPP_TOK_COMMENTLIKE_LINE */


#if TPP_HAVE_TPP_TOK_C_STRINGLIKE
	TPP_TOK_C_STRINGLIKE_MIN,
	TPP_INTERNAL(_TPP_TOK_C_STRINGLIKE_MIN) = TPP_TOK_C_STRINGLIKE_MIN - 1,
#if TPP_HAVE_TPP_TOK_C_STRING
	TPP_TOK_C_STRING, /* "<string>" "foo" */
#define _TPP_CASE_TPP_TOK_C_STRING case TPP_TOK_C_STRING:
#else /* TPP_HAVE_TPP_TOK_C_STRING */
#define _TPP_CASE_TPP_TOK_C_STRING /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_C_STRING */
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_STRING_LITERAL, /* "<string>" R"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL case TPP_TOK_CXX_RAW_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL
	TPP_TOK_CXX_WIDE_STRING_LITERAL, /* "<string>" L"foo" */
#define _TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL case TPP_TOK_CXX_WIDE_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL, /* "<string>" LR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL case TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_WIDE_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL
	TPP_TOK_CXX_UTF8_STRING_LITERAL, /* "<string>" u8"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL case TPP_TOK_CXX_UTF8_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL, /* "<string>" u8R"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF8_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL
	TPP_TOK_CXX_UTF16_STRING_LITERAL, /* "<string>" u"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL case TPP_TOK_CXX_UTF16_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL, /* "<string>" uR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF16_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL
	TPP_TOK_CXX_UTF32_STRING_LITERAL, /* "<string>" U"foo" */
#define _TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL case TPP_TOK_CXX_UTF32_STRING_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL
	TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL, /* "<string>" UR"AB(foo)AB" */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL case TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_STRING_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF32_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL
	TPP_TOK_RAW_STRING_LITERAL, /* "<string>" R"foo"  r"foo"  */
#define _TPP_CASE_TPP_TOK_RAW_STRING_LITERAL case TPP_TOK_RAW_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_RAW_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RAW_STRING_LITERAL */
#if TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL
	TPP_TOK_BLOCK_STRING_LITERAL, /* "<string>" """foo""" */
#define _TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL case TPP_TOK_BLOCK_STRING_LITERAL:
#else /* TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL */
#define _TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_BLOCK_STRING_LITERAL */
	TPP_TOK_C_CHARLIKE_MIN,
	TPP_INTERNAL(_TPP_TOK_C_CHARLIKE_MIN) = TPP_TOK_C_CHARLIKE_MIN - 1,
#if TPP_HAVE_TPP_TOK_C_CHAR
	TPP_TOK_C_CHAR, /* "<char>" 'f' */
#define _TPP_CASE_TPP_TOK_C_CHAR case TPP_TOK_C_CHAR:
#else /* TPP_HAVE_TPP_TOK_C_CHAR */
#define _TPP_CASE_TPP_TOK_C_CHAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_C_CHAR */
#if TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL
	TPP_TOK_CXX_RAW_CHAR_LITERAL, /* "<char>" R'AB(f)AB' */
#define _TPP_CASE_TPP_TOK_CXX_RAW_CHAR_LITERAL case TPP_TOK_CXX_RAW_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_WIDE_CHAR_LITERAL
	TPP_TOK_CXX_WIDE_CHAR_LITERAL, /* "<char>" L'f' */
#define _TPP_CASE_TPP_TOK_CXX_WIDE_CHAR_LITERAL case TPP_TOK_CXX_WIDE_CHAR_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL
	TPP_TOK_CXX_RAW_WIDE_CHAR_LITERAL, /* "<char>" LR'AB(f)AB' */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_CHAR_LITERAL case TPP_TOK_CXX_RAW_WIDE_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_WIDE_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_WIDE_CHAR_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_WIDE_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_WIDE_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF8_CHAR_LITERAL
	TPP_TOK_CXX_UTF8_CHAR_LITERAL, /* "<char>" u8'f' */
#define _TPP_CASE_TPP_TOK_CXX_UTF8_CHAR_LITERAL case TPP_TOK_CXX_UTF8_CHAR_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL
	TPP_TOK_CXX_RAW_UTF8_CHAR_LITERAL, /* "<char>" u8R'AB(f)AB' */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_CHAR_LITERAL case TPP_TOK_CXX_RAW_UTF8_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF8_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF8_CHAR_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF8_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF8_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF16_CHAR_LITERAL
	TPP_TOK_CXX_UTF16_CHAR_LITERAL, /* "<char>" u'f' */
#define _TPP_CASE_TPP_TOK_CXX_UTF16_CHAR_LITERAL case TPP_TOK_CXX_UTF16_CHAR_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL
	TPP_TOK_CXX_RAW_UTF16_CHAR_LITERAL, /* "<char>" uR'AB(f)AB' */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_CHAR_LITERAL case TPP_TOK_CXX_RAW_UTF16_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF16_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF16_CHAR_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF16_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF16_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_CXX_UTF32_CHAR_LITERAL
	TPP_TOK_CXX_UTF32_CHAR_LITERAL, /* "<char>" U'f' */
#define _TPP_CASE_TPP_TOK_CXX_UTF32_CHAR_LITERAL case TPP_TOK_CXX_UTF32_CHAR_LITERAL:
#if TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL
	TPP_TOK_CXX_RAW_UTF32_CHAR_LITERAL, /* "<char>" UR'AB(f)AB' */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_CHAR_LITERAL case TPP_TOK_CXX_RAW_UTF32_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_RAW_CHAR_LITERAL */
#else /* TPP_HAVE_TPP_TOK_CXX_UTF32_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_CXX_UTF32_CHAR_LITERAL     /* nothing */
#define _TPP_CASE_TPP_TOK_CXX_RAW_UTF32_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_CXX_UTF32_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL
	TPP_TOK_RAW_CHAR_LITERAL, /* "<char>" R'f'  r'f'  */
#define _TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL case TPP_TOK_RAW_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RAW_CHAR_LITERAL */
#if TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL
	TPP_TOK_BLOCK_CHAR_LITERAL, /* "<string>" '''foo''' */
#define _TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL case TPP_TOK_BLOCK_CHAR_LITERAL:
#else /* TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL */
#define _TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_BLOCK_CHAR_LITERAL */

	TPP_INTERNAL(_TPP_TOK_C_STRINGLIKE_MAX),
	TPP_TOK_C_STRINGLIKE_MAX = TPP_INTERNAL(_TPP_TOK_C_STRINGLIKE_MAX) - 1,
#if TPP_HAVE_TPP_TOK_C_STRINGLIKE_SQUOTE
#define TPP_TOK_ISSTRING_SQUOTE(id)            \
	((int)(id) >= (int)TPP_TOK_C_CHARLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_C_STRINGLIKE_MAX)
#else /* TPP_HAVE_TPP_TOK_C_STRINGLIKE_SQUOTE */
#define TPP_TOK_ISSTRING_SQUOTE(id) 0
#endif /* !TPP_HAVE_TPP_TOK_C_STRINGLIKE_SQUOTE */
#define TPP_CASE_TPP_TOK_C_STRING_SQUOTE           \
	_TPP_CASE_TPP_TOK_C_CHAR                       \
	_TPP_CASE_TPP_TOK_CXX_RAW_CHAR_LITERAL       \
	_TPP_CASE_TPP_TOK_CXX_WIDE_CHAR_LITERAL      \
	_TPP_CASE_TPP_TOK_CXX_RAW_WIDE_CHAR_LITERAL  \
	_TPP_CASE_TPP_TOK_CXX_UTF8_CHAR_LITERAL      \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF8_CHAR_LITERAL  \
	_TPP_CASE_TPP_TOK_CXX_UTF16_CHAR_LITERAL     \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF16_CHAR_LITERAL \
	_TPP_CASE_TPP_TOK_CXX_UTF32_CHAR_LITERAL     \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF32_CHAR_LITERAL \
	_TPP_CASE_TPP_TOK_RAW_CHAR_LITERAL           \
	_TPP_CASE_TPP_TOK_BLOCK_CHAR_LITERAL

#if TPP_HAVE_TPP_TOK_C_STRINGLIKE_DQUOTE
#define TPP_TOK_ISSTRING_DQUOTE(id)              \
	((int)(id) >= (int)TPP_TOK_C_STRINGLIKE_MIN && \
	 (int)(id) < (int)TPP_TOK_C_CHARLIKE_MIN)
#else /* TPP_HAVE_TPP_TOK_C_STRINGLIKE_DQUOTE */
#define TPP_TOK_ISSTRING_DQUOTE(id) 0
#endif /* !TPP_HAVE_TPP_TOK_C_STRINGLIKE_DQUOTE */
#define TPP_CASE_TPP_TOK_C_STRING_DQUOTE             \
	_TPP_CASE_TPP_TOK_C_STRING                       \
	_TPP_CASE_TPP_TOK_CXX_RAW_STRING_LITERAL       \
	_TPP_CASE_TPP_TOK_CXX_WIDE_STRING_LITERAL      \
	_TPP_CASE_TPP_TOK_CXX_RAW_WIDE_STRING_LITERAL  \
	_TPP_CASE_TPP_TOK_CXX_UTF8_STRING_LITERAL      \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF8_STRING_LITERAL  \
	_TPP_CASE_TPP_TOK_CXX_UTF16_STRING_LITERAL     \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF16_STRING_LITERAL \
	_TPP_CASE_TPP_TOK_CXX_UTF32_STRING_LITERAL     \
	_TPP_CASE_TPP_TOK_CXX_RAW_UTF32_STRING_LITERAL \
	_TPP_CASE_TPP_TOK_RAW_STRING_LITERAL           \
	_TPP_CASE_TPP_TOK_BLOCK_STRING_LITERAL

#define TPP_TOK_ISSTRING(id)                     \
	((int)(id) >= (int)TPP_TOK_C_STRINGLIKE_MIN && \
	 (int)(id) <= (int)TPP_TOK_C_STRINGLIKE_MAX)
#define TPP_CASE_TPP_TOK_C_STRING    \
	TPP_CASE_TPP_TOK_C_STRING_DQUOTE \
	TPP_CASE_TPP_TOK_C_STRING_SQUOTE
#else /* TPP_HAVE_TPP_TOK_C_STRINGLIKE */
#define TPP_TOK_ISSTRING(id)           0
#define TPP_TOK_ISSTRING_DQUOTE(id)    0
#define TPP_TOK_ISSTRING_SQUOTE(id)    0
#define TPP_CASE_TPP_TOK_C_STRING        /* nothing */
#define TPP_CASE_TPP_TOK_C_STRING_DQUOTE /* nothing */
#define TPP_CASE_TPP_TOK_C_STRING_SQUOTE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_C_STRINGLIKE */

	/* Sort multi-char tokens by their first character (to make it possible to
	 * define "tok >= X && tok <= Y"-style checks for multi-char-starts-with-z)
	 *
	 * As a matter of fact: multi-char tokens are sorted lexicographically! */
/*[[[deemon
import * from deemon;
import * from .config;

local firstChars = HashSet(MC_TOKENS.each.first.first).sorted();
for (local firstChar: firstChars) {
	local firstCharName = charNames[firstChar];
	print("#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_", firstCharName);
	print("	TPP_TOK_MC_STARTSWITH_", firstCharName, "_MIN,");
	print("	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_", firstCharName, "_MIN) = TPP_TOK_MC_STARTSWITH_", firstCharName, "_MIN - 1,");
	local fullTokens = MC_TOKENS.filter(e -> e.first.startswith(firstChar)).sorted();
	local fullTokenNames = fullTokens.map(e -> tokenName(e.first));
	for (local fullToken: fullTokens) {
		local fullTokenName = tokenName(fullToken.first);
		print("#if TPP_HAVE_TPP_TOK_", fullTokenName);
		print("	TPP_TOK_", fullTokenName, ", /" "* ", repr fullToken.first, " *" "/");
		print("#define _TPP_CASE_TPP_TOK_", fullTokenName, " case TPP_TOK_", fullTokenName, ":");
		print("#else /" "* TPP_HAVE_TPP_TOK_", fullTokenName, " *" "/");
		print("#define _TPP_CASE_TPP_TOK_", fullTokenName, " /" "* nothing *" "/");
		print("#endif /" "* !TPP_HAVE_TPP_TOK_", fullTokenName, " *" "/");
	}
	print("	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_", firstCharName, "_MAX),");
	print("	TPP_TOK_MC_STARTSWITH_", firstCharName, "_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_", firstCharName, "_MAX) - 1,");
	print("#define TPP_TOK_MC_STARTSWITH_", firstCharName, "(id)                   \\");
	print("	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_", firstCharName, "_MIN && \\");
	print("	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_", firstCharName, "_MAX)");
	print("#define TPP_CASE_TPP_TOK_MC_STARTSWITH_", firstCharName),;
	for (local fullTokenName: fullTokenNames[:-1]) {
		print(" \\\n	_TPP_CASE_TPP_TOK_", fullTokenName),;
	}
	print(" \\\n	_TPP_CASE_TPP_TOK_", fullTokenNames.last);
	print("#else /" "* TPP_HAVE_TPP_TOK_MC_STARTSWITH_", firstCharName, " *" "/");
	print("#define TPP_TOK_MC_STARTSWITH_", firstCharName, "(id)      0");
	print("#define TPP_CASE_TPP_TOK_MC_STARTSWITH_", firstCharName, " /" "* nothing *" "/");
	print("#endif /" "* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_", firstCharName, " *" "/");
	print;
}
]]]*/
#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_EXCLAIM
	TPP_TOK_MC_STARTSWITH_EXCLAIM_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_EXCLAIM_MIN) = TPP_TOK_MC_STARTSWITH_EXCLAIM_MIN - 1,
#if TPP_HAVE_TPP_TOK_EXCLAIM_EXCLAIM
	TPP_TOK_EXCLAIM_EXCLAIM, /* "!!" */
#define _TPP_CASE_TPP_TOK_EXCLAIM_EXCLAIM case TPP_TOK_EXCLAIM_EXCLAIM:
#else /* TPP_HAVE_TPP_TOK_EXCLAIM_EXCLAIM */
#define _TPP_CASE_TPP_TOK_EXCLAIM_EXCLAIM /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EXCLAIM_EXCLAIM */
#if TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL
	TPP_TOK_EXCLAIM_EQUAL, /* "!=" */
#define _TPP_CASE_TPP_TOK_EXCLAIM_EQUAL case TPP_TOK_EXCLAIM_EQUAL:
#else /* TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL */
#define _TPP_CASE_TPP_TOK_EXCLAIM_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL */
#if TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL
	TPP_TOK_EXCLAIM_EQUAL_EQUAL, /* "!==" */
#define _TPP_CASE_TPP_TOK_EXCLAIM_EQUAL_EQUAL case TPP_TOK_EXCLAIM_EQUAL_EQUAL:
#else /* TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL */
#define _TPP_CASE_TPP_TOK_EXCLAIM_EQUAL_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EXCLAIM_EQUAL_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_EXCLAIM_MAX),
	TPP_TOK_MC_STARTSWITH_EXCLAIM_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_EXCLAIM_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_EXCLAIM(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_EXCLAIM_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_EXCLAIM_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_EXCLAIM \
	_TPP_CASE_TPP_TOK_EXCLAIM_EXCLAIM \
	_TPP_CASE_TPP_TOK_EXCLAIM_EQUAL \
	_TPP_CASE_TPP_TOK_EXCLAIM_EQUAL_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_EXCLAIM */
#define TPP_TOK_MC_STARTSWITH_EXCLAIM(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_EXCLAIM /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_EXCLAIM */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_POUND
	TPP_TOK_MC_STARTSWITH_POUND_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_POUND_MIN) = TPP_TOK_MC_STARTSWITH_POUND_MIN - 1,
#if TPP_HAVE_TPP_TOK_POUND_POUND
	TPP_TOK_POUND_POUND, /* "##" */
#define _TPP_CASE_TPP_TOK_POUND_POUND case TPP_TOK_POUND_POUND:
#else /* TPP_HAVE_TPP_TOK_POUND_POUND */
#define _TPP_CASE_TPP_TOK_POUND_POUND /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_POUND_POUND */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_POUND_MAX),
	TPP_TOK_MC_STARTSWITH_POUND_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_POUND_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_POUND(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_POUND_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_POUND_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_POUND \
	_TPP_CASE_TPP_TOK_POUND_POUND
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_POUND */
#define TPP_TOK_MC_STARTSWITH_POUND(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_POUND /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_POUND */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_PERCENT
	TPP_TOK_MC_STARTSWITH_PERCENT_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PERCENT_MIN) = TPP_TOK_MC_STARTSWITH_PERCENT_MIN - 1,
#if TPP_HAVE_TPP_TOK_PERCENT_PERCENT
	TPP_TOK_PERCENT_PERCENT, /* "%%" */
#define _TPP_CASE_TPP_TOK_PERCENT_PERCENT case TPP_TOK_PERCENT_PERCENT:
#else /* TPP_HAVE_TPP_TOK_PERCENT_PERCENT */
#define _TPP_CASE_TPP_TOK_PERCENT_PERCENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PERCENT_PERCENT */
#if TPP_HAVE_TPP_TOK_PERCENT_PERCENT_EQUAL
	TPP_TOK_PERCENT_PERCENT_EQUAL, /* "%%=" */
#define _TPP_CASE_TPP_TOK_PERCENT_PERCENT_EQUAL case TPP_TOK_PERCENT_PERCENT_EQUAL:
#else /* TPP_HAVE_TPP_TOK_PERCENT_PERCENT_EQUAL */
#define _TPP_CASE_TPP_TOK_PERCENT_PERCENT_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PERCENT_PERCENT_EQUAL */
#if TPP_HAVE_TPP_TOK_PERCENT_EQUAL
	TPP_TOK_PERCENT_EQUAL, /* "%=" */
#define _TPP_CASE_TPP_TOK_PERCENT_EQUAL case TPP_TOK_PERCENT_EQUAL:
#else /* TPP_HAVE_TPP_TOK_PERCENT_EQUAL */
#define _TPP_CASE_TPP_TOK_PERCENT_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PERCENT_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PERCENT_MAX),
	TPP_TOK_MC_STARTSWITH_PERCENT_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PERCENT_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_PERCENT(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_PERCENT_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_PERCENT_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_PERCENT \
	_TPP_CASE_TPP_TOK_PERCENT_PERCENT \
	_TPP_CASE_TPP_TOK_PERCENT_PERCENT_EQUAL \
	_TPP_CASE_TPP_TOK_PERCENT_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_PERCENT */
#define TPP_TOK_MC_STARTSWITH_PERCENT(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_PERCENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_PERCENT */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_AMP
	TPP_TOK_MC_STARTSWITH_AMP_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_AMP_MIN) = TPP_TOK_MC_STARTSWITH_AMP_MIN - 1,
#if TPP_HAVE_TPP_TOK_AMP_AMP
	TPP_TOK_AMP_AMP, /* "&&" */
#define _TPP_CASE_TPP_TOK_AMP_AMP case TPP_TOK_AMP_AMP:
#else /* TPP_HAVE_TPP_TOK_AMP_AMP */
#define _TPP_CASE_TPP_TOK_AMP_AMP /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_AMP_AMP */
#if TPP_HAVE_TPP_TOK_AMP_EQUAL
	TPP_TOK_AMP_EQUAL, /* "&=" */
#define _TPP_CASE_TPP_TOK_AMP_EQUAL case TPP_TOK_AMP_EQUAL:
#else /* TPP_HAVE_TPP_TOK_AMP_EQUAL */
#define _TPP_CASE_TPP_TOK_AMP_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_AMP_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_AMP_MAX),
	TPP_TOK_MC_STARTSWITH_AMP_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_AMP_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_AMP(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_AMP_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_AMP_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_AMP \
	_TPP_CASE_TPP_TOK_AMP_AMP \
	_TPP_CASE_TPP_TOK_AMP_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_AMP */
#define TPP_TOK_MC_STARTSWITH_AMP(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_AMP /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_AMP */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_STAR
	TPP_TOK_MC_STARTSWITH_STAR_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_STAR_MIN) = TPP_TOK_MC_STARTSWITH_STAR_MIN - 1,
#if TPP_HAVE_TPP_TOK_STAR_STAR
	TPP_TOK_STAR_STAR, /* "**" */
#define _TPP_CASE_TPP_TOK_STAR_STAR case TPP_TOK_STAR_STAR:
#else /* TPP_HAVE_TPP_TOK_STAR_STAR */
#define _TPP_CASE_TPP_TOK_STAR_STAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STAR_STAR */
#if TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL
	TPP_TOK_STAR_STAR_EQUAL, /* "**=" */
#define _TPP_CASE_TPP_TOK_STAR_STAR_EQUAL case TPP_TOK_STAR_STAR_EQUAL:
#else /* TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL */
#define _TPP_CASE_TPP_TOK_STAR_STAR_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STAR_STAR_EQUAL */
#if TPP_HAVE_TPP_TOK_STAR_DOT
	TPP_TOK_STAR_DOT, /* "*." */
#define _TPP_CASE_TPP_TOK_STAR_DOT case TPP_TOK_STAR_DOT:
#else /* TPP_HAVE_TPP_TOK_STAR_DOT */
#define _TPP_CASE_TPP_TOK_STAR_DOT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STAR_DOT */
#if TPP_HAVE_TPP_TOK_STAR_LANGLE_MINUS
	TPP_TOK_STAR_LANGLE_MINUS, /* "*<-" */
#define _TPP_CASE_TPP_TOK_STAR_LANGLE_MINUS case TPP_TOK_STAR_LANGLE_MINUS:
#else /* TPP_HAVE_TPP_TOK_STAR_LANGLE_MINUS */
#define _TPP_CASE_TPP_TOK_STAR_LANGLE_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STAR_LANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_STAR_EQUAL
	TPP_TOK_STAR_EQUAL, /* "*=" */
#define _TPP_CASE_TPP_TOK_STAR_EQUAL case TPP_TOK_STAR_EQUAL:
#else /* TPP_HAVE_TPP_TOK_STAR_EQUAL */
#define _TPP_CASE_TPP_TOK_STAR_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_STAR_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_STAR_MAX),
	TPP_TOK_MC_STARTSWITH_STAR_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_STAR_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_STAR(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_STAR_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_STAR_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_STAR \
	_TPP_CASE_TPP_TOK_STAR_STAR \
	_TPP_CASE_TPP_TOK_STAR_STAR_EQUAL \
	_TPP_CASE_TPP_TOK_STAR_DOT \
	_TPP_CASE_TPP_TOK_STAR_LANGLE_MINUS \
	_TPP_CASE_TPP_TOK_STAR_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_STAR */
#define TPP_TOK_MC_STARTSWITH_STAR(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_STAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_STAR */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_PLUS
	TPP_TOK_MC_STARTSWITH_PLUS_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PLUS_MIN) = TPP_TOK_MC_STARTSWITH_PLUS_MIN - 1,
#if TPP_HAVE_TPP_TOK_PLUS_PLUS
	TPP_TOK_PLUS_PLUS, /* "++" */
#define _TPP_CASE_TPP_TOK_PLUS_PLUS case TPP_TOK_PLUS_PLUS:
#else /* TPP_HAVE_TPP_TOK_PLUS_PLUS */
#define _TPP_CASE_TPP_TOK_PLUS_PLUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PLUS_PLUS */
#if TPP_HAVE_TPP_TOK_PLUS_EQUAL
	TPP_TOK_PLUS_EQUAL, /* "+=" */
#define _TPP_CASE_TPP_TOK_PLUS_EQUAL case TPP_TOK_PLUS_EQUAL:
#else /* TPP_HAVE_TPP_TOK_PLUS_EQUAL */
#define _TPP_CASE_TPP_TOK_PLUS_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PLUS_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PLUS_MAX),
	TPP_TOK_MC_STARTSWITH_PLUS_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PLUS_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_PLUS(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_PLUS_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_PLUS_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_PLUS \
	_TPP_CASE_TPP_TOK_PLUS_PLUS \
	_TPP_CASE_TPP_TOK_PLUS_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_PLUS */
#define TPP_TOK_MC_STARTSWITH_PLUS(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_PLUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_PLUS */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_MINUS
	TPP_TOK_MC_STARTSWITH_MINUS_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_MINUS_MIN) = TPP_TOK_MC_STARTSWITH_MINUS_MIN - 1,
#if TPP_HAVE_TPP_TOK_MINUS_MINUS
	TPP_TOK_MINUS_MINUS, /* "--" */
#define _TPP_CASE_TPP_TOK_MINUS_MINUS case TPP_TOK_MINUS_MINUS:
#else /* TPP_HAVE_TPP_TOK_MINUS_MINUS */
#define _TPP_CASE_TPP_TOK_MINUS_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_MINUS */
#if TPP_HAVE_TPP_TOK_MINUS_LANGLE
	TPP_TOK_MINUS_LANGLE, /* "-<" */
#define _TPP_CASE_TPP_TOK_MINUS_LANGLE case TPP_TOK_MINUS_LANGLE:
#else /* TPP_HAVE_TPP_TOK_MINUS_LANGLE */
#define _TPP_CASE_TPP_TOK_MINUS_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_LANGLE */
#if TPP_HAVE_TPP_TOK_MINUS_LANGLE_LANGLE
	TPP_TOK_MINUS_LANGLE_LANGLE, /* "-<<" */
#define _TPP_CASE_TPP_TOK_MINUS_LANGLE_LANGLE case TPP_TOK_MINUS_LANGLE_LANGLE:
#else /* TPP_HAVE_TPP_TOK_MINUS_LANGLE_LANGLE */
#define _TPP_CASE_TPP_TOK_MINUS_LANGLE_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE
	TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE, /* "-<<<" */
#define _TPP_CASE_TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE case TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE:
#else /* TPP_HAVE_TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE */
#define _TPP_CASE_TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_MINUS_EQUAL
	TPP_TOK_MINUS_EQUAL, /* "-=" */
#define _TPP_CASE_TPP_TOK_MINUS_EQUAL case TPP_TOK_MINUS_EQUAL:
#else /* TPP_HAVE_TPP_TOK_MINUS_EQUAL */
#define _TPP_CASE_TPP_TOK_MINUS_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_EQUAL */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE
	TPP_TOK_MINUS_RANGLE, /* "->" */
#define _TPP_CASE_TPP_TOK_MINUS_RANGLE case TPP_TOK_MINUS_RANGLE:
#else /* TPP_HAVE_TPP_TOK_MINUS_RANGLE */
#define _TPP_CASE_TPP_TOK_MINUS_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_RANGLE */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR
	TPP_TOK_MINUS_RANGLE_STAR, /* "->*" */
#define _TPP_CASE_TPP_TOK_MINUS_RANGLE_STAR case TPP_TOK_MINUS_RANGLE_STAR:
#else /* TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR */
#define _TPP_CASE_TPP_TOK_MINUS_RANGLE_STAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_RANGLE_STAR */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE_RANGLE
	TPP_TOK_MINUS_RANGLE_RANGLE, /* "->>" */
#define _TPP_CASE_TPP_TOK_MINUS_RANGLE_RANGLE case TPP_TOK_MINUS_RANGLE_RANGLE:
#else /* TPP_HAVE_TPP_TOK_MINUS_RANGLE_RANGLE */
#define _TPP_CASE_TPP_TOK_MINUS_RANGLE_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE
	TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE, /* "->>>" */
#define _TPP_CASE_TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE case TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE:
#else /* TPP_HAVE_TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE */
#define _TPP_CASE_TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_MINUS_MAX),
	TPP_TOK_MC_STARTSWITH_MINUS_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_MINUS_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_MINUS(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_MINUS_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_MINUS_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_MINUS \
	_TPP_CASE_TPP_TOK_MINUS_MINUS \
	_TPP_CASE_TPP_TOK_MINUS_LANGLE \
	_TPP_CASE_TPP_TOK_MINUS_LANGLE_LANGLE \
	_TPP_CASE_TPP_TOK_MINUS_LANGLE_LANGLE_LANGLE \
	_TPP_CASE_TPP_TOK_MINUS_EQUAL \
	_TPP_CASE_TPP_TOK_MINUS_RANGLE \
	_TPP_CASE_TPP_TOK_MINUS_RANGLE_STAR \
	_TPP_CASE_TPP_TOK_MINUS_RANGLE_RANGLE \
	_TPP_CASE_TPP_TOK_MINUS_RANGLE_RANGLE_RANGLE
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_MINUS */
#define TPP_TOK_MC_STARTSWITH_MINUS(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_MINUS */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_DOT
	TPP_TOK_MC_STARTSWITH_DOT_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_DOT_MIN) = TPP_TOK_MC_STARTSWITH_DOT_MIN - 1,
#if TPP_HAVE_TPP_TOK_DOT_STAR
	TPP_TOK_DOT_STAR, /* ".*" */
#define _TPP_CASE_TPP_TOK_DOT_STAR case TPP_TOK_DOT_STAR:
#else /* TPP_HAVE_TPP_TOK_DOT_STAR */
#define _TPP_CASE_TPP_TOK_DOT_STAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_DOT_STAR */
#if TPP_HAVE_TPP_TOK_DOT_DOT
	TPP_TOK_DOT_DOT, /* ".." */
#define _TPP_CASE_TPP_TOK_DOT_DOT case TPP_TOK_DOT_DOT:
#else /* TPP_HAVE_TPP_TOK_DOT_DOT */
#define _TPP_CASE_TPP_TOK_DOT_DOT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_DOT_DOT */
#if TPP_HAVE_TPP_TOK_DOT_DOT_DOT
	TPP_TOK_DOT_DOT_DOT, /* "..." */
#define _TPP_CASE_TPP_TOK_DOT_DOT_DOT case TPP_TOK_DOT_DOT_DOT:
#else /* TPP_HAVE_TPP_TOK_DOT_DOT_DOT */
#define _TPP_CASE_TPP_TOK_DOT_DOT_DOT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_DOT_DOT_DOT */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_DOT_MAX),
	TPP_TOK_MC_STARTSWITH_DOT_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_DOT_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_DOT(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_DOT_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_DOT_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_DOT \
	_TPP_CASE_TPP_TOK_DOT_STAR \
	_TPP_CASE_TPP_TOK_DOT_DOT \
	_TPP_CASE_TPP_TOK_DOT_DOT_DOT
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_DOT */
#define TPP_TOK_MC_STARTSWITH_DOT(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_DOT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_DOT */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_SLASH
	TPP_TOK_MC_STARTSWITH_SLASH_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_SLASH_MIN) = TPP_TOK_MC_STARTSWITH_SLASH_MIN - 1,
#if TPP_HAVE_TPP_TOK_SLASH_SLASH
	TPP_TOK_SLASH_SLASH, /* "//" */
#define _TPP_CASE_TPP_TOK_SLASH_SLASH case TPP_TOK_SLASH_SLASH:
#else /* TPP_HAVE_TPP_TOK_SLASH_SLASH */
#define _TPP_CASE_TPP_TOK_SLASH_SLASH /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SLASH_SLASH */
#if TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL
	TPP_TOK_SLASH_SLASH_EQUAL, /* "//=" */
#define _TPP_CASE_TPP_TOK_SLASH_SLASH_EQUAL case TPP_TOK_SLASH_SLASH_EQUAL:
#else /* TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL */
#define _TPP_CASE_TPP_TOK_SLASH_SLASH_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SLASH_SLASH_EQUAL */
#if TPP_HAVE_TPP_TOK_SLASH_EQUAL
	TPP_TOK_SLASH_EQUAL, /* "/=" */
#define _TPP_CASE_TPP_TOK_SLASH_EQUAL case TPP_TOK_SLASH_EQUAL:
#else /* TPP_HAVE_TPP_TOK_SLASH_EQUAL */
#define _TPP_CASE_TPP_TOK_SLASH_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_SLASH_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_SLASH_MAX),
	TPP_TOK_MC_STARTSWITH_SLASH_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_SLASH_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_SLASH(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_SLASH_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_SLASH_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_SLASH \
	_TPP_CASE_TPP_TOK_SLASH_SLASH \
	_TPP_CASE_TPP_TOK_SLASH_SLASH_EQUAL \
	_TPP_CASE_TPP_TOK_SLASH_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_SLASH */
#define TPP_TOK_MC_STARTSWITH_SLASH(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_SLASH /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_SLASH */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_COLON
	TPP_TOK_MC_STARTSWITH_COLON_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_COLON_MIN) = TPP_TOK_MC_STARTSWITH_COLON_MIN - 1,
#if TPP_HAVE_TPP_TOK_COLON_COLON
	TPP_TOK_COLON_COLON, /* "::" */
#define _TPP_CASE_TPP_TOK_COLON_COLON case TPP_TOK_COLON_COLON:
#else /* TPP_HAVE_TPP_TOK_COLON_COLON */
#define _TPP_CASE_TPP_TOK_COLON_COLON /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_COLON_COLON */
#if TPP_HAVE_TPP_TOK_COLON_EQUAL
	TPP_TOK_COLON_EQUAL, /* ":=" */
#define _TPP_CASE_TPP_TOK_COLON_EQUAL case TPP_TOK_COLON_EQUAL:
#else /* TPP_HAVE_TPP_TOK_COLON_EQUAL */
#define _TPP_CASE_TPP_TOK_COLON_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_COLON_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_COLON_MAX),
	TPP_TOK_MC_STARTSWITH_COLON_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_COLON_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_COLON(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_COLON_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_COLON_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_COLON \
	_TPP_CASE_TPP_TOK_COLON_COLON \
	_TPP_CASE_TPP_TOK_COLON_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_COLON */
#define TPP_TOK_MC_STARTSWITH_COLON(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_COLON /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_COLON */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_LANGLE
	TPP_TOK_MC_STARTSWITH_LANGLE_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_LANGLE_MIN) = TPP_TOK_MC_STARTSWITH_LANGLE_MIN - 1,
#if TPP_HAVE_TPP_TOK_LANGLE_MINUS
	TPP_TOK_LANGLE_MINUS, /* "<-" */
#define _TPP_CASE_TPP_TOK_LANGLE_MINUS case TPP_TOK_LANGLE_MINUS:
#else /* TPP_HAVE_TPP_TOK_LANGLE_MINUS */
#define _TPP_CASE_TPP_TOK_LANGLE_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_LANGLE_MINUS_LANGLE
	TPP_TOK_LANGLE_MINUS_LANGLE, /* "<-<" */
#define _TPP_CASE_TPP_TOK_LANGLE_MINUS_LANGLE case TPP_TOK_LANGLE_MINUS_LANGLE:
#else /* TPP_HAVE_TPP_TOK_LANGLE_MINUS_LANGLE */
#define _TPP_CASE_TPP_TOK_LANGLE_MINUS_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_MINUS_LANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_MINUS_RANGLE
	TPP_TOK_LANGLE_MINUS_RANGLE, /* "<->" */
#define _TPP_CASE_TPP_TOK_LANGLE_MINUS_RANGLE case TPP_TOK_LANGLE_MINUS_RANGLE:
#else /* TPP_HAVE_TPP_TOK_LANGLE_MINUS_RANGLE */
#define _TPP_CASE_TPP_TOK_LANGLE_MINUS_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_MINUS_RANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE
	TPP_TOK_LANGLE_LANGLE, /* "<<" */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE case TPP_TOK_LANGLE_LANGLE:
#else /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_MINUS
	TPP_TOK_LANGLE_LANGLE_MINUS, /* "<<-" */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_MINUS case TPP_TOK_LANGLE_LANGLE_MINUS:
#else /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_MINUS */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_LANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE
	TPP_TOK_LANGLE_LANGLE_LANGLE, /* "<<<" */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE case TPP_TOK_LANGLE_LANGLE_LANGLE:
#else /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS
	TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS, /* "<<<-" */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS case TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS:
#else /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL
	TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL, /* "<<<=" */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL case TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL:
#else /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL
	TPP_TOK_LANGLE_LANGLE_EQUAL, /* "<<=" */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_EQUAL case TPP_TOK_LANGLE_LANGLE_EQUAL:
#else /* TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL */
#define _TPP_CASE_TPP_TOK_LANGLE_LANGLE_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_EQUAL
	TPP_TOK_LANGLE_EQUAL, /* "<=" */
#define _TPP_CASE_TPP_TOK_LANGLE_EQUAL case TPP_TOK_LANGLE_EQUAL:
#else /* TPP_HAVE_TPP_TOK_LANGLE_EQUAL */
#define _TPP_CASE_TPP_TOK_LANGLE_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_LANGLE_EQUAL_LANGLE
	TPP_TOK_LANGLE_EQUAL_LANGLE, /* "<=<" */
#define _TPP_CASE_TPP_TOK_LANGLE_EQUAL_LANGLE case TPP_TOK_LANGLE_EQUAL_LANGLE:
#else /* TPP_HAVE_TPP_TOK_LANGLE_EQUAL_LANGLE */
#define _TPP_CASE_TPP_TOK_LANGLE_EQUAL_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_EQUAL_LANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_EQUAL_RANGLE
	TPP_TOK_LANGLE_EQUAL_RANGLE, /* "<=>" */
#define _TPP_CASE_TPP_TOK_LANGLE_EQUAL_RANGLE case TPP_TOK_LANGLE_EQUAL_RANGLE:
#else /* TPP_HAVE_TPP_TOK_LANGLE_EQUAL_RANGLE */
#define _TPP_CASE_TPP_TOK_LANGLE_EQUAL_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_EQUAL_RANGLE */
#if TPP_HAVE_TPP_TOK_LANGLE_RANGLE
	TPP_TOK_LANGLE_RANGLE, /* "<>" */
#define _TPP_CASE_TPP_TOK_LANGLE_RANGLE case TPP_TOK_LANGLE_RANGLE:
#else /* TPP_HAVE_TPP_TOK_LANGLE_RANGLE */
#define _TPP_CASE_TPP_TOK_LANGLE_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_LANGLE_RANGLE */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_LANGLE_MAX),
	TPP_TOK_MC_STARTSWITH_LANGLE_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_LANGLE_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_LANGLE(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_LANGLE_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_LANGLE_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_LANGLE \
	_TPP_CASE_TPP_TOK_LANGLE_MINUS \
	_TPP_CASE_TPP_TOK_LANGLE_MINUS_LANGLE \
	_TPP_CASE_TPP_TOK_LANGLE_MINUS_RANGLE \
	_TPP_CASE_TPP_TOK_LANGLE_LANGLE \
	_TPP_CASE_TPP_TOK_LANGLE_LANGLE_MINUS \
	_TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE \
	_TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE_MINUS \
	_TPP_CASE_TPP_TOK_LANGLE_LANGLE_LANGLE_EQUAL \
	_TPP_CASE_TPP_TOK_LANGLE_LANGLE_EQUAL \
	_TPP_CASE_TPP_TOK_LANGLE_EQUAL \
	_TPP_CASE_TPP_TOK_LANGLE_EQUAL_LANGLE \
	_TPP_CASE_TPP_TOK_LANGLE_EQUAL_RANGLE \
	_TPP_CASE_TPP_TOK_LANGLE_RANGLE
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_LANGLE */
#define TPP_TOK_MC_STARTSWITH_LANGLE(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_LANGLE */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_EQUAL
	TPP_TOK_MC_STARTSWITH_EQUAL_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_EQUAL_MIN) = TPP_TOK_MC_STARTSWITH_EQUAL_MIN - 1,
#if TPP_HAVE_TPP_TOK_EQUAL_EXCLAIM
	TPP_TOK_EQUAL_EXCLAIM, /* "=!" */
#define _TPP_CASE_TPP_TOK_EQUAL_EXCLAIM case TPP_TOK_EQUAL_EXCLAIM:
#else /* TPP_HAVE_TPP_TOK_EQUAL_EXCLAIM */
#define _TPP_CASE_TPP_TOK_EQUAL_EXCLAIM /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_EXCLAIM */
#if TPP_HAVE_TPP_TOK_EQUAL_PERCENT
	TPP_TOK_EQUAL_PERCENT, /* "=%" */
#define _TPP_CASE_TPP_TOK_EQUAL_PERCENT case TPP_TOK_EQUAL_PERCENT:
#else /* TPP_HAVE_TPP_TOK_EQUAL_PERCENT */
#define _TPP_CASE_TPP_TOK_EQUAL_PERCENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_PERCENT */
#if TPP_HAVE_TPP_TOK_EQUAL_PERCENT_PERCENT
	TPP_TOK_EQUAL_PERCENT_PERCENT, /* "=%%" */
#define _TPP_CASE_TPP_TOK_EQUAL_PERCENT_PERCENT case TPP_TOK_EQUAL_PERCENT_PERCENT:
#else /* TPP_HAVE_TPP_TOK_EQUAL_PERCENT_PERCENT */
#define _TPP_CASE_TPP_TOK_EQUAL_PERCENT_PERCENT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_PERCENT_PERCENT */
#if TPP_HAVE_TPP_TOK_EQUAL_AMP
	TPP_TOK_EQUAL_AMP, /* "=&" */
#define _TPP_CASE_TPP_TOK_EQUAL_AMP case TPP_TOK_EQUAL_AMP:
#else /* TPP_HAVE_TPP_TOK_EQUAL_AMP */
#define _TPP_CASE_TPP_TOK_EQUAL_AMP /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_AMP */
#if TPP_HAVE_TPP_TOK_EQUAL_STAR
	TPP_TOK_EQUAL_STAR, /* "=*" */
#define _TPP_CASE_TPP_TOK_EQUAL_STAR case TPP_TOK_EQUAL_STAR:
#else /* TPP_HAVE_TPP_TOK_EQUAL_STAR */
#define _TPP_CASE_TPP_TOK_EQUAL_STAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_STAR */
#if TPP_HAVE_TPP_TOK_EQUAL_STAR_STAR
	TPP_TOK_EQUAL_STAR_STAR, /* "=**" */
#define _TPP_CASE_TPP_TOK_EQUAL_STAR_STAR case TPP_TOK_EQUAL_STAR_STAR:
#else /* TPP_HAVE_TPP_TOK_EQUAL_STAR_STAR */
#define _TPP_CASE_TPP_TOK_EQUAL_STAR_STAR /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_STAR_STAR */
#if TPP_HAVE_TPP_TOK_EQUAL_PLUS
	TPP_TOK_EQUAL_PLUS, /* "=+" */
#define _TPP_CASE_TPP_TOK_EQUAL_PLUS case TPP_TOK_EQUAL_PLUS:
#else /* TPP_HAVE_TPP_TOK_EQUAL_PLUS */
#define _TPP_CASE_TPP_TOK_EQUAL_PLUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_PLUS */
#if TPP_HAVE_TPP_TOK_EQUAL_MINUS
	TPP_TOK_EQUAL_MINUS, /* "=-" */
#define _TPP_CASE_TPP_TOK_EQUAL_MINUS case TPP_TOK_EQUAL_MINUS:
#else /* TPP_HAVE_TPP_TOK_EQUAL_MINUS */
#define _TPP_CASE_TPP_TOK_EQUAL_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_MINUS */
#if TPP_HAVE_TPP_TOK_EQUAL_SLASH
	TPP_TOK_EQUAL_SLASH, /* "=/" */
#define _TPP_CASE_TPP_TOK_EQUAL_SLASH case TPP_TOK_EQUAL_SLASH:
#else /* TPP_HAVE_TPP_TOK_EQUAL_SLASH */
#define _TPP_CASE_TPP_TOK_EQUAL_SLASH /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_SLASH */
#if TPP_HAVE_TPP_TOK_EQUAL_SLASH_SLASH
	TPP_TOK_EQUAL_SLASH_SLASH, /* "=//" */
#define _TPP_CASE_TPP_TOK_EQUAL_SLASH_SLASH case TPP_TOK_EQUAL_SLASH_SLASH:
#else /* TPP_HAVE_TPP_TOK_EQUAL_SLASH_SLASH */
#define _TPP_CASE_TPP_TOK_EQUAL_SLASH_SLASH /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_SLASH_SLASH */
#if TPP_HAVE_TPP_TOK_EQUAL_COLON
	TPP_TOK_EQUAL_COLON, /* "=:" */
#define _TPP_CASE_TPP_TOK_EQUAL_COLON case TPP_TOK_EQUAL_COLON:
#else /* TPP_HAVE_TPP_TOK_EQUAL_COLON */
#define _TPP_CASE_TPP_TOK_EQUAL_COLON /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_COLON */
#if TPP_HAVE_TPP_TOK_EQUAL_LANGLE
	TPP_TOK_EQUAL_LANGLE, /* "=<" */
#define _TPP_CASE_TPP_TOK_EQUAL_LANGLE case TPP_TOK_EQUAL_LANGLE:
#else /* TPP_HAVE_TPP_TOK_EQUAL_LANGLE */
#define _TPP_CASE_TPP_TOK_EQUAL_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_LANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE
	TPP_TOK_EQUAL_LANGLE_LANGLE, /* "=<<" */
#define _TPP_CASE_TPP_TOK_EQUAL_LANGLE_LANGLE case TPP_TOK_EQUAL_LANGLE_LANGLE:
#else /* TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE */
#define _TPP_CASE_TPP_TOK_EQUAL_LANGLE_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE
	TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE, /* "=<<<" */
#define _TPP_CASE_TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE case TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE:
#else /* TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE */
#define _TPP_CASE_TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL
	TPP_TOK_EQUAL_EQUAL, /* "==" */
#define _TPP_CASE_TPP_TOK_EQUAL_EQUAL case TPP_TOK_EQUAL_EQUAL:
#else /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL */
#define _TPP_CASE_TPP_TOK_EQUAL_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EXCLAIM
	TPP_TOK_EQUAL_EQUAL_EXCLAIM, /* "==!" */
#define _TPP_CASE_TPP_TOK_EQUAL_EQUAL_EXCLAIM case TPP_TOK_EQUAL_EQUAL_EXCLAIM:
#else /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EXCLAIM */
#define _TPP_CASE_TPP_TOK_EQUAL_EQUAL_EXCLAIM /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EXCLAIM */
#if TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL
	TPP_TOK_EQUAL_EQUAL_EQUAL, /* "===" */
#define _TPP_CASE_TPP_TOK_EQUAL_EQUAL_EQUAL case TPP_TOK_EQUAL_EQUAL_EQUAL:
#else /* TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL */
#define _TPP_CASE_TPP_TOK_EQUAL_EQUAL_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_EQUAL_EQUAL */
#if TPP_HAVE_TPP_TOK_EQUAL_RANGLE
	TPP_TOK_EQUAL_RANGLE, /* "=>" */
#define _TPP_CASE_TPP_TOK_EQUAL_RANGLE case TPP_TOK_EQUAL_RANGLE:
#else /* TPP_HAVE_TPP_TOK_EQUAL_RANGLE */
#define _TPP_CASE_TPP_TOK_EQUAL_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE
	TPP_TOK_EQUAL_RANGLE_RANGLE, /* "=>>" */
#define _TPP_CASE_TPP_TOK_EQUAL_RANGLE_RANGLE case TPP_TOK_EQUAL_RANGLE_RANGLE:
#else /* TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE */
#define _TPP_CASE_TPP_TOK_EQUAL_RANGLE_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE
	TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE, /* "=>>>" */
#define _TPP_CASE_TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE case TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE:
#else /* TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE */
#define _TPP_CASE_TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_EQUAL_QMARK
	TPP_TOK_EQUAL_QMARK, /* "=?" */
#define _TPP_CASE_TPP_TOK_EQUAL_QMARK case TPP_TOK_EQUAL_QMARK:
#else /* TPP_HAVE_TPP_TOK_EQUAL_QMARK */
#define _TPP_CASE_TPP_TOK_EQUAL_QMARK /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_QMARK */
#if TPP_HAVE_TPP_TOK_EQUAL_AT
	TPP_TOK_EQUAL_AT, /* "=@" */
#define _TPP_CASE_TPP_TOK_EQUAL_AT case TPP_TOK_EQUAL_AT:
#else /* TPP_HAVE_TPP_TOK_EQUAL_AT */
#define _TPP_CASE_TPP_TOK_EQUAL_AT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_AT */
#if TPP_HAVE_TPP_TOK_EQUAL_AT_AT
	TPP_TOK_EQUAL_AT_AT, /* "=@@" */
#define _TPP_CASE_TPP_TOK_EQUAL_AT_AT case TPP_TOK_EQUAL_AT_AT:
#else /* TPP_HAVE_TPP_TOK_EQUAL_AT_AT */
#define _TPP_CASE_TPP_TOK_EQUAL_AT_AT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_AT_AT */
#if TPP_HAVE_TPP_TOK_EQUAL_HAT
	TPP_TOK_EQUAL_HAT, /* "=^" */
#define _TPP_CASE_TPP_TOK_EQUAL_HAT case TPP_TOK_EQUAL_HAT:
#else /* TPP_HAVE_TPP_TOK_EQUAL_HAT */
#define _TPP_CASE_TPP_TOK_EQUAL_HAT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_HAT */
#if TPP_HAVE_TPP_TOK_EQUAL_PIPE
	TPP_TOK_EQUAL_PIPE, /* "=|" */
#define _TPP_CASE_TPP_TOK_EQUAL_PIPE case TPP_TOK_EQUAL_PIPE:
#else /* TPP_HAVE_TPP_TOK_EQUAL_PIPE */
#define _TPP_CASE_TPP_TOK_EQUAL_PIPE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_PIPE */
#if TPP_HAVE_TPP_TOK_EQUAL_TILDE
	TPP_TOK_EQUAL_TILDE, /* "=~" */
#define _TPP_CASE_TPP_TOK_EQUAL_TILDE case TPP_TOK_EQUAL_TILDE:
#else /* TPP_HAVE_TPP_TOK_EQUAL_TILDE */
#define _TPP_CASE_TPP_TOK_EQUAL_TILDE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_EQUAL_TILDE */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_EQUAL_MAX),
	TPP_TOK_MC_STARTSWITH_EQUAL_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_EQUAL_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_EQUAL(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_EQUAL_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_EQUAL_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_EQUAL \
	_TPP_CASE_TPP_TOK_EQUAL_EXCLAIM \
	_TPP_CASE_TPP_TOK_EQUAL_PERCENT \
	_TPP_CASE_TPP_TOK_EQUAL_PERCENT_PERCENT \
	_TPP_CASE_TPP_TOK_EQUAL_AMP \
	_TPP_CASE_TPP_TOK_EQUAL_STAR \
	_TPP_CASE_TPP_TOK_EQUAL_STAR_STAR \
	_TPP_CASE_TPP_TOK_EQUAL_PLUS \
	_TPP_CASE_TPP_TOK_EQUAL_MINUS \
	_TPP_CASE_TPP_TOK_EQUAL_SLASH \
	_TPP_CASE_TPP_TOK_EQUAL_SLASH_SLASH \
	_TPP_CASE_TPP_TOK_EQUAL_COLON \
	_TPP_CASE_TPP_TOK_EQUAL_LANGLE \
	_TPP_CASE_TPP_TOK_EQUAL_LANGLE_LANGLE \
	_TPP_CASE_TPP_TOK_EQUAL_LANGLE_LANGLE_LANGLE \
	_TPP_CASE_TPP_TOK_EQUAL_EQUAL \
	_TPP_CASE_TPP_TOK_EQUAL_EQUAL_EXCLAIM \
	_TPP_CASE_TPP_TOK_EQUAL_EQUAL_EQUAL \
	_TPP_CASE_TPP_TOK_EQUAL_RANGLE \
	_TPP_CASE_TPP_TOK_EQUAL_RANGLE_RANGLE \
	_TPP_CASE_TPP_TOK_EQUAL_RANGLE_RANGLE_RANGLE \
	_TPP_CASE_TPP_TOK_EQUAL_QMARK \
	_TPP_CASE_TPP_TOK_EQUAL_AT \
	_TPP_CASE_TPP_TOK_EQUAL_AT_AT \
	_TPP_CASE_TPP_TOK_EQUAL_HAT \
	_TPP_CASE_TPP_TOK_EQUAL_PIPE \
	_TPP_CASE_TPP_TOK_EQUAL_TILDE
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_EQUAL */
#define TPP_TOK_MC_STARTSWITH_EQUAL(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_EQUAL */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_RANGLE
	TPP_TOK_MC_STARTSWITH_RANGLE_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_RANGLE_MIN) = TPP_TOK_MC_STARTSWITH_RANGLE_MIN - 1,
#if TPP_HAVE_TPP_TOK_RANGLE_MINUS
	TPP_TOK_RANGLE_MINUS, /* ">-" */
#define _TPP_CASE_TPP_TOK_RANGLE_MINUS case TPP_TOK_RANGLE_MINUS:
#else /* TPP_HAVE_TPP_TOK_RANGLE_MINUS */
#define _TPP_CASE_TPP_TOK_RANGLE_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_RANGLE_MINUS_LANGLE
	TPP_TOK_RANGLE_MINUS_LANGLE, /* ">-<" */
#define _TPP_CASE_TPP_TOK_RANGLE_MINUS_LANGLE case TPP_TOK_RANGLE_MINUS_LANGLE:
#else /* TPP_HAVE_TPP_TOK_RANGLE_MINUS_LANGLE */
#define _TPP_CASE_TPP_TOK_RANGLE_MINUS_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_MINUS_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_MINUS_RANGLE
	TPP_TOK_RANGLE_MINUS_RANGLE, /* ">->" */
#define _TPP_CASE_TPP_TOK_RANGLE_MINUS_RANGLE case TPP_TOK_RANGLE_MINUS_RANGLE:
#else /* TPP_HAVE_TPP_TOK_RANGLE_MINUS_RANGLE */
#define _TPP_CASE_TPP_TOK_RANGLE_MINUS_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_MINUS_RANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_LANGLE
	TPP_TOK_RANGLE_LANGLE, /* "><" */
#define _TPP_CASE_TPP_TOK_RANGLE_LANGLE case TPP_TOK_RANGLE_LANGLE:
#else /* TPP_HAVE_TPP_TOK_RANGLE_LANGLE */
#define _TPP_CASE_TPP_TOK_RANGLE_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_EQUAL
	TPP_TOK_RANGLE_EQUAL, /* ">=" */
#define _TPP_CASE_TPP_TOK_RANGLE_EQUAL case TPP_TOK_RANGLE_EQUAL:
#else /* TPP_HAVE_TPP_TOK_RANGLE_EQUAL */
#define _TPP_CASE_TPP_TOK_RANGLE_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_EQUAL_LANGLE
	TPP_TOK_RANGLE_EQUAL_LANGLE, /* ">=<" */
#define _TPP_CASE_TPP_TOK_RANGLE_EQUAL_LANGLE case TPP_TOK_RANGLE_EQUAL_LANGLE:
#else /* TPP_HAVE_TPP_TOK_RANGLE_EQUAL_LANGLE */
#define _TPP_CASE_TPP_TOK_RANGLE_EQUAL_LANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_EQUAL_LANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_EQUAL_RANGLE
	TPP_TOK_RANGLE_EQUAL_RANGLE, /* ">=>" */
#define _TPP_CASE_TPP_TOK_RANGLE_EQUAL_RANGLE case TPP_TOK_RANGLE_EQUAL_RANGLE:
#else /* TPP_HAVE_TPP_TOK_RANGLE_EQUAL_RANGLE */
#define _TPP_CASE_TPP_TOK_RANGLE_EQUAL_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_EQUAL_RANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE
	TPP_TOK_RANGLE_RANGLE, /* ">>" */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE case TPP_TOK_RANGLE_RANGLE:
#else /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_MINUS
	TPP_TOK_RANGLE_RANGLE_MINUS, /* ">>-" */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_MINUS case TPP_TOK_RANGLE_RANGLE_MINUS:
#else /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_MINUS */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_RANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL
	TPP_TOK_RANGLE_RANGLE_EQUAL, /* ">>=" */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_EQUAL case TPP_TOK_RANGLE_RANGLE_EQUAL:
#else /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_RANGLE_EQUAL */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE
	TPP_TOK_RANGLE_RANGLE_RANGLE, /* ">>>" */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE case TPP_TOK_RANGLE_RANGLE_RANGLE:
#else /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS
	TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS, /* ">>>-" */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS case TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS:
#else /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS */
#if TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL
	TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL, /* ">>>=" */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL case TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL:
#else /* TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL */
#define _TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_RANGLE_MAX),
	TPP_TOK_MC_STARTSWITH_RANGLE_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_RANGLE_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_RANGLE(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_RANGLE_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_RANGLE_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_RANGLE \
	_TPP_CASE_TPP_TOK_RANGLE_MINUS \
	_TPP_CASE_TPP_TOK_RANGLE_MINUS_LANGLE \
	_TPP_CASE_TPP_TOK_RANGLE_MINUS_RANGLE \
	_TPP_CASE_TPP_TOK_RANGLE_LANGLE \
	_TPP_CASE_TPP_TOK_RANGLE_EQUAL \
	_TPP_CASE_TPP_TOK_RANGLE_EQUAL_LANGLE \
	_TPP_CASE_TPP_TOK_RANGLE_EQUAL_RANGLE \
	_TPP_CASE_TPP_TOK_RANGLE_RANGLE \
	_TPP_CASE_TPP_TOK_RANGLE_RANGLE_MINUS \
	_TPP_CASE_TPP_TOK_RANGLE_RANGLE_EQUAL \
	_TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE \
	_TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE_MINUS \
	_TPP_CASE_TPP_TOK_RANGLE_RANGLE_RANGLE_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_RANGLE */
#define TPP_TOK_MC_STARTSWITH_RANGLE(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_RANGLE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_RANGLE */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_QMARK
	TPP_TOK_MC_STARTSWITH_QMARK_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_QMARK_MIN) = TPP_TOK_MC_STARTSWITH_QMARK_MIN - 1,
#if TPP_HAVE_TPP_TOK_QMARK_EQUAL
	TPP_TOK_QMARK_EQUAL, /* "?=" */
#define _TPP_CASE_TPP_TOK_QMARK_EQUAL case TPP_TOK_QMARK_EQUAL:
#else /* TPP_HAVE_TPP_TOK_QMARK_EQUAL */
#define _TPP_CASE_TPP_TOK_QMARK_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_QMARK_EQUAL */
#if TPP_HAVE_TPP_TOK_QMARK_QMARK
	TPP_TOK_QMARK_QMARK, /* "??" */
#define _TPP_CASE_TPP_TOK_QMARK_QMARK case TPP_TOK_QMARK_QMARK:
#else /* TPP_HAVE_TPP_TOK_QMARK_QMARK */
#define _TPP_CASE_TPP_TOK_QMARK_QMARK /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_QMARK_QMARK */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_QMARK_MAX),
	TPP_TOK_MC_STARTSWITH_QMARK_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_QMARK_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_QMARK(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_QMARK_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_QMARK_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_QMARK \
	_TPP_CASE_TPP_TOK_QMARK_EQUAL \
	_TPP_CASE_TPP_TOK_QMARK_QMARK
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_QMARK */
#define TPP_TOK_MC_STARTSWITH_QMARK(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_QMARK /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_QMARK */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_AT
	TPP_TOK_MC_STARTSWITH_AT_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_AT_MIN) = TPP_TOK_MC_STARTSWITH_AT_MIN - 1,
#if TPP_HAVE_TPP_TOK_AT_EQUAL
	TPP_TOK_AT_EQUAL, /* "@=" */
#define _TPP_CASE_TPP_TOK_AT_EQUAL case TPP_TOK_AT_EQUAL:
#else /* TPP_HAVE_TPP_TOK_AT_EQUAL */
#define _TPP_CASE_TPP_TOK_AT_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_AT_EQUAL */
#if TPP_HAVE_TPP_TOK_AT_AT
	TPP_TOK_AT_AT, /* "@@" */
#define _TPP_CASE_TPP_TOK_AT_AT case TPP_TOK_AT_AT:
#else /* TPP_HAVE_TPP_TOK_AT_AT */
#define _TPP_CASE_TPP_TOK_AT_AT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_AT_AT */
#if TPP_HAVE_TPP_TOK_AT_AT_EQUAL
	TPP_TOK_AT_AT_EQUAL, /* "@@=" */
#define _TPP_CASE_TPP_TOK_AT_AT_EQUAL case TPP_TOK_AT_AT_EQUAL:
#else /* TPP_HAVE_TPP_TOK_AT_AT_EQUAL */
#define _TPP_CASE_TPP_TOK_AT_AT_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_AT_AT_EQUAL */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_AT_MAX),
	TPP_TOK_MC_STARTSWITH_AT_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_AT_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_AT(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_AT_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_AT_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_AT \
	_TPP_CASE_TPP_TOK_AT_EQUAL \
	_TPP_CASE_TPP_TOK_AT_AT \
	_TPP_CASE_TPP_TOK_AT_AT_EQUAL
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_AT */
#define TPP_TOK_MC_STARTSWITH_AT(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_AT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_AT */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_HAT
	TPP_TOK_MC_STARTSWITH_HAT_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_HAT_MIN) = TPP_TOK_MC_STARTSWITH_HAT_MIN - 1,
#if TPP_HAVE_TPP_TOK_HAT_EQUAL
	TPP_TOK_HAT_EQUAL, /* "^=" */
#define _TPP_CASE_TPP_TOK_HAT_EQUAL case TPP_TOK_HAT_EQUAL:
#else /* TPP_HAVE_TPP_TOK_HAT_EQUAL */
#define _TPP_CASE_TPP_TOK_HAT_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_HAT_EQUAL */
#if TPP_HAVE_TPP_TOK_HAT_HAT
	TPP_TOK_HAT_HAT, /* "^^" */
#define _TPP_CASE_TPP_TOK_HAT_HAT case TPP_TOK_HAT_HAT:
#else /* TPP_HAVE_TPP_TOK_HAT_HAT */
#define _TPP_CASE_TPP_TOK_HAT_HAT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_HAT_HAT */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_HAT_MAX),
	TPP_TOK_MC_STARTSWITH_HAT_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_HAT_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_HAT(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_HAT_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_HAT_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_HAT \
	_TPP_CASE_TPP_TOK_HAT_EQUAL \
	_TPP_CASE_TPP_TOK_HAT_HAT
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_HAT */
#define TPP_TOK_MC_STARTSWITH_HAT(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_HAT /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_HAT */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_PIPE
	TPP_TOK_MC_STARTSWITH_PIPE_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PIPE_MIN) = TPP_TOK_MC_STARTSWITH_PIPE_MIN - 1,
#if TPP_HAVE_TPP_TOK_PIPE_EQUAL
	TPP_TOK_PIPE_EQUAL, /* "|=" */
#define _TPP_CASE_TPP_TOK_PIPE_EQUAL case TPP_TOK_PIPE_EQUAL:
#else /* TPP_HAVE_TPP_TOK_PIPE_EQUAL */
#define _TPP_CASE_TPP_TOK_PIPE_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PIPE_EQUAL */
#if TPP_HAVE_TPP_TOK_PIPE_PIPE
	TPP_TOK_PIPE_PIPE, /* "||" */
#define _TPP_CASE_TPP_TOK_PIPE_PIPE case TPP_TOK_PIPE_PIPE:
#else /* TPP_HAVE_TPP_TOK_PIPE_PIPE */
#define _TPP_CASE_TPP_TOK_PIPE_PIPE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_PIPE_PIPE */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PIPE_MAX),
	TPP_TOK_MC_STARTSWITH_PIPE_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_PIPE_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_PIPE(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_PIPE_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_PIPE_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_PIPE \
	_TPP_CASE_TPP_TOK_PIPE_EQUAL \
	_TPP_CASE_TPP_TOK_PIPE_PIPE
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_PIPE */
#define TPP_TOK_MC_STARTSWITH_PIPE(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_PIPE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_PIPE */

#if TPP_HAVE_TPP_TOK_MC_STARTSWITH_TILDE
	TPP_TOK_MC_STARTSWITH_TILDE_MIN,
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_TILDE_MIN) = TPP_TOK_MC_STARTSWITH_TILDE_MIN - 1,
#if TPP_HAVE_TPP_TOK_TILDE_EQUAL
	TPP_TOK_TILDE_EQUAL, /* "~=" */
#define _TPP_CASE_TPP_TOK_TILDE_EQUAL case TPP_TOK_TILDE_EQUAL:
#else /* TPP_HAVE_TPP_TOK_TILDE_EQUAL */
#define _TPP_CASE_TPP_TOK_TILDE_EQUAL /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_TILDE_EQUAL */
#if TPP_HAVE_TPP_TOK_TILDE_TILDE
	TPP_TOK_TILDE_TILDE, /* "~~" */
#define _TPP_CASE_TPP_TOK_TILDE_TILDE case TPP_TOK_TILDE_TILDE:
#else /* TPP_HAVE_TPP_TOK_TILDE_TILDE */
#define _TPP_CASE_TPP_TOK_TILDE_TILDE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_TILDE_TILDE */
	TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_TILDE_MAX),
	TPP_TOK_MC_STARTSWITH_TILDE_MAX = TPP_INTERNAL(_TPP_TOK_MC_STARTSWITH_TILDE_MAX) - 1,
#define TPP_TOK_MC_STARTSWITH_TILDE(id)                   \
	((int)(id) >= (int)TPP_TOK_MC_STARTSWITH_TILDE_MIN && \
	 (int)(id) <= (int)TPP_TOK_MC_STARTSWITH_TILDE_MAX)
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_TILDE \
	_TPP_CASE_TPP_TOK_TILDE_EQUAL \
	_TPP_CASE_TPP_TOK_TILDE_TILDE
#else /* TPP_HAVE_TPP_TOK_MC_STARTSWITH_TILDE */
#define TPP_TOK_MC_STARTSWITH_TILDE(id)      0
#define TPP_CASE_TPP_TOK_MC_STARTSWITH_TILDE /* nothing */
#endif /* !TPP_HAVE_TPP_TOK_MC_STARTSWITH_TILDE */
/*[[[end]]]*/

	TPP_TOK_MULTICHAR_END, /* KEEP THIS THE LAST MULTICHAR TOKEN! */
	TPP_TOK_KEYWORD_BEGIN = TPP_TOK_MULTICHAR_END, /* First builtin keyword */
	TPP_INTERNAL(_TPP_TOK_KEYWORD_BEGIN) = TPP_TOK_KEYWORD_BEGIN - 1,
#undef GUARD_TPP_AMALGAMATION_H
#define TPP_DEFS
#define TPP_KWD(id, string) id,
#include TPP_CONFIG_DEFS_FILENAME
#undef TPP_DEFS
#if TPP_HAVE_USER_KEYWORDS
	TPP_TOK_USERKEYWORD_BEGIN, /* First user-defined (non-builtin) keyword */
#else /* TPP_HAVE_USER_KEYWORDS */
	TPP_TOK_USERKEYWORD, /* Some user-defined (non-builtin) keyword */
#endif /* !TPP_HAVE_USER_KEYWORDS */
} tpp_token_id;

/* Helper macros to easily detect certain types of whitespace. */
#define TPP_TOK_ISSPACE_OR_COMMENT(id)              ((id) == TPP_TOK_SPACE || TPP_TOK_ISCOMMENT_NOLINE(id))
#define TPP_TOK_ISLF_OR_COMMENT(id)                 ((id) == TPP_TOK_LF || TPP_TOK_ISCOMMENT_LINE(id))
#define TPP_TOK_ISSPACE_OR_LF_OR_COMMENT(id)        ((id) == TPP_TOK_SPACE || (id) == TPP_TOK_LF || TPP_TOK_ISCOMMENT(id))
#define TPP_TOK_ISLF_OR_COMMENT_OR_EOF(id)          ((id) == TPP_TOK_LF || TPP_TOK_ISCOMMENT_LINE(id) || (id) == TPP_TOK_EOF)
#define TPP_TOK_ISSPACE_OR_LF_OR_COMMENT_OR_EOF(id) ((id) == TPP_TOK_SPACE || (id) == TPP_TOK_LF || TPP_TOK_ISCOMMENT(id) || (id) == TPP_TOK_EOF)


/* Helper macros to determine which (and what kind of) keyword is described by a given `id' */
#define TPP_TOK_ISKEYWORD(id)        ((int)(id) >= (int)TPP_TOK_KEYWORD_BEGIN)
#if TPP_HAVE_USER_KEYWORDS
#define TPP_TOK_ISUSERKEYWORD(id)    ((int)(id) >= (int)TPP_TOK_USERKEYWORD_BEGIN)
#else /* TPP_HAVE_USER_KEYWORDS */
#define TPP_TOK_ISUSERKEYWORD(id)    ((id) == TPP_TOK_USERKEYWORD)
#endif /* !TPP_HAVE_USER_KEYWORDS */
#define TPP_TOK_ISBUILTINKEYWORD(id) (TPP_TOK_ISKEYWORD(id) && !TPP_TOK_ISUSERKEYWORD(id))

#if TPP_HAVE_STRTOKENID
/* Returns the "*" in "TPP_TOK_*" of "id", which must be a (non-keyword and non-error) token ID
 * >> printf("%s\n", tpp_strtokenid(TPP_TOK_EQUAL_EQUAL));  // "EQUAL_EQUAL"
 * >> printf("%s\n", tpp_reprtokenid(TPP_TOK_EQUAL_EQUAL)); // "==" */
TPP_DECL TPP_WUNUSED char const *TPPCALL tpp_strtokenid(tpp_token_id id);
#else /* TPP_HAVE_STRTOKENID */
#define tpp_strtokenid(id) ((char const *)NULL)
#endif /* !TPP_HAVE_STRTOKENID */

#if TPP_HAVE_REPRTOKENID
/* Similar to `tpp_strtokenid()', but returns a (canonical) representation of "id":
 * >> printf("%s\n", tpp_strtokenid(TPP_TOK_EQUAL_EQUAL));  // "EQUAL_EQUAL"
 * >> printf("%s\n", tpp_reprtokenid(TPP_TOK_EQUAL_EQUAL)); // "==" */
TPP_DECL TPP_WUNUSED char const *TPPCALL tpp_reprtokenid(tpp_token_id id);
#else /* TPP_HAVE_STRTOKENID */
#define tpp_reprtokenid(id) ((char const *)NULL)
#endif /* !TPP_HAVE_REPRTOKENID */

struct tpp_keyword;
typedef struct tpp_token {
	tpp_token_id              TPP_INTERNAL(tt_id);    /* Token ID (never set to one of `TPP_TOK_E*'; iow: always positive or TPP_TOK_EOF) */
	struct tpp_keyword const *TPP_INTERNAL(tt_kwd);   /* [1..1][valid_if(tpp_token_haskwd(self))] Keyword identified by `tt_id' */
	tpp_char const           *TPP_INTERNAL(tt_start); /* [1..1][>= tt_chunk->ts_str && <= tt_end] Token start pointer */
	tpp_char const           *TPP_INTERNAL(tt_end);   /* [1..1][>= tt_start && <= tt_chunk->ts_str+tt_chunk->ts_len] Token end pointer */
	TPP_REF tpp_string       *TPP_INTERNAL(tt_chunk); /* [0..1] Text chunk containing "tt_start" and "tt_end" (or "NULL" if not needed) */
} tpp_token;

/* Public API */
#define tpp_token_move(self, from) \
	(void)(*(self) = *(from), tpp_dbg_memset(from, sizeof(tpp_token)))
#define tpp_token_copy(self, from)              \
	(void)(*(self) = *(from),                   \
	       !((self)->TPP_INTERNAL(tt_chunk)) || \
	       (tpp_string_incref((self)->TPP_INTERNAL(tt_chunk)), 1))
#define tpp_token_fini(self)                                       \
	(void)(!((self)->TPP_INTERNAL(tt_chunk)) ||                    \
	       (tpp_string_decref((self)->TPP_INTERNAL(tt_chunk)), 1), \
	       tpp_dbg_memset(self, sizeof(tpp_token)))
#if TPP_HAVE_USER_KEYWORDS
#define tpp_token_haskwd(self)     TPP_TOK_ISKEYWORD(tpp_token_getid(self))
#else /* TPP_HAVE_USER_KEYWORDS */
#define tpp_token_haskwd(self)     TPP_TOK_ISBUILTINKEYWORD(tpp_token_getid(self))
#endif /* !TPP_HAVE_USER_KEYWORDS */
#define tpp_token_getid(self)      ((self)->TPP_INTERNAL(tt_id))
#define tpp_token_getkwd(self)     ((self)->TPP_INTERNAL(tt_kwd)) /* Only valid when "tpp_token_haskwd(self)" */
#define tpp_token_getstart(self)   ((self)->TPP_INTERNAL(tt_start))
#define tpp_token_getend(self)     ((self)->TPP_INTERNAL(tt_end))
#define tpp_token_getlen(self)     ((tpp_size)(tpp_token_getend(self) - tpp_token_getstart(self)))
#define tpp_token_getkwdcstr(self) tpp_keyword_getcstr(tpp_token_getkwd(self))

/* Helpers to set the data-fields of "self" */
#define tpp_token_setid(self, id) \
	(void)((self)->TPP_INTERNAL(tt_id) = (id))
#define tpp_token_setkwd(self, kwd) \
	(void)((self)->TPP_INTERNAL(tt_id) = ((self)->TPP_INTERNAL(tt_kwd) = (kwd))->TPP_INTERNAL(tk_id))

/* Set the text-range of the token.
 * WARNING: When used on tpp_lexer_gettoken(), the given "end" pointer
 *          also specifies where the next call to tpp_lexer_yield() will
 *          start scanning for tokens! */
#define tpp_token_setrange(self, start, end)         \
	(void)((self)->TPP_INTERNAL(tt_start) = (start), \
	       (self)->TPP_INTERNAL(tt_end)   = (end))

/* Convenience aliases */
#define tpp_token_iseof(self)                    (tpp_token_getid(self) == TPP_TOK_EOF)
#define tpp_token_isspace_or_comment(self)       TPP_TOK_ISSPACE_OR_COMMENT(tpp_token_getid(self))
#define tpp_token_islf_or_comment(self)          TPP_TOK_ISLF_OR_COMMENT(tpp_token_getid(self))
#define tpp_token_isspace_or_lf_or_comment(self) TPP_TOK_ISSPACE_OR_LF_OR_COMMENT(tpp_token_getid(self))
#define tpp_token_iskeyword(self)                TPP_TOK_ISKEYWORD(tpp_token_getid(self))
#define tpp_token_isuserkeyword(self)            TPP_TOK_ISUSERKEYWORD(tpp_token_getid(self))
#define tpp_token_isbuiltinkeyword(self)         TPP_TOK_ISBUILTINKEYWORD(tpp_token_getid(self))
#define tpp_token_iscomment(self)                TPP_TOK_ISCOMMENT(tpp_token_getid(self))
#define tpp_token_iscomment_line(self)           TPP_TOK_ISCOMMENT_LINE(tpp_token_getid(self))
#define tpp_token_iscomment_noline(self)         TPP_TOK_ISCOMMENT_NOLINE(tpp_token_getid(self))
#define tpp_token_isstring(self)                 TPP_TOK_ISSTRING(tpp_token_getid(self))


#if TPP_HAVE_TOKEN_ENCODESTRING
/* \-encode "data...+=num_bytes" by passing it to "printer"
 * NOTE: Leading/trailing " (or ')-characters are *NOT* printed!
 *
 * @return: >= 0: Sum of positive return values of "printer"
 * @return: < 0:  First negative return value of "printer".
 *                Note that this function never causes errors
 *                on its own, meaning that the meaning of
 *                *all* negative values is entirely up to the
 *                given "printer"! */
TPP_DECL /*TPP_WUNUSED*/ TPP_NONNULL((1)) tpp_ssize TPPCALL
tpp_token_encodestring(tpp_formatprinter printer, void *arg,
                       void const *data, tpp_size num_bytes);
#endif /* TPP_HAVE_TOKEN_ENCODESTRING */

TPP_DECL_END
/*[[[tpp-end]]]*/

#endif /* !GUARD_TPP_TOKEN_H */
