
../ctype-unicode.c: ctype.dee UnicodeData.txt DerivedCoreProperties.txt
	deemon ctype.dee

UnicodeData.txt:
	wget https://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt
DerivedCoreProperties.txt:
	wget https://ftp.unicode.org/Public/UNIDATA/DerivedCoreProperties.txt
